### PR TITLE
fix: Update Terms & Conditions and Privacy Policy URLs

### PR DESCRIPTION
**Pull request by frankvonhoven**
**Description**
Updates the URLs for Terms & Conditions and Privacy Policy via `AppConstants`

---
**Screenshots/Recordings**

### Onboarding
onboarding-modal-terms-of-use
### SettingsScreen
settings-terms-of-use

### SettingsScreen
settings-privacy-policy
### Create New Wallet
https://github.com/MetaMask/metamask-mobile/assets/141057783/a0d5f93e-29b7-4c72-a8d3-ef01952a560c

---

### Terms of Use
- Scenario: Terms of use page uses `https://legal.consensys.io/metamask/terms-of-use/` from `Settings tab` > `About MetaMask` > `Terms of Use`
  - Given: I am on the `About MetaMask` page accessed from the `Settings` tab
  - And I tap on `Terms of Use`
  - Then I should see a WebView that shows `https://legal.consensys.io/metamask/terms-of-use/`

 - Scenario: Terms of use page uses `https://legal.consensys.io/metamask/terms-of-use/` from the `Import using secret recovery phrase` page's footer from onboarding
   - Given: I am on the `Import using secret recovery phrase` page accessed from onboarding
   - And I tap on `Terms of Conditions` from the footer
   - Then I should see a WebView that shows `https://legal.consensys.io/metamask/terms-of-use/`

 - Scenario: Terms of use page uses `https://legal.consensys.io/plain/terms-of-use/` the mandatory terms of use modal
   - Given: I am on the onboarding screen
   - And I tap on `Create new wallet`
   - And I skip the MetaMetrics screen
   - Then I should see a WebView that shows `https://legal.consensys.io/plain/terms-of-use/`

### Privacy policy
 - Scenario: Privacy policy page uses `https://legal.consensys.io/metamask/privacy-policy/` from `Settings tab` > `About MetaMask` > `Privacy Policy`
   - Given: I am on the `About MetaMask` page accessed from the `Settings` tab
   - And I tap on `Privacy Policy`
   - Then I should see a WebView that shows `https://legal.consensys.io/metamask/privacy-policy/`

 - Scenario: Privacy policy page uses `https://legal.consensys.io/metamask/privacy-policy/` from bottom of MetaMetrics modal
   - Given: I am on the onboarding screen
   - And I tap on `Create new wallet`
   - And I see the MetaMetrics screen
   - When I tap on the `Privacy Policy` link from the footer
   - Then I should see a WebView that shows `https://legal.consensys.io/metamask/privacy-policy/`

**Issue**

fixes [#934](https://github.com/MetaMask/mobile-planning/issues/934)

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by frankvonhoven** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Cal-L — APPROVED** [review]
LGTM

**Comment by tommasini** [comment]
Hey @frankvonhoven did you tested if it's possible to navigate to other page from the terms of use modal? 
The scenario I'm thinking about it's:
* You are on the terms of use modal on the terms of use page
* Press the hiperlink to the privacy terms
* You are redirected to there (you shouldn't be able to do that), we should make sure that the user reads the terms of use

**Comment by frankvonhoven** [comment]
@tommasini I think you can get to the Privacy Policy within the Terms of Use modal, but not other links... see video:

terms-privacy

**Comment by frankvonhoven** [comment]
That is a good question! I'm wondering why it's blocking the other webpages, I don't see anything in the WebView like `onShouldStartLoadWithRequest` to prevent navigation, maybe I'm missing something?

**Comment by cortisiko** [comment]
@frankvonhoven Feel free to kick off the E2E test run on bitrise for this PR. Once you have all ✅ , go ahead and merge this PR. cc @Cal-L

**Comment by cortisiko** [comment]
https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/d10d60e4-ac20-4a48-9fff-3355fa20913e E2E test run. Will go ahead and merge this PR.

**Review by cortisiko — APPROVED** [review]

**Pull request merged**
