### PR TITLE
Bugfix/small UI fixes

### PR DESCRIPTION
**Pull request by rickycodes**
**Description**

Just a couple small UI fixes. I noticed the spacing of the warning indication when you haven't backed up is a bit off:

**before:**

image

**after:**

image

One other thing I noticed is that we're displaying the back button on our congratulations screen, which I think is an unnecessary action for that page...

**before:**

image

**after:**

image

### CODE REVIEW

**Comment by cjeria** [comment]
These fixes look good. The only inconsistency I notice here is the "Congratulations" font. It looks like Roboto, not Euclid.

**Comment by rickycodes** [comment]
> The only inconsistency I notice here is the "Congratulations" font. It looks like Roboto, not Euclid.

I noticed we have an `extraBold` style that doesn't work on Android. I simply removed that and used our `bold` style which seems to look fine? I've updated the after screenshot above.

**Review by estebanmino — APPROVED** [review]
LGTM

**Comment by rickycodes** [comment]
couple small changes based on design QA:

On the drawer it should only say "Unprotected" as to reduce the likelihood of the string breaking on smaller devices:

image

Secondly we're moving the "Security & Privacy" settings section below "General":

image

**Comment by cjeria** [comment]
LGTM @rickycodes

**Comment by ibrahimtaveras00** [comment]
I noticed that although we removed the back button on the top left, on android, I still can push the device back button and get redirected; seen here = http://recordit.co/mLaye65Qd0

do we also want to remove that option as well?

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
I noticed that although we removed the back button on the top left, on android, I still can push the device back button and get redirected; seen here = http://recordit.co/mLaye65Qd0

do we also want to remove that option as well? 

same thing goes for the import seed phrase flow, and sync with extension flow = http://recordit.co/RdK9B8EfWW

**Comment by rickycodes** [comment]
@ibrahimtaveras00 the hardware back button should be disable now as well :)

**Review by ibrahimtaveras00 — APPROVED** [review]
QA Passed 👍

**Comment by omnat** [comment]
Didn't realized we made some changes on this screen. Pointed to @cjeria just yesterday that we need copy update on this success screen. Too late for this release, but captured in #2136 to address later.

**Pull request merged**
