### PR TITLE
feat: add MetaMetrics delete on Wallet delete

### PR DESCRIPTION
**Pull request by frankvonhoven**
## **Description**
This creates a MetaMetrics deletion task when a user deletes their wallet.

## **Related issues**

Fixes: [1271](https://github.com/MetaMask/mobile-planning/issues/1271)

## **Manual testing steps**

1. Open Flipper Network inspector
2. Go to Settings > Security
3. Delete Wallet
4. Should see Successful call to MM proxy

### **After**

https://github.com/MetaMask/metamask-mobile/assets/141057783/45472d73-29c8-4e00-ad43-74bb774a51c0

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by NicolasMassart — DISMISSED** [review]
Simple, strait to the point. I like that.
Just one note, you could also have used the useMetrics hook (app/components/hooks/useMetrics/useMetrics.ts). So make sure you are ok wit not using it. It ends being exactly the same, just a matter of code style preference.

**Comment by tommasini** [comment]
Can we try to fix this issue on this [PR](https://github.com/MetaMask/mobile-planning/issues/1271#issuecomment-2133774383) ?

**Comment by frankvonhoven** [comment]
> Simple, strait to the point. I like that. Just one note, you could also have used the useMetrics hook (app/components/hooks/useMetrics/useMetrics.ts). So make sure you are ok wit not using it. It ends being exactly the same, just a matter of code style preference.

I initially thought to use the hook, but this function `deleteUser` is a regular javascript function and not in a React component, so I wasn't able to use the hook in this case.

**Comment by frankvonhoven** [comment]
Added in clearing browser history and cache on wallet delete

**Comment by tommasini** [comment]
It seems we have a small lint issue and we are good to go

**Review by tommasini — APPROVED** [review]
LGTM! Awesome work!

**Pull request merged**
