### PR TITLE
fix crash when changing password

### PR DESCRIPTION
**Pull request by jpcloureiro**

### CODE REVIEW

**Review by andreahaku — APPROVED** [review]
LGTM even if we should understand what's not passing a valid address to the component

**Comment by blackdevelopa** [comment]
@jpcloureiro do you think if you rebased, it will fix the failing ci/audit?

**Comment by jpcloureiro** [comment]
> LGTM even if we should understand what's not passing a valid address to the component

Yes, we should check where the `EthereumAddress` component is used and what address prop is being passed on.
Let's handle that on a new issue.

> @jpcloureiro do you think if you rebased, it will fix the failing ci/audit?

Not sure. Did github publish a new vulnerability in the last hours?

**Review by cortisiko — APPROVED** [review]
✅ ✅ ✅ ✅

**Pull request merged**
