### PR TITLE
Integrate changes from controllers v15.0.2

### PR DESCRIPTION
**Pull request by adonesky1**
**Description**
- Adds migrations and required changes for breaking changes from controllers changes ([572](https://github.com/MetaMask/controllers/pull/572) and [570](https://github.com/MetaMask/controllers/pull/570))

### CODE REVIEW

**Review by Cal-L — APPROVED** [review]
LGTM. Awaiting controller update PR.

**Comment by adonesky1** [comment]
@Cal-L do you want to re-review now that the controllers version has been bumped?

**Comment by adonesky1** [comment]
Or should someone from QA review?

**Comment by adonesky1** [comment]
I've done some local testing but it would probably good to have some more reliable QA on this before merging? @ibrahimtaveras00 @Cal-L if someone has bandwidth?

**Review by Cal-L — APPROVED** [review]
LGTM!

**Comment by Cal-L** [comment]
@ibrahimtaveras00 QAd by me

**Pull request merged**
