### PR TITLE
Implemented EIP3085 & EIP3326 support for WalletConnect requests

### LINKED ISSUE #3279: WalletConnect - sendCustomRequest - wallet_addEthereumChain is not working
WalletConnect - sendCustomRequest - wallet_addEthereumChain is not working
plz add
app/components/Views/BrowserTab/index.js - rpcMethods
to app/core/WalletConnect.js (call_request event - payload.method)

### PR DESCRIPTION
**Pull request by aostrun**
**Description**

Support for EIP3085 (`wallet_addEthereumChain`) and EIP3326 (`wallet_switchEthereumChain`) via WalletConnect requests.
These RPCs are essential for a good user experience, especially now when there are a lot of DApps using Polygon or other similar chains.

Support for these two interfaces was already implemented in the app but only within the app included the browser:
https://github.com/MetaMask/metamask-mobile/blob/4f90828110a4b33d1e2ad2aa39fa59443e80f4a3/app/components/Views/BrowserTab/index.js#L755-L776

But a lot of people use WalletConnect to interface with the MetaMask mobile, and these interfaces were not supported for WalletConnect requests.

I've utilized the existing code and created a glue between the WalletConnect handler and the main React component using the existing Redux store - I simply added two new Redux states and two new actions.
WalletConnect handler triggers Redux actions which trigger the logic in the main component to open the modals.

**Checklist**

* [X] There is a related GitHub issue
* [X] Tests are included if applicable
* [X] Any added code is fully documented

**Issue**

Resolves #3279

### CODE REVIEW

**Comment by aostrun** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sethkfman** [comment]
@aostrun We will be reviewing the numerous PRs around this issue on Monday and will update the status.

**Comment by aostrun** [comment]
@sethkfman Any updates regarding this issue?

**Comment by syntichsizer** [comment]
@sethkfman cmon.

**Comment by gantunesr** [comment]
Hi @aostrun, I was reviewing this PR and it didn't work with the test cases I was using, did it work in your end?

**Comment by aostrun** [comment]
Hi @gantunesr, thanks for trying out the PR. I tested EIP3085 & EIP3326 requests using a simple custom web page that simulates a WalletConnect enabled DApp, something similar to your [Metamask Test DApp](https://metamask.github.io/test-dapp/), and everything worked fine on my side.

It might be useful to implement support for WalletConnect on the Metamask Test DApp which should allow for easier testing of the WalletConnect related stuff, I can even try to do it - it shouldn't be hard.

Here are the screenshots of the popups the mobile app loads when I send `wallet_addEthereumChain` & `wallet_switchEthereumChain` requests over WalletConnect session.
<p float="left">
	  
	  
</p>

**Comment by gantunesr** [comment]
Hey @aostrun, you're right, I just updated the test dapp with wc and it worked. We'll give you a follow up in some days about this PR.

**Comment by aostrun** [comment]
Glad to hear it works on your side too. :partying_face: 
Do you plan to integrate your work on the wallet connect support for test dapp to the main branch? It would be useful for various testing purposes. Thanks for your time!

**Comment by gantunesr** [comment]
Yes, the idea is to add more WC use cases and then merge it, you can access that work in this [branch](https://github.com/MetaMask/test-dapp/tree/wc-support) in the meanwhile

cc @andreahaku

**Comment by andrepimenta** [comment]
Will be fixed with https://github.com/MetaMask/metamask-mobile/pull/3685

**Pull request closed without merging**
