### PR TITLE
[REFACTOR] Transactions

### PR DESCRIPTION
**Pull request by gantunesr**
# Description

Refactor Transaction Activity component.

# Criteria

- [ ] Behaviour should be the same (Tx detail view, cancel tx feature, speed up tx feature)
- [ ] Update testing

### CODE REVIEW

**Review by andrepimenta — APPROVED** [review]
LGTM!

**Review by plasmacorral — CHANGES_REQUESTED** [review]
When I am tapping "Cancel" on a pending transaction, I am presented the "speed up transaction" modal instead of the cancellation modal. 

OS/Device:  (experienced on both OS, but this report & state log is from my android tests)
Android 11 build RZAS31.Q@-146-14-5
security update December 1, 2021
Moto G Play (2021)

Steps to recreate: 
Change to testnet (Ropsten), click into the asset (Eth) to view transactions, tap `send`, select/enter recipient address, tap `next`, enter amount, tap `next`, tap the estimated gas fee, tap `advanced options`, reduce `Max priority fee` and `max fee` until the red warnings are shown `_____ is low for current network conditions` using the `-`, tap `save`, tap `send`.  

Then wait for the `submitted` transaction to appear in the transaction page.  

Tap`cancel` and note that copy and options presented are for speeding up a transaction, not canceling.

Expectation: Should see copy and options to increase gas to cancel rather than speed up
[MetaMask State logs -  v4.0.1 (814).zip](https://github.com/MetaMask/metamask-mobile/files/8072604/MetaMask.State.logs.-.v4.0.1.814.zip)
.

**Review by plasmacorral — CHANGES_REQUESTED** [review]
Still seeing the issue where tapping `Cancel` on a pending transaction presents the `Speed up` copy.

Also, it feels like the transaction page doesn't refresh quickly after send.  I find myself having to go back to wallet view and then back into transactions, or needing to swipe down to refresh the transactions page.  Otherwise, its tough to see the pending transaction and make changes before the testnet transaction is accepted.

https://recordit.co/GBJFesQ2YH

**Comment by gantunesr** [comment]
Cancel issue solved in [06e05a1](https://github.com/MetaMask/metamask-mobile/pull/3517/commits/06e05a10af855ad70f4431336dd0f0fda7709273)

cc: @plasmacorral

**Review by chrisleewilcox — COMMENTED** [review]
This is failing audit checks.  Please address.

**Comment by gantunesr** [comment]
I'm closing this PR since it became stale. I'll re-open it when the priority is raised over this or our QA team increases their capacity.

**Pull request closed without merging**
