### PR TITLE
fix: crash on reload fix by patch

### PR DESCRIPTION
**Pull request by tommasini**
## **Description**

This PR fixes reload crash on IOS adding a patch found here: https://github.com/software-mansion/react-native-reanimated/issues/4783#issuecomment-1713329472

https://github.com/user-attachments/assets/f5e39b2e-ed33-446f-9837-56ce1fc54688

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Daniel-Cross — DISMISSED** [review]

**Comment by Daniel-Cross** [comment]
Works for me

**Review by EtherWizard33 — DISMISSED** [review]
tested and confirmed it fixes the refresh crash i had before

**Review by Cal-L — DISMISSED** [review]
LGTM

**Review by leotm — DISMISSED** [review]
weird how missed it in the [.72 upg](https://github.com/MetaMask/metamask-mobile/pull/9280) 🤔 bumping reanimated 3.1.0 to 3.4.2

workaround lgtm, could be worth adding comment in the patch for visibility

**Comment by tommasini** [comment]
@leotm you are right! adding the comment right now!

**Review by cortisiko — APPROVED** [review]

**Review by leotm — APPROVED** [review]

**Pull request merged**
