### PR TITLE
Bitrise yml bump version

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

### CODE REVIEW

**Comment by ShevaSHIO** [comment]
1a3ebca

**Comment by ShevaSHIO** [comment]
e47ffcd

**Comment by ShevaSHIO** [comment]
15d115f

**Comment by ShevaSHIO** [comment]
c3dd24c

**Comment by ShevaSHIO** [comment]
49a1d54

**Comment by ShevaSHIO** [comment]
1146d56

**Comment by ShevaSHIO** [comment]
c46a52d

**Comment by ShevaSHIO** [comment]
0791e96

**Comment by ShevaSHIO** [comment]
85329ce

**Comment by ShevaSHIO** [comment]
03bba69

**Comment by ShevaSHIO** [comment]
7e6e8e7

**Comment by ShevaSHIO** [comment]
bd83efc

**Comment by ShevaSHIO** [comment]
0b6b113

**Comment by ShevaSHIO** [comment]
76793db

**Comment by ShevaSHIO** [comment]
c0c7341

**Comment by ShevaSHIO** [comment]
093af53

**Comment by ShevaSHIO** [comment]
25f204e

**Comment by ShevaSHIO** [comment]
e2c3d7e

**Comment by ShevaSHIO** [comment]
468864b

**Comment by ShevaSHIO** [comment]
924f8a4

**Comment by ShevaSHIO** [comment]
ff403a9

**Comment by ShevaSHIO** [comment]
7ab21c7

**Comment by ShevaSHIO** [comment]
6141117

**Comment by ShevaSHIO** [comment]
ffd17cd

**Comment by ShevaSHIO** [comment]
3f9e8d2

**Comment by ShevaSHIO** [comment]
c7b15dc

**Comment by ShevaSHIO** [comment]
df695d1

**Comment by ShevaSHIO** [comment]
b8fcf67

**Comment by ShevaSHIO** [comment]
7f7f09a

**Comment by ShevaSHIO** [comment]
fcdea4e

**Comment by ShevaSHIO** [comment]
255e9e1

**Comment by ShevaSHIO** [comment]
76c47c3

**Comment by ShevaSHIO** [comment]
cbdfd6a

**Comment by ShevaSHIO** [comment]
8ee216f

**Comment by ShevaSHIO** [comment]
f8908aa

**Comment by ShevaSHIO** [comment]
c9ad43b

**Review by sethkfman — APPROVED** [review]

**Pull request merged**
