### PR TITLE
Experiment/upgrade react native 66

### PR DESCRIPTION
**Pull request by Cal-L**
**Description**

#3425 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

### CODE REVIEW

**Comment by cortisiko** [comment]
Here is the list i found thus far:

Issue 1 (iOS specific)

Whenever i am in the wallet view then tap on the “send”, I get an error: `VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.` 

see [here](http://recordit.co/GJxvZwAQ5e) 


Issue 1B (iOS specific)
I also encounter the same virtualization error when I attempt to Add a contact.

To reproduce:
launch the app
import your wallet/create a new account
open the drawer
tap on “Contacts”
tap on “Add Contact”

see [here](http://recordit.co/QJmLL3l0S4)


**side note about issue 1B: I also encountered an error while on the contacts view on android. I literally experienced it one time and i couldnt reproduce afterwards. Maybe look into android as well for issue 1B?**

**Comment by cortisiko** [comment]
Issue 2 (Android Specific) :

When I go to:
the burger menu
open security and privacy
 tap on the change password CTA I get: `Attempt to invoke virtual method 'android.graphics.drawable.Drawable.android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference`





**This happened one time. I cannot reproduce this anymore.**

Issue 2B

When I:
the burger menu
open security and privacy
tap on the change password CTA
enter in my old password
enter in my new password.
upon tapping on the ‘Reset password’ CTA

I get
```
Possible Unhandled Promise Rejection (id: 27):
TypeError: undefined is not an object (evaluating 'identities[selectedAddress].name')
```

see [here](http://recordit.co/B836D5uhFO)

**Comment by cortisiko** [comment]
Issue 3 (iOS specific)

I am unable to onramp with apple pay. Whenever i tap on “pay with apple pay” I get `EventEmitter.removeSubscription(...): Method has been deprecated. Please instead use `remove()` on the subscription itself.`

To reproduce:
go through the on ramp flow.
attempt to pay with apple pay.
notice the error.



see [here](http://recordit.co/jNVkUhOgEJ)

**Review by cortisiko — CHANGES_REQUESTED** [review]
Sending this back your way Cal.

**Review by cortisiko — APPROVED** [review]
🌮 🌮 🌮 🌮 🌮 🌮

**Review by gantunesr — APPROVED** [review]
LGTM. Reviewed with @Cal-L 🚀

**Pull request merged**
