### PR TITLE
refactor: generate nonces using nonce tracker

### LINKED ISSUE #7673: [Bug] Reset Account is not clearing the nonce
**Describe the bug**
_A clear and concise description of what the bug is_
When you perform a Reset Account action, the nonce is not cleared.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

https://user-images.githubusercontent.com/54408225/220074129-698a2bf4-a301-473d-8f07-037f6c1e95f1.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Advanced Settings
2. Enable Custom Nonce
3. Click Send
4. Add Recipient
5. Add Amount
6. Edit Nonce by adding +1 (if suggested nonce is 50, set it to 51)
7. Accept tx
8. Go to Advanced Settings
9. Click Reset Account
10. Click Send
11. Add Recipient
12. Add Amount
13. See nonce is not reset to step 6 (50), but incremented from step 6 (52)

**Expected behavior**
_A clear and concise description of what you expected to happen_
Nonce should be reset. See correct flow example here

https://user-images.githubusercontent.com/54408225/220076277-adc78a5f-0cd9-4989-9178-4352b871183b.mp4

**Smartphone (please complete the following information):**

- Device: Pixel 6
- OS: Android 12
- App Version: v5.14.0 (1055)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by matthewwalsh0**
### Use NonceTracker package

When sending transactions, the `nonce` value is currently generated using an `eth_getTransactionCount` query to determine the next nonce according to the network, plus a caching layer in the `NetworkController` which intercepts this query result to accommodate any pending transactions sent from the wallet.

This PR replaces all of the above and generates the `nonce` value using only the `NonceTracker` package, which internally continues to check the network nonce, and also factor pending transactions but by explicitly checking them, rather than relying on a cached value.

This same package is used in the extension.

Following the previous bug concerning incorrect `nonce` values, the `NonceTracker` usage now explicitly ignores incoming transfer transactions using the `isTransfer` property.

### Synchronise custom nonce logic 

The `NonceTracker` is now also used to propose nonces when `Customize transaction nonce` is enabled, and the related UI logic now utilises the `TransactionController` to ensure this logic remains synchronised in future.

### Generate submit history

Finally, as a means to protect the user following any nonce issues in future, a `submitHistory` array is now automatically populated whenever a transaction is successfully submitted.

This records the following data per transaction in order to support debugging efforts even after `Reset account` has been used:

- Chain ID
- Transaction Hash
- Network Type
- Network URL
- Origin
- Raw Transaction
- Time
- Transaction Parameters

This history is currently limited to the last 100 submitted transactions.

A migration has been added to generate this information from existing wallets using the transaction metadata.

## **Related issues**

Fixes: #7673 

## **Manual testing steps**

Full transaction regression.

Additional focus on all nonce edge cases including:

- Presence of incoming transfer transaction with higher nonces.
- Presence of standard incoming transactions.
- Using `Reset Account` after sending a transaction with a higher nonce.
- Cancelling a transaction with a high nonce then sending a normal transaction.
- Sending multiple pending transactions.
- Switching networks during pending transactions and after confirmed transactions.
- Using custom nonce values.

Verify the correct `submitHistory` is now added to state logs after the following scenarios:

- Use of alternate networks.
- Use of `Reset account` button.
- Upgrade from previous versions using existing transaction state.

### **After**

[Pending]

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by OGPoyraz — DISMISSED** [review]

**Review by vinistevam — DISMISSED** [review]

**Comment by sleepytanya** [comment]
Dev build iOS:
 1. `Customize transaction` nonce is disabled
 2. Send `approve transaction` from the mobile wallet to the extension wallet - nonce #45
 3. Send `transferFrom` transactions from extension wallet - nonce #65
 4. `Customize transaction nonce` is enabled 
 5. Send `approve` transaction from the mobile wallet - nonce #70 (stuck transaction)
 

https://github.com/MetaMask/metamask-mobile/assets/104780023/54268aa8-02ca-4aa3-899c-6847d17d485f


 7. `Cancel transaction` fails, `speed up the transaction` works, tx remains submitted
 8. Send `transferFrom` transaction from the extension wallet - nonce #66 (confirmed)
 

https://github.com/MetaMask/metamask-mobile/assets/104780023/a33596e1-7c38-4318-8120-03f792880a46

**Comment by sleepytanya** [comment]
Performing reset account after stuck transaction with high nonce (and subsequent transferFrom transaction) leaves only first transaction (nonce 45) in the mobile transaction history:
Screenshot 2023-11-07 at 12 16 03 AM

**Comment by sleepytanya** [comment]
Token transactions sent using transferFrom to mobile account are not detected in the incoming transaction history:
Screenshot 2023-11-07 at 12 38 02 AM
-484c-417d-a640-8e698b34632e">

**Comment by sleepytanya** [comment]
1. Enable `customize tx nonce` after `reseting` the account
2. Send `transferFrom` tx with the higher nonce to the mobile account (nonce 68)
3. Send `approve` transaction from the mobile account - transactions nonce is 81 (stuck transaction)
4. Try to send another transaction (regular eth send) from the mobile (to have multiple stuck transactions)
5. New transaction has the same nonce and replaces previous stuck transaction:

https://github.com/MetaMask/metamask-mobile/assets/104780023/35ef029a-699b-4353-a747-cf8a46fb5ac2


Screenshot 2023-11-07 at 1 10 21 AM

**Comment by sleepytanya** [comment]
All transactions performed with disabled and enabled `customize tx nonce ` were confirmed successfully.
Screenshot 2023-11-08 at 11 57 21 AM
State log file:
[fixed.txt](https://github.com/MetaMask/metamask-mobile/files/13299363/fixed.txt)

**Review by tommasini — APPROVED** [review]
LGTM!

Just have a little curious question, since I didn't debug it:

On the nonce-tracker library, we can also have the [nonce details](https://github.com/MetaMask/nonce-tracker/blob/a1ddc27ce152910a575b76b8bfc8f51713a44fc5/src/NonceTracker.ts#L172C41-L172C52) when we use the getNonceLock method

Could we have some advantage of what is returned there on the future?

**Review by OGPoyraz — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]

**Review by alanaladd21 — APPROVED** [review]

**Comment by sleepytanya** [comment]
Scenarios tested:
1.  correct `submitHistory` is added to state logs after use of alternate networks:
[before_network.txt](https://github.com/MetaMask/metamask-mobile/files/13370564/before_network.txt)
[after_network.txt](https://github.com/MetaMask/metamask-mobile/files/13370565/after_network.txt)

2. correct `submitHistory` is added to state logs after use of 'Delete wallet':
[before_reset.txt](https://github.com/MetaMask/metamask-mobile/files/13370567/before_reset.txt)
[after_reset.txt](https://github.com/MetaMask/metamask-mobile/files/13370569/after_reset.txt)

3. Stuck multiple pending transaction with `custom nonce` on and off
4. Performing transaction with higher and lower nonce with `custom nonce `enabled
5. Normal Eth `send` with the presence higher/lower nonce transactions with `custom nonce` disabled and enabled
6. Cancelling/speeding up transactions
7. Switching networks while having submitted/confirmed/queued transactions
8. Use custom nonce values
9. Perform `sendFrom` transactions with higher nonce and then perform any transactions with lower nonce with `custom nonce` enabled
10.

**Comment by sleepytanya** [comment]
Using custom nonce values:
1. Perform any transaction with the custom nonce.
2. Transaction stays submitted until you perform transaction(s) with all missing nonces in between, i.e. last nonce was 200, next custom nonce is 205, you have to send tx with nonces 201-204 to confirm transaction 205.

**Comment by hesterbruikman** [comment]
@matthewwalsh0 Can you please confirm whether this PR is `QA passed`?

cc @sethkfman

**Pull request merged**
