### PR TITLE
Fix word election error in Spanish

### PR DESCRIPTION
**Pull request by Pedro-vk**
**Description**

_"Llave" is key but is used only for keys that open doors. "Clave" is key too but is used as "secret"._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by omnat** [comment]
Hi @Pedro-vk thanks for this improvement suggestion. This word's translation is correct for some regional Spanish versions. So we're considering keeping it as is. Let us know if you have strong opinions on changing this.

**Comment by Pedro-vk** [comment]
> Hi @Pedro-vk thanks for this improvement suggestion. This word's translation is correct for some regional Spanish versions. So we're considering keeping it as is. Let us know if you have strong opinions on changing this.

I think that you should make this change for several reasons:
- Is the correct word in Spanish following the RAE dictionary (the one used for Spanish):
  - https://dle.rae.es/clave (2 definitions)
  - https://dle.rae.es/llave (noting related to secrets/cryptography)
- Is the word used on MetaMask (extension): 
  - https://github.com/MetaMask/metamask-extension/search?q=clave&unscoped_q=clave (Clave)
  - https://github.com/MetaMask/metamask-extension/search?q=clave&unscoped_q=llave (Llave)

It's true that probably in South America is used (don't know, but possible because sometimes is used a very literal translation of English for technical words)

**Review by ibrahimtaveras00 — APPROVED** [review]
👍

**Review by estebanmino — APPROVED** [review]

**Comment by estebanmino** [comment]
thanks @Pedro-vk !

**Pull request merged**
