### PR TITLE
fix: change fox svg code

### PR DESCRIPTION
**Pull request by tommasini**
**Description**
Change svg fox code

**Screenshots/Recordings**
image

**Issue**

fixes #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by Cal-L — DISMISSED** [review]
LGTM

**Review by Cal-L — APPROVED** [review]
LGTM

**Comment by yanrong-chen** [comment]
Looks good to me now, thank you @tommasini!

**Review by MarioAslau — APPROVED** [review]
Looks great!

**Pull request merged**
