### PR TITLE
Update gradle

### PR DESCRIPTION
**Pull request by rickycodes**
**Description**

Update gradle... not sure if we want to add this, but Android Studio thinks we should!

### CODE REVIEW

**Comment by nicc938** [comment]
😃

**Review by nicc938 — APPROVED** [review]

**Comment by nicc938** [comment]
😃

**Review by estebanmino — APPROVED** [review]
💯

**Comment by nicc938** [comment]
Thx

**Review by nicc938 — APPROVED** [review]

**Pull request merged**
