### PR TITLE
fix: show tokens balances after unlock wallet

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

After unlocking the wallet; tokenBalances are not being fetched from tokenBalancesController.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Import an account with tokens
2. Lock wallet
3. Unlock wallet
4. You should be able to see your token balances

### **Before**

https://github.com/user-attachments/assets/3cc02982-699d-43a3-b5d9-57a93b5aa460

### **After**

https://github.com/user-attachments/assets/8cf94bb6-533f-435f-99ad-6d614ceadb97

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by montelaidev** [comment]
It seems wrong to be subscribing to the `PreferencesController` state change because the selected account does not change when the account is unlocked. It would also cause any changes in preferences to update the token balances. I think the fix should be to have the `TokenBalancesController` subscribe to the unlock event of the `KeyringController`.

**Comment by sahar-fehri** [comment]
> It seems wrong to be subscribing to the `PreferencesController` state change because the selected account does not change when the account is unlocked. It would also cause any changes in preferences to update the token balances. I think the fix should be to have the `TokenBalancesController` subscribe to the unlock event of the `KeyringController`.

Thnx @montelaidev  for reviewing 🙏  That makes sense

**Comment by sahar-fehri** [comment]
Hello @montelaidev ! Pushed an update here [f6ba618](https://github.com/MetaMask/metamask-mobile/pull/12099/commits/f6ba618c5a5d2b0472fac9449210a20f9b2d0dce)
Eventually i did not make `tokenBalancesController` subscribe to `keyringController:unlock`; but instead `tokensController` is subscribing to it;

Because the list of tokens inside tokenBalancesController would be an empty array here https://github.com/MetaMask/core/blob/955196c58cf835d39d505369f7b38a4e8900d22e/packages/assets-controllers/src/TokenBalancesController.ts#L203

And its populated upon subscription to tokensController:stateChange https://github.com/MetaMask/core/blob/955196c58cf835d39d505369f7b38a4e8900d22e/packages/assets-controllers/src/TokenBalancesController.ts#L142

**Review by cryptodev-2s — APPROVED** [review]

**Review by owencraston — APPROVED** [review]

**Comment by Gudahtt** [comment]
Why are the token balances not persisted? I would expect them to be persisted, requiring no update upon unlock

**Comment by Gudahtt** [comment]
Ah, I see that we are not passing in the initial state of `TokenBalancesController` in `Engine.ts`. This seems like the main problem here.

**Comment by sahar-fehri** [comment]
Closing this one in favor of this https://github.com/MetaMask/metamask-mobile/pull/12108 🙏

**Pull request closed without merging**
