### PR TITLE
[FIX] Block explorer crash

### PR DESCRIPTION
**Pull request by gantunesr**
**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

There's a crash while trying to access an undefined block explorer, to reproduce the issue just add manually a new network without the block explorer url and try to access it.

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**BUG**
https://user-images.githubusercontent.com/17601467/182456429-ea8f9d8a-fac8-4bc0-818a-d5e5ce3af49f.mov

**FIX**
https://user-images.githubusercontent.com/17601467/182456263-fc2b36c9-9716-4bf3-89d0-4ba05cafdb83.mov

**Issue**

Progresses https://github.com/MetaMask/metamask-mobile/issues/4753

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by Cal-L — APPROVED** [review]
LGTM

**Review by cortisiko — CHANGES_REQUESTED** [review]
@gantunesr The initial Fix looks good. I did however run into an issue where I attempted to edit the network and then add the block explorer URL. Upon doing so, I do not see the option to get to the block explorer within the app/view token details. 

See [recording](http://recordit.co/1MGWWRJGYL) 
compared to v5.3: https://polygonscan.com/

**Review by cortisiko — APPROVED** [review]
🌮 🌮 🌮

**Review by Cal-L — APPROVED** [review]
LGTM

**Pull request merged**
