### PR TITLE
chore: Update `@metamask/controller-utils` to v3.4

### PR DESCRIPTION
**Pull request by Gudahtt**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

The `@metamask/controller-utils` package has been updated to v3.4. This package had previously been held back because v3.1.0 introduced a usage of the BigInt API, which was a compatibility issue. But that should no longer be a problem now that React Native has been upgraded.

There were no breaking changes in this range of updates, but there were a few additions and rearrangements that required substantial patch updates.

**Issue**

This change was done to simplify PR #6872, which is part of https://github.com/MetaMask/mobile-planning/issues/798

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

### CODE REVIEW

**Comment by Gudahtt** [comment]
@SocketSecurity ignore @spruceid/siwe-parser@1.1.3
    @SocketSecurity ignore apg-js@4.1.3

The parser package has been evaluated by us already, and the lack of a README in general isn't a big concern for us.

The flagged module in `apg-js` appears to be a development script included in the published package by mistake.

**Comment by Gudahtt** [comment]
Passing e2e test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/36eda36b-b4f9-4ca3-a8b9-691366cdfe85

**Comment by Gudahtt** [comment]
For reference, here is the source for v3.4.0: https://github.com/MetaMask/core/blob/%40metamask/controller-utils%403.4.0/packages/controller-utils/src/constants.ts
You can see the intended structure there.

The networks Linea Goerli and Linea Mainnet weren't added until a later version, here: https://github.com/MetaMask/core/pull/1423

**Review by leotm — APPROVED** [review]
lgtm!

**Pull request merged**
