### PR TITLE
feat: update walletconnect se-sdk to 1.7.0

### PR DESCRIPTION
**Pull request by abretonc7s**
## **Description**

Library updated to latest version.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by omridan159 — DISMISSED** [review]

**Comment by abretonc7s** [comment]
@SocketSecurity ignore-all

**Comment by christopherferreira9** [comment]
Issue 1: Can't connect to WC dapps
Steps: 
1. Go to to https://release-2-3-0.web3modal-dev.pages.dev/v2Extended
2. Click connect on the web dapp
3. Scan the QR code -> See issue

https://github.com/MetaMask/metamask-mobile/assets/104831203/1dbbf90a-b41e-4997-8364-ea3d5ea87648

Logs:
```
 ERROR  {"context": "client"} this.client.core.relayer.confirmOnlineStateOrThrow is not a function. (In 'this.client.core.relayer.confirmOnlineStateOrThrow()', 'this.client.core.relayer.confirmOnlineStateOrThrow' is undefined)
 ERROR  invalid wallet status [TypeError: this.client.core.relayer.confirmOnlineStateOrThrow is not a function. (In 'this.client.core.relayer.confirmOnlineStateOrThrow()', 'this.client.core.relayer.confirmOnlineStateOrThrow' is undefined)]
```

**Comment by christopherferreira9** [comment]
QA passed.
Connected via Qr Code and deeplink to https://feba4b8b.web3modal-dev.pages.dev/v2Customised and https://release-2-3-0.web3modal-dev.pages.dev/v2Base with both android and iOS.

**Review by andreahaku — COMMENTED** [review]
LGTM

**Review by andreahaku — COMMENTED** [review]
LGTM

**Review by andreahaku — APPROVED** [review]

**Pull request merged**
