### PR TITLE
Add IPFS gateway to remote image

### PR DESCRIPTION
**Pull request by wachunei**
**Description**

This PR uses current IPFS gateway selected in advanced settings to resolve IPFS scheme URIs

TODO:
* [x] Add support for tokens in token list, eg: FNX token
* [ ] ~~Add support for NFTs~~

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

~~Resolves #3274 #2817 #2838~~

### CODE REVIEW

**Comment by kinggongzilla** [comment]
thank you for the proposed fix! Looking forward to being accepted

**Comment by maximgeerinck** [comment]
@wachunei you can mint different types here: https://app-testnet.refinable.com/

- Video (MOV, MPV4)
- Image (PNG, JPG, GIF, ...)

let me know if you need something else. For the ipfs i used following:

- first we validate the ipfs url (there are way too many broken incorrect token urls)

```
import isIpfs, { url } from "is-ipfs";
 const isValidUrl =
    isIpfs.ipfsUrl(url) ||
    isIpfs.ipnsUrl(url) ||
    isIpfs.path(url) ||
    isIpfs.cid(url.replace("ipfs://", "")) ||
    isIpfs.cidPath(url.replace("ipfs://", ""));
  if (!isValidUrl) {
    console.error(url);
    throw new Error("given ipfs url is not valid!");
  }
```

then we replace the hash by a public node, we did add fallback for multiple nodes as it can be that for very new NFTs, not all public nodes picked up the document yet

```
const IPFS_GATEWAY = "https://cloudflare-ipfs.com";
gateway = gateway.replace("/ipfs/", "");

const hasIpfsHash = url.match(
  /\/ipfs\/Qm[1-9A-HJ-NP-Za-km-z]{44}(\/.*)?|^\/ipns\/.+/gm
);

if (hasIpfsHash) {
  return `${gateway}${hasIpfsHash[0]}`;
}

return url.replace("ipfs://", `${gateway}/ipfs/`);
```

some don't even use ipfs, so we return when the url starts with `http`

Test case can look like:

```
it.each([
  [
    "ipfs://QmY8VYrfNV1kQ9YjGjA2YdYZbZS9a1AUBM69ABkvNafH4U",
    "https://cloudflare-ipfs.com/ipfs/QmY8VYrfNV1kQ9YjGjA2YdYZbZS9a1AUBM69ABkvNafH4U",
  ],
  [
    "https://gateway.pinata.cloud/ipfs/QmSb8FZBPJA3mxmYnMP5SGWiMwvFtYbNokTp8PU4453ax4/token/63.json",
    "https://gateway.pinata.cloud/ipfs/QmSb8FZBPJA3mxmYnMP5SGWiMwvFtYbNokTp8PU4453ax4/token/63.json",
  ],
  ["https://something-random", "https://something-random"],
  [
    "https://cloudflare-ipfs.com/ipfs/QmY8VYrfNV1kQ9YjGjA2YdYZbZS9a1AUBM69ABkvNafH4U",
    "https://cloudflare-ipfs.com/ipfs/QmY8VYrfNV1kQ9YjGjA2YdYZbZS9a1AUBM69ABkvNafH4U",
  ],
  [
    "ipfs://Qmeg18ZUcmcZG7Lne5bWF1kRPrSQ7LCToBRukYZcvoq8fw/nft.png",
    "https://cloudflare-ipfs.com/ipfs/Qmeg18ZUcmcZG7Lne5bWF1kRPrSQ7LCToBRukYZcvoq8fw/nft.png",
  ],
])(`%s is a valid ipfs url`, async (url, result) => {
  expect(resolvePublicIPFSUrl(url)).toEqual(result);
});

it.each([
  ["gewgwegwge"],
  ["ipfs://weweg/few/weg/gwe"],
  ["ipfs://00545411850545614840"],
])(`%s is not a valid ipfs url`, async (url) => {
  expect(() => resolvePublicIPFSUrl(url)).toThrowError();
});
```

^All the types above we've already encountered on public collections (also the invalid ones sadly)

**Comment by wachunei** [comment]
This PR will focus on ERC720 tokens with IPFS logo image url. NFTs support will be tracked in this issue: #3310

**Review by Cal-L — APPROVED** [review]
LGTM

**Review by cortisiko — APPROVED** [review]
This guy is 👍

**Pull request merged**
