### PR TITLE
fix(browser): added remaining fields in WebSourceResponse patch

### PR DESCRIPTION
**Pull request by sethkfman**
**Description**

This PR adds properties to WebSourceResponse including headers of response.

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by sethkfman** [comment]
E2E Test: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/07bbcea1-458d-45cf-b26c-09665e410c16

**Comment by sethkfman** [comment]
E2E Tests: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/5f4fd091-26a2-4f74-9d74-b902dcb5172c

**Review by Cal-L — DISMISSED** [review]
LGTM

**Review by NEllusion — DISMISSED** [review]
Looks good

**Comment by sethkfman** [comment]
E2E Rerun: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/d5cd1c4a-0f32-41e8-af52-d1e93baeef7a

**Review by Cal-L — APPROVED** [review]
LGTM

**Pull request merged**
