### PR TITLE
[FIX] Update warning image

### PR DESCRIPTION
**Pull request by gantunesr**
# Description

Update 'Skip Account security?' modal warning image.

Old Image | New Image 
:-------------------------:|:-------------------------:
 |

### CODE REVIEW

**Comment by rickycodes** [comment]
Instead of adding this new PNG. I suggest we delete it and use `<FeatherIcon name="alert-triangle" size={20} />` which is the same and used elsewhere. wdyt?

**Review by rickycodes — CHANGES_REQUESTED** [review]
Instead of adding this new PNG I suggest we delete it and use `<FeatherIcon name="alert-triangle" size={...} />` which is the same and used elsewhere. wdyt?

**Comment by gantunesr** [comment]
@rickycodes done! (`b64f8da`)

Screen Shot 2022-01-26 at 14 37 34

**Review by rickycodes — APPROVED** [review]

**Review by Cal-L — APPROVED** [review]
LGTM

**Pull request merged**
