### PR TITLE
fix: refresh ownership status for nfts

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

When a user transfers an NFT, he will still be able to see it on the NFT tab view. 
This PR refreshes the NFTs owned by the user and displays only the ones currently owned by him.

## **Related issues**

Fixes: https://consensyssoftware.atlassian.net/browse/MMASSETS-103

## **Manual testing steps**

1. Mint an NFT using one of your accounts(ACC1).
2. Go to NFTs tab and make sure you can see your minted NFT.
3. Transfer the NFT to another account (ACC2), i used REMIX solidity IDE to deploy my contract and transfer the NFT.
4. Go to the account you sent the NFT to (ACC2)
5. Import NFT (enter address and tokenId)
6. Make sure you can see the NFT sent by ACC1
7. Go back to NFTs tab on ACC1 and make sure you no longuer see the NFT in your list

### **Before**

Account2 transferred the three nfts to Account test, and yet you still see the nfts displayed on account2.

https://github.com/MetaMask/metamask-mobile/assets/10994169/b1698965-2633-4222-bb4a-8c2f80c4a607

### **After**
Returning to account2 and refreshing the page, will remove the nft from the list.

https://github.com/MetaMask/metamask-mobile/assets/10994169/4f9c2a9d-72b5-4454-910a-eca9f2c75b43

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sahar-fehri** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by sethkfman — DISMISSED** [review]
LGTM

**Review by cortisiko — CHANGES_REQUESTED** [review]
hey @sahar-fehri can we confirm this also works on android? If possible can you add unit test coverage for this particular flow?

Also can you confirm that this bug no longer exists on your PR: https://github.com/MetaMask/metamask-mobile/issues/3406

**Review by sethkfman — APPROVED** [review]
LGTM

**Review by cortisiko — APPROVED** [review]
✅ ✅ ✅ ✅ ✅

**Pull request merged**
