### PR TITLE
Handle network changes for incoming deeplink and qr code requests.

### LINKED ISSUE #2557: Requesting token doesn't respect network
**Describe the bug**

When using the request flow, or tapping on a deeplink, we are only respecting the request's network if it's coming from a custom network, but we're not respecting Mainnet nor other default networks

**Screenshots**

In this example, I'm requesting ETH while on mainnet, but upon scanning the QR code, the network isn't being switched to Mainnet; seen here = http://recordit.co/sIUhBU0CMk

**To Reproduce**
_Steps to reproduce the behavior_
1. Create a deeplink in browser or QR code payment request from one network
2. With your device, open app and be on a different network than above request 
3. Scan QR code, or open deeplink from browser

Feel free to use this deeplink which should change network to Rinkeby:

https://metamask.app.link/send/0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6@4?value=1e15

Or scan this payment request QR code:

Screen Shot 2021-04-20 at 6 48 35 PM

**Expected behavior**

My network should automatically change according to the network of the payment request

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### LINKED ISSUE #2836: ERC681 URI doesn't change network on iOS mobile app
**Describe the bug**
[ERC-681](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md) described a network agnostic URI encoded into a QR Code that wallets could scan and set up the payment.

ethereum:0xdf3e18d64bc6a983f673ab319ccae4f1a57c7010@4?value=2900000000000000
This URI should ask the user to send 0.0029 ETH to `0xdf3e18d64bc6a983f673ab319ccae4f1a57c7010` with chain Id = 4 i.e. Rinkeby testnet.

However, after scanning the QR code in metamask, it continues to stay on the same network that I opened it in, thus discounting the chain id parameter.

Here is the QR code for everyone to test:
eth-rinkeby

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Open the app, say with network as eth-mainnet
2. Click on the button to scan a qr code
3. Scan the qr code which has a URI for a different network (like rinkeby)

**Expected behavior**
Regardless of whichever network metamask was previously in, it should change to the new network based on the chain ID.

If the relevant chain ID isn't on the app's list of configured networks, then throw a relevant error (such as "network not configured")

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 14
 - App Version 2.5.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by Fatxx**
**Description**

When a user receives an incoming request either by deeplink or QR code scan, and he doesn't have the requested network selected it should now automatically switch to the requested network or shows up an alert if the network isn't available in user preferred networks list.

**To Reproduce**
Steps to reproduce the behavior

Create a deeplink in browser or QR code payment request from one network
With your device, open app and be on a different network than above request
Scan QR code, or open deeplink from browser
Feel free to use this deeplink which should change network to Rinkeby:

https://metamask.app.link/send/0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6@4?value=1e15

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2557 and #2836

### CODE REVIEW

**Review by cortisiko — CHANGES_REQUESTED** [review]
@Fatxx sending this back your way. Below are the list of issues I found:

**Issue 1**
If I attempt to deep link to a custom network (such as matic or binance) and that network is not added to my wallet I get conflicting behavior. I see the same clipboard alert message when my network is successfully changed and in that message I  also see [“oops something went wrong please try again”](https://www.screencast.com/t/bRYgUQHc)


to reproduce: 
ensure you do not have matic added to your list of networks
deep link [here](https://metamask.app.link/send/0x0000000000000000000000000000000000001010@137/transfer?address=0xC5b2b5ae370876c0122910F92a13bef85A133E56&uint256=3e18) 

notice the [behavior](http://recordit.co/BZh0ajhoe9). 


**Issue 1B**

If i were to:
switch to a custom network. In this case i am using binance. 
create a request qr-code/deep link by going through the request flow in the app on device A, 
On device B i do not have binance (BSC) added to my wallet
scan the QR on device B 
on device B once the QR takes you to the send flow, the network work defaults to your current wallet. Shouldn’t we let the user know that they do not have the network(in this case binance) added?  

see [here](http://recordit.co/wPowiQrTAG)

**Comment by cortisiko** [comment]
**Potential Issue 3**

There is a bug with the clipboard alert whenever a network changes from a custom network back to main net. Unfortunately I am unable to provide a screenshot/recording because this happens sporadically.

**Comment by Fatxx** [comment]
@cortisiko you can QA if you like, although it needs another dev review.

**Review by cortisiko — APPROVED** [review]
🌮 🌮 🌮

**Comment by omnat** [comment]
@Fatxx did you want my input on copy on this issue? I don't see a suggestion. Am I at the wrong issue?

**Review by andrepimenta — APPROVED** [review]
LGTM!

**Comment by Fatxx** [comment]
> @Fatxx did you want my input on copy on this issue? I don't see a suggestion. Am I at the wrong issue?

@omnat I tagged you again

**Pull request merged**
