### PR TITLE
Add Aurora Token Detection

### PR DESCRIPTION
**Pull request by wachunei**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

This PR enables Aurora Token detection by patching the changes from https://github.com/MetaMask/core/pull/1327/

**Screenshots/Recordings**
Token is being autodetected:

**QA Steps**
Use any wallet with aurora tokens (like orangefox.eth) and tokens must be autodetected when token detection is on

**Issue**

Progresses #5037

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by Cal-L — DISMISSED** [review]
LGTM.

**Comment by sethkfman** [comment]
@wachunei Who is doing the QA on this ticket?

**Comment by wachunei** [comment]
> @wachunei Who is doing the QA on this ticket?

@sethkfman I don't know who will take it

**Review by mcmire — APPROVED** [review]
Patch makes sense!

**Comment by bkirb** [comment]
Screenshot 2023-05-25 at 3 55 08 PM
LGTM I verified the auto detection changes

**Pull request merged**
