### PR TITLE
refactor: Use selectors for token list controller state access

### PR DESCRIPTION
**Pull request by cryptodev-2s**
**Description**

Token list controller Redux state is now accessed excusively through selectors. This makes future state changes easier to manage.

Most of these changes consist of replacing the direct access to TokenListController State, by selectors.

**Issue**

Relates to https://github.com/MetaMask/mobile-planning/issues/1066

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

### CODE REVIEW

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Comment by Gudahtt** [comment]
Passing e2e test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/525dd0f3-2a8f-4239-97e3-56d40e784733

**Review by sethkfman — DISMISSED** [review]
LGTM

**Review by sethkfman — APPROVED** [review]
LGTM

**Pull request merged**
