### PR TITLE
chore: remove unused @metamask/oss-attribution-generator

### PR DESCRIPTION
**Pull request by legobeat**
## **Description**

As of #8862, the `@metamask/oss-attribution-generator` package devDependency is no longer used - though it's still being pulled in.
This addresses that, and bumps the version to latest (which was already being used as of #8862).

Removes problematic dependency `array-find-index`.

## **Related issues**

- #9384 

## **Manual testing steps**

- Run `yarn setup`
- Run `yarn build:attribution`

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Review by NicolasMassart — COMMENTED** [review]
resolve conflicts and ask for review again please.

**Comment by NicolasMassart** [comment]
@legobeat I sent you a Slack message as I have issues testing this PR.

**Review by NicolasMassart — COMMENTED** [review]
Hi @legobeat,
I was testing this PR and when I run `yarn build:attribution` locally, it fails (returns 1 and there's an error at the last line of the output, see the end of the log bellow) and completely removes devDependencies section form the package.json.
I believe it's not the expected behaviour, could you help me testing this properly please?

```
@metamask/react-native-animated-fox: unable to locate package.json
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Review by Gudahtt — DISMISSED** [review]
LGTM, thanks for catching that!

**Review by Gudahtt — APPROVED** [review]

**Review by sethkfman — APPROVED** [review]
LGTM

**Pull request merged**
