### PR TITLE
[WIP] server side cookies not set

### LINKED ISSUE #1273: metamask-mobile not accepting cookies from github login flow on gitcoin
Hi from Gitcoin.

weve got a few reports from users that metamask mobile is not accepting cookies set in the browser from github login flow, preventing users from logging in on gitcoin, and creating a 500 on the Gitcoin login flow.

For example i got this from a user..  

Screenshot_20200110-215041_MetaMask (1)

 The objective of this bounty is to get Gitcoin login working on metamask mobile

Suggested fix path is to clone metamask-mobile, get it running on your local, and then try to login to gitcoin.  The browser will receive a set of cookies/session variables back from Gitcoin.. which are not stored in the same manner that Chrome/Opera store them.. thus causing logins on gitcoin to fail on metamask mobile.

Please only apply to the bounty if you can get this done within 2 weeks; and if you have strong independent debugging skills.

### PR DESCRIPTION
**Pull request by mul1sh**
**Description**
Bug is  #1273

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Will eventually fix #1273

### CODE REVIEW

**Comment by danlipert** [comment]
hey @mul1sh - just checking in on your progress here, how's it going?

**Comment by mul1sh** [comment]
@danlipert I was able to get the cookies set using the react-native-cookies (lib)[https://github.com/react-native-community/cookies] but they are set in the wrong path so the crash still happens. So this is what i'm currently working on and #1273 will be fixed.

ETA 2 more days before I get it fully working in both android and ios :)

**Comment by danlipert** [comment]
@mul1sh awesome! really excited for this - thanks for the update! 👍

**Comment by estebanmino** [comment]
Hi @mul1sh still working on this?

**Comment by mul1sh** [comment]
@estebanmino  yep very actively working on this. I've been trying out a couple of fixes for this where I have it working but I had to introduce another 3rd party dependency or I downgrade the react-native version.

**Comment by estebanmino** [comment]
Hi @mul1sh still working on this?

**Comment by mul1sh** [comment]
@estebanmino Yes I am, very much working on this. Expect a final commit with all my changes tomorrow, I'm just wrapping up testing as I type thiss.

**Comment by mul1sh** [comment]
@estebanmino sorry got a bit distracted by all this lockdown business, but anyway wrapping this up now, expect a push with the updated PR in the next few hours.

**Comment by mul1sh** [comment]
Rebasing my local commits and then I finally push & fix #1273

**Comment by mul1sh** [comment]
Almost done fixing an android X issue & also rebasing my local commits and then I finally push & fix #1273

**Comment by mul1sh** [comment]
Almost done with my fix and then I sort #1273

**Comment by mul1sh** [comment]
Testing my android X fix and then I finally sort #1273

**Comment by estebanmino** [comment]
@mul1sh closing this due to inactivity, feel free to open a new one when the fix is finished.

**Pull request closed without merging**
