### PR TITLE
chore: update the 'sendMessage' method in the 'DeeplinkProtocolService' class

### PR DESCRIPTION
**Pull request by omridan159**
## **Description**

Updated the `sendMessage` method in the `DeeplinkProtocolService` class.

#### Changes Made:
- Attached `chainId` and `selectedAccounts` to each sent message.

#### Code Snippet:
```typescript
async sendMessage(message: any, forceRedirect?: boolean) {
  const messageWithMetadata = {
    ...message,
    data: {
      ...message.data,
      chainId: this.getChainId(),
      accounts: this.getSelectedAccounts(),
    },
  };
  // rest of the method implementation
}
```

### This PR addresses several key issues and enhancements:

1. Account Screen Hang Fix:
- Resolved an issue where the account screen would hang due to a chain mismatch. Now, users will either be switched automatically or prompted to switch chains, ensuring a smooth user experience.

2. Chain Switching Improvement:
- Enhanced the handling of chain switching. Users can now switch chains in MetaMask without unnecessary alerts or state preservation issues. This allows for a more seamless interaction with Warpcast.

3. Batch Request Handling:
- Fixed the problem where batch requests were returning empty arrays. The system now correctly handles batch requests with methods like wallet_switchEthereumChain.

4. Deeplink Protocol Service Updates:
- Updated the sendMessage method to include chainId and selected accounts in the message metadata. This ensures that all messages carry the necessary information for accurate processing.
- Improved the handling of multichain RPC call responses, ensuring that batch RPC responses are managed correctly and users are redirected appropriately if an error occurs.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by andreahaku — DISMISSED** [review]
LGTM

**Review by elefantel — DISMISSED** [review]
Looks good

**Comment by christopherferreira9** [comment]
Good for iOS and Android using the ReactNative SDK.

**Test cases**
------------------------------------
**GIVEN** that a user has a ReactNative SDK dapp installed on iOS
**WHEN** the user changes the chain on the wallet side after connecting
**AND** the user tries to sign
**THEN** the user should get a message warning that chains are out of sync

**GIVEN** that a user has a ReactNative SDK dapp installed on Android
**AND** the user tries to sign
**WHEN** the user changes the chain on the wallet side after connecting
**THEN** the suer should be prompt to sign

**GIVEN** that a user has a ReactNative SDK dapp installed on iOS
**WHEN** the user tris to perform `batch` with: switchChain + sign
**THEN** the response should not contain the null in the first response

**Review by elefantel — APPROVED** [review]
Looks good

**Pull request merged**
