### PR TITLE
fix: Remove fallback

### PR DESCRIPTION
**Pull request by tommasini**
**Description**
Remove fallback, more information on this [issue](https://github.com/MetaMask/MetaMask-planning/issues/822)

**Core pr**
https://github.com/MetaMask/core/pull/1532

**Screenshots/Recordings**
https://recordit.co/WW4TvM6fZ4

**E2E test**
https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/4088eeac-b0df-4e09-9e09-7202f292527f

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by Cal-L — APPROVED** [review]
LGTM

**Review by Cal-L — CHANGES_REQUESTED** [review]
Can we test what happens when NFT info fails to fetch from on chain AND fallback is removed?

**Comment by tommasini** [comment]
Hey @Cal-L the result of this test is [here](https://github.com/MetaMask/MetaMask-planning/issues/822#issuecomment-1642673231)

**Comment by Cal-L** [comment]
> Can we test what happens when NFT info fails to fetch from on chain AND fallback is removed?

Perfect. thank you

**Review by Cal-L — APPROVED** [review]
LGTM

**Pull request merged**
