### PR TITLE
[FIX] Reject grant permission cancel transaction

### PR DESCRIPTION
**Pull request by tommasini**
**Description**
When we tried to reject permission for a contract to be able to use the wallet funds, we didn't answer back to the dapp and did not cancel the transaction. This would let the dapp be waiting for some answer.

**Proposed Solution**
 Cancel the transaction when the user rejects the permission

**Code Impact**
Low

**Screenshots/Recordings**
The issue:
https://recordit.co/3kEkR6MBZA
The solution:
https://recordit.co/abWG79D8rJ

**Test Case**
Case1:
 * Go to https://swap.cow.fi/#/swap?chain=mainnet on our in app browser, chrome or chrome desktop
 * Connect (via wallet connect or in-app browser)
 * SWAP WETH for one random token like ZRX (Can not be ether, try always a token that we usually do not swap)
 * Press "Allow cow swape to use your WETH"
 * On MM mobile app, reject the permission that is being asked

**Issue**

Progresses #4482 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by blackdevelopa — COMMENTED** [review]
LGTM. Kindly confirm the copy, `You've rejected granting permission` with Design and Product.

**Comment by tommasini** [comment]
@blackdevelopa Thanks for the review! Waiting for answer 🚀

**Review by blackdevelopa — APPROVED** [review]
Awesome work, Tomas. 🚀

**Review by cortisiko — APPROVED** [review]
This PR is QA passed!

**Pull request merged**
