### PR TITLE
chore: Replaced ApplePayButton colors with hardcoded hex colors

### LINKED ISSUE #8286: [MOB] Replace tokens with hex colors for Apple Pay Button
[MOB] Replace tokens with hex colors for Apple Pay Button

### PR DESCRIPTION
**Pull request by brianacnguyen**
## **Description**

Replaced ApplePayButton colors with hardcoded hex colors

## **Related issues**

Fixes: #8286

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

N/A
## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by wachunei** [comment]
This is against a lint rule about literal colors. Is there a reason to not have these as constants?

**Review by georgewrmarshall — COMMENTED** [review]
It would be good to use brand colors here

**Review by georgewrmarshall — DISMISSED** [review]

**Comment by georgewrmarshall** [comment]
> This is against a lint rule about literal colors. Is there a reason to not have these as constants?

I agree with this. Does it not make sense to have all non design token colors in mobile defined in one central file `styles/common`

**Comment by brianacnguyen** [comment]
> This is against a lint rule about literal colors. Is there a reason to not have these as constants?

it was to make sure that the colors stay hardcoded as true black and white, as dictated by the apple guidelines. I've updated the code to use constants instead with notes to not change the values instead

**Review by wachunei — APPROVED** [review]

**Review by georgewrmarshall — APPROVED** [review]
Nice work

**Pull request merged**
