### PR TITLE
feat(ci): removed the matrix option from unit testing

### PR DESCRIPTION
**Pull request by sethkfman**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

Remove the matrix set of unit tests to allow for a single code coverage file generation. The CI run time is approx. +/- 2 min the same as the existing matrix. 
- Matrix CI: https://github.com/MetaMask/metamask-mobile/actions/runs/4984821356 
- Non-Matrix (this PR) CI: https://github.com/MetaMask/metamask-mobile/actions/runs/4985772216 

**Screenshots/Recordings**

NA

**Issue**

NA

**Checklist**

* [NA] There is a related GitHub issue
* [NA] Tests are included if applicable
* [NA] Any added code is fully documented

### CODE REVIEW

**Review by Cal-L — APPROVED** [review]
LGTM.

**Review by leotm — APPROVED** [review]
this means the `components-ui` units no longer run `./scripts/run-component-tests.js` right
non-matrix CI's passing anyhow, but doesn't look like GH actions expose memory usage to confirm

as an aside locally `test:unit` with `jest ./app/components/UI/` only hitting 2.7GB ram max now for a node process 🎉 so we might be able to revert the temp fix before Jest v29 cc @Gudahtt

**Comment by sethkfman** [comment]
@leotm The updated action is actually running: `"test:unit": "jest ./app/ ./locales/",` which runs all the tests in ./app. Let me know if I am missing something in your response. Thx

**Comment by leotm** [comment]
> @leotm The updated action is actually running: `"test:unit": "jest ./app/ ./locales/",` which runs all the tests in ./app. Let me know if I am missing something in your response. Thx

yep nth missing and updated GH action runs that ^ coverage remains the same 👍

_but_ CI no longer runs `"test:unit:components-ui": "./scripts/run-component-tests.js"` to fix [memory leak](https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/gh/metamask/mobile-planning/477) on ``./app/components/UI/`` tests, afaik this is ok (the node process was hitting 23 GB only locally, then net freeze)
just observing seems resolved (2.7 GB) now locally, so we/i can revert the temp fix script pre Jest 29 if agreed
i.e. a chance to clean up tech debt earlier than we expected

**Comment by Gudahtt** [comment]
Interesting. So I guess whatever was causing the explosion in memory usage has been fixed. I wonder what the culprit was.

Perhaps the known Jest memory leak that has no solution until v29 was just a small part of the problem, and the bigger issue was something else entirely.

**Comment by Gudahtt** [comment]
Either way, this seems to work, so I guess we're good for now! We can reduce memory usage further with Jest v29 as we had planned.

Nit: is there any point in keeping around the subdivided unit test scripts, and the Bash script I wrote for the component tests? May as well delete them, I doubt they'll be much use locally.

**Pull request merged**
