### PR TITLE
chore: selectors confirmations dir

### LINKED ISSUE #10309: chore: Abstract controller selectors in `confirmations` dir
### What is this about?

This task is a prerequisite for abstracting controller selectors in preparation for optimizing selectors (memoization). This task focuses on files in the `confirmations` dir.

### Scenario

_No response_

### Design

_No response_

### Technical Details

Abstract selectors for the following files. If the selector doesn't exist yet, we will need to create them in the `selectors` dir

- [x] app/components/Views/confirmations/Approval/index.js
  705,23:   transactions: state.engine.backgroundState.TransactionController.transactions,

- [x] app/components/Views/confirmations/ApproveView/Approve/index.js
  920,23:   transactions: state.engine.backgroundState.TransactionController.transactions,
  930,22:   addressBook: state.engine.backgroundState.AddressBookController.addressBook,

- [x] app/components/Views/confirmations/components/ApproveTransactionReview/AddNickname/index.tsx
  270,22:   addressBook: state.engine.backgroundState.AddressBookController.addressBook,

- [x] app/components/Views/confirmations/components/EditGasFeeLegacyUpdate/index.tsx
  90,13:       state.engine.backgroundState.GasFeeController.gasEstimateType,

- [x] app/components/Views/confirmations/Send/index.js
  784,22:   addressBook: state.engine.backgroundState.AddressBookController.addressBook,

- [x] app/components/Views/confirmations/SendFlow/AddressList/AddressList.tsx
  58,13:       state.engine.backgroundState.AddressBookController.addressBook,

- [x] app/components/Views/confirmations/SendFlow/Confirm/components/CustomGasModal/CustomGasModal.tsx
  55,13:       state.engine.backgroundState.GasFeeController.gasEstimateType,

- [ ] app/components/Views/confirmations/SendFlow/SendTo/index.js
  670,22:   addressBook: state.engine.backgroundState.AddressBookController.addressBook,

### Threat Modeling Framework

_No response_

### Acceptance Criteria

- App behavior remains the same
- Spot check the flows where changes were made to confirm consistent behavior

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

_No response_

### PR DESCRIPTION
**Pull request by tommasini**
## **Description**

Add selectors to confirmations directory

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

https://github.com/user-attachments/assets/a3f026c2-a10e-4254-b7f0-9415ffc5cd8a

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by matthewwalsh0 — DISMISSED** [review]

**Comment by tommasini** [comment]
Let's only merge this PR once the Transaction Controller to v35 is merged!

**Review by OGPoyraz — DISMISSED** [review]

**Review by MarioAslau — DISMISSED** [review]
LGTM !

**Review by MarioAslau — DISMISSED** [review]
Looks good!

**Review by MarioAslau — APPROVED** [review]

**Review by Jonathansoufer — APPROVED** [review]
LGTM!

**Review by omridan159 — APPROVED** [review]

**Pull request merged**
