### PR TITLE
Release 2.1.3: Hotfix analytics try catch

### PR DESCRIPTION
**Pull request by andrepimenta**
**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

### CODE REVIEW

**Review by rickycodes — APPROVED** [review]
LGTM

**Comment by ShevaSHIO** [comment]
30bd188

**Comment by ShevaSHIO** [comment]
d56cd14

**Comment by ShevaSHIO** [comment]
65e8c1b

**Pull request merged**
