### PR TITLE
feat: Signature Controller v5.3.1

### PR DESCRIPTION
**Pull request by tommasini**
Minor update of signature controller to 5.3.1, signature controller on this version have the approval controller as a dependency on versino 3.5.1 that we do not have yet on mobile, with this being said, everything seems to be working but it is better to ship this updates together for we have the dependencies aligned

This is the issue that updates approval controller: https://github.com/MetaMask/mobile-planning/issues/1604

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

Exploratory signs with E2E test dapp and send transaction o sepolia: https://recordit.co/69lqoJGUag

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by MarioAslau — APPROVED** [review]
LGTM

**Comment by Cal-L** [comment]
Looks like the approval controller dependency bump is from 3.5.0 -> 3.5.1, which only bumps the patch version of base controller from ^3.2.0 -> ^3.2.1. The patch versions doesn't seem to have breaking changes, so we should be good. @tommasini Is it a simple task to bump approval controller to 3.5.1?

**Comment by tommasini** [comment]
The task to bump the approval controller is mixed with the bump of transaction controller, I would like to merge this PR after that one

That issue,  is responsability of confirmations team and is blocked by the network controller PR

Approval controller issue: https://github.com/MetaMask/mobile-planning/issues/1604

Network controller PR: https://github.com/MetaMask/metamask-mobile/pull/8952

**Comment by tommasini** [comment]
Merging this since the dependency is not a breaking change!

**Pull request merged**
