### PR TITLE
Added .ruby-version

### PR DESCRIPTION
**Pull request by Zidail**
**Description**
---

#### What Changed:

- Added `.ruby-version` and set project ruby version to 2.3.7

#### Why create a separate file for saving the ruby version?

Just like how we specify which version of node we need to use with the `.nvmrc`, we should also specify which version of ruby we should use.

Adding this file allows us to tell `rbenv` and `rvm` which version should be used for this project and minimize conflicts that may arise from different contributors using  different versions of ruby.

**Checklist**
---

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves None

### CODE REVIEW

**Comment by brunobar79** [comment]
Hey @Zidail, thanks for your PR!

Regarding the `.ruby-version` addition, that's a good idea, but I'd prefer to use  2.3.7 which is what's installed by default in MacOS Mojave and it's what we use on CI. 

Regarding moving the gemfile to the root, I don't think that's necessary cause we're not using ruby at all for android projects, so I'd prefer to keep it like that.

In the future, when you have ideas like this I recommend you to open a github issue first to start a discussion before doing any work so we're all in the same page.

**Review by brunobar79 — CHANGES_REQUESTED** [review]
Hey @Zidail, thanks for your PR!

Regarding the .ruby-version addition, that's a good idea, but I'd prefer to use 2.3.7 which is what's installed by default in MacOS Mojave and it's what we use on CI.

Regarding moving the gemfile to the root, I don't think that's necessary cause we're not using ruby at all for android projects, so I'd prefer to keep it the way it is.

In the future, when you have ideas like this I recommend you to open a github issue first to start a discussion before doing any work so we're all in the same page.

**Comment by Zidail** [comment]
@brunobar79 Thanks for the feedback. I'll be sure to do that in the future.
I'll update this branch to only include the `.ruby-version` and update that to use 2.3.7 instead.

**Review by brunobar79 — APPROVED** [review]
👍

**Pull request merged**
