### PR TITLE
Style updates

### PR DESCRIPTION
**Pull request by rickycodes**
re-opening this sine I merged #2201 too early my bad.

**Description**

Some design inconsistencies Christian brought up being addressed in this PR

This PR actually makes a lot of style updates so I will go through them:

1. The `baseStyles.black` has been updated to not be absolute black.

2. Type face updated in asset list for adding Tokens:

| Before:  | After: |
| ------------- | ------------- |
| image | image

3. Type face updated in `BaseNotification` component:

| Before:  | After: |
| ------------- | ------------- |
| image | image

3. Create password

| Before:  | After: |
| ------------- | ------------- |
| image | image

4. Import from Seed

| Before:  | After: |
| ------------- | ------------- |
| image | image

5. Login

| Before:  | After: |
| ------------- | ------------- |
| image | image

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
this was already approved the last time 😅

**Comment by rickycodes** [comment]
> this was already approved the last time

I know :sob: 

needed re-approval because of the revert

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
only one place looked off to me in terms of UX

The "Create a new wallet" flow on Wallet setup, the green arrow indicating the passwords match is misaligned 

image

**Review by ibrahimtaveras00 — APPROVED** [review]
All good now 

image

QA Passed 👍🏽

**Pull request merged**
