### PR TITLE
test: flag Confirmations tests as Smoke tests

### PR DESCRIPTION
**Pull request by seaona**
## **Description**
In this PR we are flagging all the Confirmations tests as Smoke test. This includes the following spec files:

- advanced-gas (the only one that was previously flagged as Smoke)
- approve-default-erc
- eth-sign
- personal-sign
- send-erc20
- send-erc721
- send-eth
- typed-sign
- typed-sign-v3
- typed-sign-v4

Notice the amount of time added on the runs is not significant compared to the amount of scenarios we add, giving everyone more confidence on making changes in the Wallet. See numbers below.

Notice the tests are stable, being 100% Successful after several ci runs. This was achieved thanks to [this fix](https://github.com/MetaMask/metamask-mobile/pull/7802) by @vinistevam 

###  Recent examples how Confirmations tests captured an error on `main`
- [Here](https://consensys.slack.com/archives/C02U025CVU4/p1699963068242849?thread_ts=1699950726.232009&cid=C02U025CVU4) is an example of how running all the Confirmations tests, would have captured and prevent an error in `main`. Luckily we were running them locally and could spot the error and connect the dots with the slack thread.

- [Here](https://github.com/MetaMask/metamask-mobile/issues/7920) Signatures flow broken in main, that would have been captured by Confirmations tests if run as Smoke  https://app.bitrise.io/build/fa65a941-6cd6-4b0c-9ece-151e76cdbb0d

#### Run #1 - Detox Build & Test
- ios: 16m 31s
- android: 36m 09s
- bitrise: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/10633145-b793-4ac3-8d9b-316ca24586f8

#### Run #2 - Detox Build & Test
- ios: 18m 15s
- android: 34m 15s
- bitrise: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/aad945da-60b3-49f2-ae89-18a6a59efe35

#### Run #3 - Detox Build & Test
- ios: 17m 30s
- android: 36m 12s
- bitrise: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/a9bd1bd3-a23f-4535-9b21-8475ca790980

#### Run #4 - Detox Build & Test
- ios: 18m 47s
- android: 35m 58s
- bitrise: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/3109490d-0355-4eb3-bbed-bedd644f26d9

#### Run #5 - Detox Build & Test
- ios: 16m 57s
- android: 32m 02s
- bitrise: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/69a433eb-0bb0-4b67-95b2-c58145cc8963

## **Related issues**

Fixes: #

## **Manual testing steps**
Trigger ci test runs from Bitrise and see that all tests are passing.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by cortisiko — CHANGES_REQUESTED** [review]
Can we remove the type-sign test from the smoke tag? It takes[ 5 mins](https://addons-testing.bitrise.io/builds/faea2f40-6f02-408e-912a-f2be09c25583/summary?status=failed) for that one spec file to run compared to the other tests which take ~1 minute.

**Comment by seaona** [comment]
> Can we remove the type-sign test from the smoke tag? It takes[ 5 mins](https://addons-testing.bitrise.io/builds/faea2f40-6f02-408e-912a-f2be09c25583/summary?status=failed) for that one spec file to run compared to the other tests which take ~1 minute.

thanks for your comment @cortisiko . It's true that typed signature spec took a bit longer. We've re-arranged the tests so we can benefit of the parallelization.
Having Signatures included in the Smoke test pipeline is really important for Confirmations flow, so we'll like to re-evaluate it with the new timings (once we have the data).
Currently[ Signatures are broken in main](https://github.com/MetaMask/metamask-mobile/issues/7920), and that's something that could have been captured by these tests. We can re-run the jobs once that issue is fixed (now tests will fail) and post the results here.

**Comment by cortisiko** [comment]
@seaona amazing, thanks for splitting the tests. 

> Currentlyhttps://github.com/MetaMask/metamask-mobile/issues/7920, and that's something that could have been captured by these tests.


Actually, the nightly regression test build (which includes these signature tests) caught the failing tests. They should be fixed in main now. Feel free to pull in main and rerun the tests.

**Comment by seaona** [comment]
## Run after Signatures Change - Detox Build & Test

- ios: currently failing due to issue with pods in `main`
- android: 30m 50s
- bitrise: https://app.bitrise.io/build/2cad43f1-9db3-4538-9eb5-8bd6cfe95dd0

**Review by cortisiko — DISMISSED** [review]
PR looks good. Nit: Can you put the sign tests in a signatures folder?

**Review by cortisiko — APPROVED** [review]

**Review by cryptotavares — APPROVED** [review]

**Pull request merged**
