### PR TITLE
Tokens view

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

This pull request adds the ability to handle assets (ERC20), adding manually custom tokens.

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented
* [x] Get tokens from GABA
* [x] Add custom tokens

Related #61 

**WIP**

customtoken

### CODE REVIEW

**Review by brunobar79 — CHANGES_REQUESTED** [review]
Honestly I'm impressed with the quality and speed that you made this.  🥇 

I've added a few of comments mostly about the code style or some RN specifics, but otherwise looks great!

It would be great if you can add unit tests for this new components (not e2e yet because I didn't set it up for android)

**Review by brunobar79 — DISMISSED** [review]

**Review by bitpshr — CHANGES_REQUESTED** [review]
This code looks great and this is a very strong first PR against this project. Really great work. The code quality is top-notch, existing patterns were followed, and things work and work well.

I left a lot of nit-picky comments only to be thorough and to help you quickly identify what should be fixed. Every comment is minor, so don't let the number of comments discourage you. This is great stuff. Also, some general comments:

- All components should at least have a snapshot test.
- _Any_ component that shows text should have a class applied with at least a `fontStyle` so the correct font family is applied. This includes inputs, `<Text>` components, etc.
- We should create a ticket to finish the remainder of token adding, like searching for tokens.

**Review by brunobar79 — APPROVED** [review]
👍  After the last round of comments

**Review by bitpshr — APPROVED** [review]
Looks great! Very strong work.

**Pull request merged**
