### PR TITLE
chore: [Design quality] Update token details

### PR DESCRIPTION
**Pull request by gambinish**
## **Description**

Design direction here: https://www.figma.com/design/TfVzSMJA8KwpWX8TTWQ2iO/Asset-list-and-details?node-id=4746-41582&node-type=canvas&t=Tuq7jbo7koNWMiJq-0

There we a few components added after this direction was given. I also took the opportunity to align these new components as well.

Additionally, I updated some alignment of the `TransactionListItem` since I was in the area. This wasn't specifically requested in the design feedback, but since I was here I figured I would look into it. I can revert these changes if it's not intended.

## **Related issues**

Fixes: https://consensyssoftware.atlassian.net/browse/MMASSETS-401
GH Issue: https://www.figma.com/design/TfVzSMJA8KwpWX8TTWQ2iO/Asset-list-and-details?node-id=4746-41582&node-type=canvas&t=Tuq7jbo7koNWMiJq-0

## **Manual testing steps**

1. Go to a token, ideally one where you have some activity
2. Validate design expectation

### **Before**

https://github.com/user-attachments/assets/4f795bc8-7491-459a-9778-11675b706841

solution

### **After**

https://github.com/user-attachments/assets/c228d8fb-5668-4d3a-a290-71e9c0befcc9

solution

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by amandaye0h** [comment]
`Ethereum (ETH)` still looks a bit smaller than`58.75 Today` — can you confirm if both of them are the same style, `body-md-medium`? Should be `14px`, `medium/500`, no letter spacing, line height `22px`.

Screenshot 2024-09-26 at 5 10 11 PM

**Comment by amandaye0h** [comment]
We'd also want the red lines to be blue. This should be the color for the `3M` view (`0:15` in your video):
 
Screenshot 2024-09-26 at 5 15 07 PM

**Review by Matt561 — DISMISSED** [review]
The changes to `<StakingEarnings />` make sense 👍

**Review by amandaye0h — DISMISSED** [review]
Approving to unblock you since I am OOO Sept 30-Oct 8

**Comment by gambinish** [comment]
https://github.com/MetaMask/metamask-mobile/pull/11470#issuecomment-2378153177

this should be addressed here: https://github.com/MetaMask/metamask-mobile/pull/11470/commits/b9fc1d6086d234cad513e62c1784b3ba5b1309d9

**Comment by cortisiko** [comment]
@gambinish if you havent already, can you also test on a smaller screen device?

**Comment by gambinish** [comment]
@cortisiko I've attached two screenshots of an iPhone 15 Pro Max (large screen) and an iPhone XS (small screen)

I think the designs look fine. Could you review and approve if you agree?

Screenshot 2024-09-30 at 2 45 28 PM
Screenshot 2024-09-30 at 2 43 04 PM

**Review by cortisiko — APPROVED** [review]
🎉 🎉 🎉

**Review by bergeron — APPROVED** [review]

**Pull request merged**
