### PR TITLE
fix: update default search engine to google

### PR DESCRIPTION
**Pull request by mindofmar**
## **Description**

1. What is the reason for the change?

We have received several reports of phishing links being the top result within DuckDuckGo's search engine when searching for official web3 sites. This is a security risk to users and creates a poor user experience if the user cannot trust the search results.

[See example here.](https://github.com/user-attachments/assets/d512f54c-06be-4120-970a-1edee0484a32) (first result is a phishing link, shown above the official Uniswap.org website)

3. What is the improvement/solution?

Switch the default search engine to Google, which shows more reliable results.

## **Manual testing steps**

1. Go to the Explore tab
2. Run a search query using the mobile browser
3. Ensure that the Browser searches on Google instead of DuckDuckGo

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by mindofmar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by vinnyhoward — APPROVED** [review]

**Review by vinnyhoward — CHANGES_REQUESTED** [review]
Pulled it down and works great, PR looks good as well. But I did encounter an issue where DDG would persist. I had to delete the app or the changes won't take hold.

**Comment by mindofmar** [comment]
Hey @vinnyhoward would you mind pulling in my changes and re-trying? I've added a migration script.

**Comment by Cal-L** [comment]
Failures on Bitrise not related to this PR

**Review by Cal-L — APPROVED** [review]
LGTM

**Review by vinnyhoward — APPROVED** [review]
Pulled down and tested. LGTM✅

**Pull request merged**
