### PR TITLE
fix: add a section for stakeholder reviews in issue template

### PR DESCRIPTION
**Pull request by gauthierpetetin**
## **Description**

Adds a section for "stakeholder reviews" in general issue template.
This gives the opportunity to indicate, when creating a new issue, if the work needs to be reviewed by specific stakeholders before being merged.

[Same PR for Extension](https://github.com/MetaMask/metamask-extension/pull/21783)

## **Related issues**

- NA

## **Manual testing steps**

1. Go to this [test repo](https://github.com/gauthierpetetin-test/repo_test/issues/new?assignees=&labels=&projects=&template=general_issue.yml)
2. Create a new issue

## **Screenshots/Recordings**

Screenshot 2023-11-09 at 18 02 44

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Cal-L — DISMISSED** [review]
LGTM

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
@gauthierpetetin can we re-word avoid QA statement?  We want to encourage a thoughtful process for teams to make a sufficient determination if a PR should go to QA or if it's not necessary.  Something like...
"Automation tests are required to pass before merging PRs but not all changes are covered by automation tests.  Please review if QA is needed beyond automation tests."

**Comment by gauthierpetetin** [comment]
@chrisleewilcox yes that makes sense, it's updated now. Thanks for the review.

**Review by NicolasMassart — COMMENTED** [review]
Is this change going to be clear enough for external users?
Should we add something like "leave this blank if you are not part of MM team"? and then check the box on our side when we qualify issues?

**Comment by gauthierpetetin** [comment]
@NicolasMassart , yes good point, it is updated now

**Review by NicolasMassart — APPROVED** [review]
Looks good to me.

**Review by chrisleewilcox — APPROVED** [review]
LGTM

**Pull request merged**
