### PR TITLE
feat(ci): upgrade ruby to 3.0.0

### PR DESCRIPTION
**Pull request by sethkfman**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

This PR adds a ruby-version and Gemfile that enforces minimum versions of Ruby and cocoa pods.
Versions are set to:
- Ruby Version: 3.0.0
- Cocoapods Version: 1.12.1

Successful QA build: https://app.bitrise.io/build/39b514f5-4579-4e7a-bcbe-03945bc4860f

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by sethkfman** [comment]
Successful QA build: https://app.bitrise.io/build/39b514f5-4579-4e7a-bcbe-03945bc4860f

**Comment by sethkfman** [comment]
Pending QA E2E build: https://app.bitrise.io/build/2befc39b-f2f3-43eb-8543-afe1d84da751

**Review by Cal-L — APPROVED** [review]
LGTM

**Review by leotm — APPROVED** [review]

**Review by leotm — COMMENTED** [review]
just spotted the files introduced later in RN 0.67+ (nb: our 0.66.5)
https://github.com/facebook/react-native/blob/0.67-stable/template/Gemfile
https://github.com/facebook/react-native/blob/0.67-stable/template/_ruby-version
along with the Gem lockfile we didn't include
https://github.com/facebook/react-native/blob/0.67-stable/template/Gemfile.lock

presuming we're introducing these ahead for added security?
to prevent unmaintained Ruby v2.7 (EOL 31 Mar 2023) usage

edit: yeah makes sense, remembering now spotting the warning few mo ago
- https://github.com/facebook/react-native/issues/35807#issuecomment-1378837476

**Pull request merged**
