### PR TITLE
Fix browser initial loading performance

### LINKED ISSUE #1543: Android performance issue: delay of browser page load
This requires more investigation as to the cause. When loading the app / logging in, there can be a noticeable amount of time between the mounting of the browser component and the beginning of the loading of the url the user was one when they last closed the browser.

We need to pinpoint the source of this slow down and then fix it.

### PR DESCRIPTION
**Pull request by andrepimenta**
**Description**

This fixes the browser initial load performance issue. The initial loading was being delayed mainly because:
- We were getting the `InpageBridgeWeb3` from the Filesystem which is very slow. The fix was creating a helper that gets the `InpageBridgeWeb3` on app init asynchronously so that when the user gets to the browser it is already loaded. 
- And also by an unnecessary timeout on the init function. The fix was bypassing this timeout on initial load.

This should make the time between the mounting of the browser component and the beginning of the loading be almost instantaneous.

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #1543

### CODE REVIEW

**Review by rickycodes — APPROVED** [review]
LGTM

**Review by danjm — APPROVED** [review]
this is a great solution

**Review by ibrahimtaveras00 — APPROVED** [review]
QA Passed 👍

**Comment by tangten** [comment]
hi @andrepimenta, do we public InpageBridgeWeb3 file? I want to inject window.ethereum manually for my dapps browser personal

**Pull request merged**
