### PR TITLE
feat: QR-based add NGRAVE ZERO Hardware

### PR DESCRIPTION
**Pull request by xardass**
## **Description**

Hello,

This PR changes the UI and text to add the NGRAVE ZERO hardware wallet.

Our upcoming release planned for the beginning of July will add QR code compatibility with MetaMask following EIP-4527.

## **Related issues**

Fixes: https://github.com/MetaMask/accounts-planning/issues/536

See the corresponding changes in the extension: https://github.com/MetaMask/metamask-extension/pull/25080 

## **Manual testing steps**

1. Add a QR based wallet on MetaMask Mobile
2. Scan the QR code from the hardware wallet.

### **Before**

image

### **After**

image

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by caiquecruz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Akaryatrh — DISMISSED** [review]

**Review by gantunesr — DISMISSED** [review]

**Comment by Akaryatrh** [comment]
@xardass You PR is approved but there are some conflicts that must be resolved. Can you take care of that so we can proceed with merge? Thanks 🙂

**Review by gantunesr — COMMENTED** [review]
Looks like there's a lint issue because of an unused variable

**Comment by caiquecruz** [comment]
> Looks like there's a lint issue because of an unused variable

Just removed, thank you!

**Comment by gantunesr** [comment]
@caiquecruz now you need to update the snapshot for that component,

```
yarn test:unit:update
```

**Review by Akaryatrh — APPROVED** [review]

**Review by gantunesr — APPROVED** [review]

**Comment by dawnseeker8** [comment]
hi, @xardass the PR has been approved by two code reviewer and has `qa passed` tag. so you can `Squash and merge` the PR now.

**Comment by gantunesr** [comment]
This PR can be merged with a SonarCloud Code Analysis check bypass

**Pull request merged**
