### PR TITLE
Bugfix/android anr

### LINKED ISSUE #2498: Sentry: ApplicationNotResponding: Application Not Responding for at least 4000 ms.
Sentry Issue: [METAMASK-MOBILE-BKK](https://sentry.io/organizations/metamask/issues/2044150063/?referrer=github_integration)

```
ApplicationNotResponding: Application Not Responding for at least 4000 ms.
    at android.view.ThreadedRenderer.nDestroy(ThreadedRenderer.java)
    at android.view.ThreadedRenderer.destroy(ThreadedRenderer.java:411)
    at android.view.ViewRootImpl.destroyHardwareRenderer(ViewRootImpl.java:6529)
    at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3554)
    at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6459)
...
(14 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by sethkfman**
**Description**

Increase sentry module version which uses an increased ANR timeout (5 sec and mirrors Google's rules for ANR). This issue is no longer thrown on splash screen.

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2498

### CODE REVIEW

**Comment by andrepimenta** [comment]
Since this bumps the major version of sentry, is the api still the same, it still works?

**Comment by sethkfman** [comment]
@andrepimenta  Good question. The major increment doesn't include any breaking changes just some major feature upgrades. Taken from Sentry's Change Log:

`This major version release doesn't contain any breaking API/code changes. Starting from the version 6.0.0, all SDKs that support sending sessions data will do so by default. See our Release Health docs to learn more. As of this version, it applies to all Browser SDKs (Browser, React, Angular, Vue, Gatsby etc.). Node.js and other related Server SDKs will follow soon after, in the minor 6.x release. You can opt-out of this behavior by setting autoSessionTracking: false option during SDK initialization.`

I tested it with general usage and didn't see any issues. I do think we should keep an eye on it during regression just incase.

**Comment by sethkfman** [comment]
I was thinking during the pre-release/regression testing we can watch Sentry to make sure we are getting events tied to the latest versions we released. If there is an issue we can revert the PR and manually set the ANR timeout to 5000.

**Review by ibrahimtaveras00 — APPROVED** [review]
No issues with loading animation nor logging in, 👍🏽

**Review by andrepimenta — APPROVED** [review]

**Pull request merged**
