### PR TITLE
Fix android injection

### LINKED ISSUE #1140: window.web3 and window.ethereum both of them returns undefined on sub pages...
Platform : Android
Metamask Version : 0.24(17)

typeof window.ethereum always returns "undefined"
typeof window.web3 always returns "undefined"

web3 and ethereum working correctly on a website home page... 
but sub pages in a website always returns undefined...

          let msg = "type of window.ethereum :"+typeof window.ethereum;
                    msg += "\r\ntype of window.web3:"+typeof window.web3;
                    msg += "\r\nMetaMask is not accessible!";

**In Sub Page**
photo5819179708665934306

**In Home Page**
photo5819179708665934307

### LINKED ISSUE #1391: How is the inpage.js injected before page load execution?
HI, I'm trying to understand how Metamask works, I see that in a webpage displayed in a WebView in app/components/Views/BrowserTab/index.js, the js code is first loaded from a local asset then injected via injectedJavaScript={entryScriptWeb3}, which sets the window.ethereum var, and some middleware that intercepts postMessage.

What I don't understand is that injectedJavascript is supposed to be run after page is loaded, so the page code should have already run at that point, a the call to window.ethereum would have returned undefined. The Chrome plugin uses content script, so the window.ethereum and the middleware are set in the DOM before the page is loaded, but here how is it achieved? Does the useWebkit option have an impact on this?

### LINKED ISSUE #1931: window.ethereum missing in Android app (CSP blocked?)
**Describe the bug**
On IDEX website (eg. https://exchange.idex.io/support/check) there is no `window.web3` or `window.ethereum` injected.

See "Unlocked Wallet" section and `Software Wallet Check - New Web3Ethereum: NO, Older Web3: NO` which is reading `window` values.

**To Reproduce**
1. Open https://exchange.idex.io/support/check or https://exchange.idex.io/unlock
2. See that metamask is not injected on the webpage

**Smartphone:**
 - OS: Android
 - App Version `v1.0.5 (39)`

**Sorry, but no more information**

I don't see any error in console (being recorded after app started), but there might be something hidden cause I was not able to use full inspector using remove WebView debugger (https://github.com/MetaMask/metamask-mobile/issues/1226).

I suspect that there might an issue with [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) which is blocking scripts which Metamask wants to inject. But cannot verify this issue without full console output.

### LINKED ISSUE #1956: window.ethereum is randomly null in a Flutter web app
**Describe the bug**

Checking for window.ethereum (after load) is often null on flutter web apps. It would seem flutter is affecting whatever Metamask mobile is doing to inject the ethereum object. It doesn't happen every time, but typically on initial load it will happen.

The Chrome extension doesn't have this problem btw.

**To Reproduce**

This happens on any flutter web app, I put up the generic flutter app here to show the behavior: 

https://trust-test-4f535.web.app/

See source to verify the `addEventListener`. 

**Expected behavior**

window.ethereum to not be null. 

**Smartphone (please complete the following information):**

 - Device: Pixel 4 XL
 - OS: Android 11
 - App Version: 1.0.5 (39)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### LINKED ISSUE #1975: Ethereum provider injection randomly fails on Android
**Describe the bug**
When I open my DApp, the web3 provider is not always injected. It doesn't make sence I use @metamask/detect-provider or plain window.ethereum call.

**To Reproduce**
_Steps to reproduce the behavior_
1. Start DApp 
2. Check if Web3 is injected via:

```
async function testEthereum() {

  const provider = await detectEthereumProvider()

  if (provider) {
    alert('YES');
  } else {
    alert('ERROR!');
      setTimeout(testEthereum, 3000); // 3 seconds
  }
}
```

I also tried adding an eventlistener, but this doesn't' work as well:

```
      window.addEventListener('ethereum#initialized', App.initWeb3, {
        once: true,
      });

```

In my HTML file I added:

`<script src="https://unpkg.com/@metamask/detect-provider/dist/detect-provider.min.js"></script>
`

3. Sometimes the web3 is not available. After refreshign the page, sometimes it works, sometimes it does not work.

**Expected behavior**
I expect the provider is always available.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 10
 - OS: Android 10
 - App Version 1.0.5 (39)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by andrepimenta**
**Description**

Fixes android injection by implementing shouldInterceptRequest on RN WebView. 
Implemented this fix from https://github.com/react-native-webview/react-native-webview/pull/1099#issuecomment-678892528: 
https://github.com/status-im/react-native-webview/commit/5578e63fc609b770408ddbdead5a4a211c45218b

**Issues**

Resolves #1931
Resolves #1975
Resolves #1956
Resolves #1391
Resolves https://github.com/MetaMask/metamask-mobile/issues/1140

### CODE REVIEW

**Comment by shendel** [comment]
@andrepimenta can I have a few questions?
who are these "Mobile Devs" reviews for a very long time
Could you post the compiled APK (with dev mode on if its possible) - so I can check it works?

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
A majority of the Dapps I checked seem fine.  However, I did notice that when navigating to uniswap via our home page tabs, it didn't prompt me to connect.  If I reload the page, it does prompt me to connect.  Also if I come from a bookmark or deeplink I am prompted.

seen here = https://recordit.co/vAMqEBu1tl

Also, as you can see towards the end of the recording and here = https://recordit.co/r6aNsdum1Y, when I am already connected, but I refresh the app (kill and launch again) or if I close the tab, and then open another tab and navigate back to uniswap, it shows as I'm not connected.  But if I reload I am indeed connected.  Similar to above, if I come from a deeplink or from favorites it works fine.

**Comment by andrepimenta** [comment]
> A majority of the Dapps I checked seem fine. However, I did notice that when navigating to uniswap via our home page tabs, it didn't prompt me to connect. If I reload the page, it does prompt me to connect. Also if I come from a bookmark or deeplink I am prompted.
> 
> seen here = https://recordit.co/vAMqEBu1tl
> 
> Also, as you can see towards the end of the recording and here = https://recordit.co/r6aNsdum1Y, when I am already connected, but I refresh the app (kill and launch again) or if I close the tab, and then open another tab and navigate back to uniswap, it shows as I'm not connected. But if I reload I am indeed connected. Similar to above, if I come from a deeplink or from favorites it works fine.

Hey @ibrahimtaveras00, it should be fixed now!

**Review by estebanmino — APPROVED** [review]
lgtm

**Review by ibrahimtaveras00 — APPROVED** [review]
👍🏽

**Comment by MrPeanutz** [comment]
Seems like this bug is still going on

**Comment by shendel** [comment]
@MrPeanutz MM v2.0.1 (49), Android 9.1.0.404 (Huawei Y6s) - For me work fine

**Comment by romansemko** [comment]
https://test.minted.vodka - I do see this bug at our project. Interestingly, only on some android devices. Android 11 seems to work just fine. Another Android 9 and Android 10 devices have the issue.

**Comment by SKlayer** [comment]
https://wagon.cash - It doesn't works on my Android 11 M2011J18C  and many devices..

**Comment by tomtomcrypto** [comment]
Same for me, no injection in both Android browsers and in Metamask in-app browser. Android 10, Huawei P30. Working fine on desktop and using metamask detect provider script.

**Pull request merged**
