### PR TITLE
fix: reset transaction fix

### PR DESCRIPTION
**Pull request by witmicko**
## **Description**
fixes https://github.com/MetaMask/mobile-planning/issues/1292

Addresses: https://github.com/MetaMask/mobile-planning/issues/1283

### CODE REVIEW

**Comment by sethkfman** [comment]
@blackdevelopa @jpuri Could you take a look at this ticket for feedback and confirm this bug fix is not breaking anything.

**Review by tommasini — APPROVED** [review]
LGTM!

**Review by blackdevelopa — APPROVED** [review]
This change looks good to me. QA is advised

**Comment by seaona** [comment]
After QAing on this branch I confirm the normal behaviour of the wallet is preserved. However I haven't tested if the original issue was fixed as I don't have permissions to see the ticket.

- :heavy_check_mark:  Send ETH and tokens from inside the wallet
- :heavy_check_mark:  Send EHT and tokens from a dapp
- :heavy_check_mark: Signatures
- :heavy_check_mark: Hardware wallet transactions and signatures
- :heavy_check_mark: Deeplinks

**Comment by seaona** [comment]
The original reported issue seems to be working on my end too
cc @tommasini

**Pull request merged**
