### PR TITLE
refactor: Update AvatarVariants to AvatarVariant

### PR DESCRIPTION
**Pull request by brianacnguyen**
## **Description**
Rename `AvatarVariants` to `AvatarVariant`

## **Screenshots**
Simulator Screen Shot - iPhone 14 Pro - 2023-11-09 at 13 36 36
Simulator Screen Shot - iPhone 14 Pro - 2023-11-09 at 13 36 38
Simulator Screen Shot - iPhone 14 Pro - 2023-11-09 at 13 36 46

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by tommasini** [comment]
Hey @brianacnguyen Can we have a recording of some components impacted?

**Comment by brianacnguyen** [comment]
> Hey @brianacnguyen Can we have a recording of some components impacted?

done

**Review by georgewrmarshall — APPROVED** [review]
LGMT!
- Checked out branch and did a search for `AvatarVariants` with no results
Screenshot 2023-11-10 at 8 30 30 AM

**Review by tommasini — APPROVED** [review]
LGTM!

**Pull request merged**
