### PR TITLE
fix: migrate from patched @exodus/react-native-payments to @metamask/react-native-payments

### PR DESCRIPTION
**Pull request by legobeat**
## **Description**

Instead of pulling in `@exodus/react-native-payments` from a git-commit and then patching it (!(?)), this migrates to a published version of the package under the name `@metamask/react-native-payments` with the same effect.

## **Related issues**

- #9387 
- #5324 
- https://github.com/MetaMask/react-native-payments/pull/5
- https://github.com/MetaMask/react-native-payments/pull/6
  - this makes the remaining related yarn resolution redundant. Can be integrated into metamask-mobile at a later point.
 
## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/@metamask/react-native-payments@2.0.0

new author ok

**Review by rickycodes — DISMISSED** [review]

**Comment by Gudahtt** [comment]
I noticed that there were still references to the old package in `Podfile.lock`. The lock file had changes after a local install on macOS as well. I have pushed those changes in 2083232bc8e8b8e1bfb97fbea6828285b625019f

**Review by Cal-L — APPROVED** [review]
LGTM from platform perspective. @wachunei Could someone from your team take a look at this PR since I believe payments is used by on-ramping

**Comment by wachunei** [comment]
If the changes from 1.5 -> 2 were the patches only then we are good to go, LGTM

**Review by wachunei — APPROVED** [review]

**Pull request merged**
