### PR TITLE
fix: error is not being handled correctly when user fails biometrics

### PR DESCRIPTION
**Pull request by jayala**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off 

**Description**
This PR fixes the wrong message when users cancel biometric auth on the 'Import from seed' flow.

**Screenshots/Recordings**

Before:
https://user-images.githubusercontent.com/116747263/227347582-cd20f633-a894-4544-aac9-b3f22d4770e3.mp4

After:
https://recordit.co/9y81CfzPgO

**Issue**
https://github.com/MetaMask/metamask-mobile/issues/6028

Progresses #???

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

### CODE REVIEW

**Comment by jayala** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by leotm** [comment]
thanks for signing the CLA ^ i've just hit re-run (CLA Bot now passing)

**Comment by leotm** [comment]
could you update the PR title to match our new [format](https://github.com/MetaMask/metamask-mobile/actions/runs/5370403166/jobs/9760931317?pr=6702)?

**Comment by jayala** [comment]
@leotm do you know how to fix the tests? It is [failing](https://github.com/MetaMask/metamask-mobile/actions/runs/5370402615/jobs/9761040676?pr=6702) for a SONAR_TOKEN variable not set.

**Comment by leotm** [comment]
> @leotm do you know how to fix the tests? It is [failing](https://github.com/MetaMask/metamask-mobile/actions/runs/5370402615/jobs/9761040676?pr=6702) for a SONAR_TOKEN variable not set.

it's a fault our end nothing to worry about ^ we'll soon update to only run if the token is available

i've hit _Approve and run_ on the checks

**Pull request closed without merging**
