### PR TITLE
feat: PPOM Version update to download files only before transaction

### LINKED ISSUE #8994: PPOM - Update ppom dependency to 1.4.5
### What is this about?

Update ppom to 1.4.5

### Scenario

_No response_

### Design

_No response_

### Technical Details

_No response_

### Threat Modeling Framework

_No response_

### Acceptance Criteria

_No response_

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

_No response_

### PR DESCRIPTION
**Pull request by jpuri**
## **Description**

Blockaid - download files from CDN only when transaction is received and we do not have updated files in storage.

## **Related issues**

Fixes: MetaMask/MetaMask-planning#2110
Fixes: #8994

## **Manual testing steps**

1. To to test dapp
2. Submit transaction and check file downloads
3. Check by switching between various networks, submitting multiple transactions.

## **Screenshots/Recordings**
NA

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've clearly explained what problem this PR is solving and how it is solved.
- [X] I've linked related issues
- [X] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [X] I’ve properly set the pull request status:
  - [X] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by segun — DISMISSED** [review]

**Review by blackdevelopa — DISMISSED** [review]

**Comment by segun** [comment]
This PR also fixes https://app.zenhub.com/workspaces/-confirmations-secure-ux-6245e6e2348677001213b8d2/issues/gh/metamask/metamask-mobile/8797

**Comment by seaona** [comment]
hi there, I'm seeing a weird behaviour when I disable and enable the feature in settings.
Do you think this might be related to this PR? It seems to work fine on main.
I cannot fully test the feature due to this issue, which prevents me to enable it back :thinking: 


https://github.com/MetaMask/metamask-mobile/assets/54408225/2821fdb6-cf1d-4ec3-813e-eaf424352c2d

**Comment by seaona** [comment]
hey @jpuri I confirm I continue to see the behaviour I mentioned above in this branch

**Comment by seaona** [comment]
after QAing the PR it looks like the behaviour is as expected:
- :green_circle: The first tx/signature will get all the cdn requests
- :green_circle:  After we've performed a 1st tx, the cdn request for versions will be done on every or signature

https://github.com/MetaMask/metamask-mobile/assets/54408225/83a37bea-62dd-4709-a701-0bbd9e4c25b2

- When I close the wallet, if I reopen it again and trigger a tx/signature, all the cdn requests are perfromed on the first tx/signature. I guess that's also expected?

https://github.com/MetaMask/metamask-mobile/assets/54408225/8e5f4fdc-a9c9-45dc-b74f-7d714712bafa

https://github.com/MetaMask/metamask-mobile/assets/54408225/6e158a87-a51e-4024-b46c-fc150917a5e9

- :question:  Did we remove the Android friction for the toggle? Was this intentional?

https://github.com/MetaMask/metamask-mobile/assets/54408225/b5a66af4-4efe-4f74-97e8-d4a4323fe212


Aside from the question, if needs to be clarified, the rest looks good @jpuri

**Comment by jpuri** [comment]
@SocketSecurity ignore npm/flat-cache@3.1.0

**Review by blackdevelopa — DISMISSED** [review]

**Comment by jpuri** [comment]
Hey @seaona : thanks a lot for detailed QA. So much useful. Please check my replies:

> When I close the wallet, if I reopen it again and trigger a tx/signature, all the cdn requests are perfromed on the first tx/signature. I guess that's also expected?
This is not expected in fact I could not replicate.

> ❓ Did we remove the Android friction for the toggle? Was this intentional?
Yes this is expected and now we do not initialise PPOM instance when we enable the preference, but we do that only when first transaction is received after enabling the preference.

**Comment by bschorchit** [comment]
Could we update ppom version to v1.4.5 as a separate PR so we possibly cherry pick it to an earlier release?

**Comment by jpuri** [comment]
> Could we update ppom version to v1.4.5 as a separate PR so we possibly cherry pick it to an earlier release, @jpuri ?

Sure @bschorchit , let me do that.

**Comment by jpuri** [comment]
PR to update ppom npm package in mobile repo: https://github.com/MetaMask/metamask-mobile/pull/9053

**Comment by seaona** [comment]
> When I close the wallet, if I reopen it again and trigger a tx/signature, all the cdn requests are perfromed on the first tx/signature. I guess that's also expected?

I've tried again and cannot repro. I think what I'm seeing now it's expected: when I close the app and re-open it again, I only see 1 request which fetches the version `
https://static.cx.metamask.io/api/v1/confirmations/ppom/ppom_version.json?_=1711441255281`

I think that's correct :+1: 

https://github.com/MetaMask/metamask-mobile/assets/54408225/93b05aa3-1207-4414-a10a-b6655198fe12

**Review by blackdevelopa — APPROVED** [review]

**Review by segun — APPROVED** [review]

**Pull request merged**
