### PR TITLE
Style updates

### PR DESCRIPTION
**Pull request by rickycodes**
**Description**

Some design inconsistencies Christian brought up being addressed in this PR

This PR actually makes a lot of style updates so I will go through them:

1. The `baseStyles.black` has been updated to not be absolute black.

2. Type face updated in asset list for adding Tokens:

| Before:  | After: |
| ------------- | ------------- |
| image | image

3. Type face updated in `BaseNotification` component:

| Before:  | After: |
| ------------- | ------------- |
| image | image

3. Create password

| Before:  | After: |
| ------------- | ------------- |
| image | image

4. Import from Seed

| Before:  | After: |
| ------------- | ------------- |
| image | image

5. Login

| Before:  | After: |
| ------------- | ------------- |
| image | image

### CODE REVIEW

**Comment by cjeria** [comment]
@rickycodes looks good! Just a bit of feedback on the **import seed phrase** screen regarding spacing and the font size of the form validation text. See below

image

**Comment by rickycodes** [comment]
@cjeria I've gone ahead and made the font size adjustments, re: spacing we might want to leave that as is for now? The feedback text isn't always present so increasing that spacing might look a bit odd in the empty cases

here's what things look like now:

| Without feedback:  | With: |
| ------------- | ------------- |
| image | image

Let me know what you think.

**Comment by cjeria** [comment]
LGTM!

**Review by estebanmino — APPROVED** [review]
lgtm

**Pull request merged**
