### PR TITLE
feat(off-ramp): add off-ramp feature

### PR DESCRIPTION
**Pull request by wachunei**
> **Warning**
> This branch (`feat/off-ramp`) must not contain any direct commits to it and will only server as the collection of other PRs that contribute to the development of the off-ramp feature, while keeping the changes in sync with `main` branch.

> **Note**
> This PR is a work in progress

## **Description**

This PR contains the off-ramp feature and is a collection of the work of multiple other PRs. PRs that have been reviewed and approved by MetaMask members are marked as "✅ Approved".

**Merged and Open PRs**
1. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7014 - Approved
2. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7016 - Approved
3. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7169 - Approved
4. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7227 - Approved
5. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7378 - Approved
6. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7325 - Approved
7. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7401 - Approved
8. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7477 - Approved
9. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7495 - Approved
10. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7498 - Approved
11. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7522 - Approved
12. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7539 - Approved
13. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7556 - Approved
14. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7625 - Approved
15. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7715 - Approved
16. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7576 - Approved
17. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7577 - Approved
18. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7637
19. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7748 - Approved
20. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7800 - Approved
21. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7742
22. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7830
23. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7850
24. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7852
25. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7854
26. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7858
27. ✅ - https://github.com/MetaMask/metamask-mobile/pull/7872

**Draft PRs**

**Design Document**
https://www.figma.com/file/PsKqriAOpJDQpaHt373D45/Off-Ramp?type=design&node-id=3227-193475&mode=design&t=RY1XXYsSUIkqG1Di-0

## **Related issues**

Refer to each PR

## **Manual testing steps**

Refer to each PR

## **Screenshots/Recordings**

Refer to each PR

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sethkfman** [comment]
@wachunei Add figma documentation for expected behavior

**Comment by wachunei** [comment]
Here's our figma https://www.figma.com/file/PsKqriAOpJDQpaHt373D45/Off-Ramp?type=design&node-id=3227-193475&mode=design&t=RY1XXYsSUIkqG1Di-0

**Review by sethkfman — DISMISSED** [review]
LGTM

**Comment by wachunei** [comment]
@sethkfman  We have added a new PR with a fix during QA https://github.com/MetaMask/metamask-mobile/pull/7872

**Review by sethkfman — APPROVED** [review]
LGTM

**Comment by bkirb** [comment]
@wachunei @georgeweiler LGTM I finished verifying iOS and Android with the latest changes ✅

**Pull request merged**
