### PR TITLE
[5.3][Fix] Use gas fee from market instead when not specified in QR code

### LINKED ISSUE #3704: MetaMask suggests gas fees too high when using Coinbase QR
**Describe the bug**
When generating a QR code with [Coinbase Commerce](https://commerce.coinbase.com/) and using it with MetaMask Mobile, MetaMask Mobile suggests the gas fees that are x10+ higher than what they should be.

**Screenshots**

When pulling from a Coinbase Commerce generated QR code:
QR

When typing in the same generated address to send to and the same amount manually:
non-QR

**To Reproduce**
1. Have QR code generated with [Coinbase Commerce](https://commerce.coinbase.com/).
2. Open MetaMask Mobile.
3. Tap the QR code reader icon.
4. See the suggested gas fees too high.

**Expected behavior**
Reasonable suggested gas fees based on the current network suggestion.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 15.2.1
 - App Version: MetaMask v4.0.1 (814)

**Additional information**

If you use a QR code reader to read what's in the code from the example, you get:

```
ethereum:0x4dc53535ec0d5844b935ccc0259e46c02e4961f5?value=3184000000000000
```
-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by Fatxx**
**Description**

Gas fees should now be fetched from the market (EIP1559) instead of using network prices when not specified in QR code.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #3704

### CODE REVIEW

**Review by jpcloureiro — COMMENTED** [review]
Q: The gas estimation for deeplinks will use which transaction to do the calcs?

**Comment by Fatxx** [comment]
Not sure I understand the question @jpcloureiro. But the gas is fetched on the confirm screen if not provided in the transaction.

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
Please address check failures and branch conflicts.

**Comment by Fatxx** [comment]
For this QR code to work we need to merge the blocked PR #3929

**Comment by chrisleewilcox** [comment]
App with fix showing fees.....
https://recordit.co/aQZcI0l3Y1

Coinbase Wallet app scanned same QR showing fees....
https://recordit.co/DIGLo7TptE

**Review by chrisleewilcox — APPROVED** [review]
Tested, pass.  See recordings.

LGTM!

**Pull request merged**
