### PR TITLE
feat: Update assets controllers v14

### PR DESCRIPTION
**Pull request by tommasini**
## **Description**
This PR addresses the update to the Asset Controller v14

Created Core branch to address patch changes: patch/mobile-assets-controllers-v-14-0-0

Fixed issue of token being automatically imported when requested by a dapp.

Changed breaking changes on addToken and watchAsset function signature.

Important to note that this version of assets controller is pointing to version 5 of controller utils, therefore the auto detect tokens will only be available when this [PR](https://github.com/MetaMask/metamask-mobile/pull/9149) is merged 

## **Related issues**

Fixes: https://github.com/MetaMask/mobile-planning/issues/1620

## **Manual testing steps**

1. imported tokens on mainnet
2. Imported tokens on custom network
3. Auto-detect tokens on mainnet & custom network
4. Import token via dapp
5.

## **Screenshots/Recordings**

Auto detect tokens, import token via dapp:

https://github.com/MetaMask/metamask-mobile/assets/46944231/daed21fe-1bbe-432e-9c1d-71e7ccc3baa9

Add custom token/ hide token:

https://github.com/MetaMask/metamask-mobile/assets/46944231/a1911455-136f-436b-924f-01f8d5bcd5a9

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by wachunei — DISMISSED** [review]
Changes in `app/components/UI/Ramp/hooks/useHandleSuccessfulOrder.ts` LGTM

**Review by bergeron — APPROVED** [review]
Looks good to me!  Tested detecting and importing tokens.  switching accounts / chains.  And my recent patch for linea pricing.

As the PR description mentions, NFT detection requires https://github.com/MetaMask/metamask-mobile/pull/9149

**Review by blackdevelopa — APPROVED** [review]
code lgtm

**Review by NicolasMassart — APPROVED** [review]
Looks good to me.

**Pull request merged**
