### PR TITLE
feat: ipfs banner 

### PR DESCRIPTION
**Pull request by tommasini**
**Description**
More info [here](https://github.com/MetaMask/mobile-planning/issues/1216)

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

fixes #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by MarioAslau — DISMISSED** [review]
Looking good!

**Review by MarioAslau — DISMISSED** [review]
LGTM

**Review by MarioAslau — DISMISSED** [review]
LGTM

**Review by MarioAslau — DISMISSED** [review]
Looks good to me!

**Review by MarioAslau — DISMISSED** [review]
LGTM

**Review by cortisiko — APPROVED** [review]
PR looks good ✅

**Pull request merged**
