### PR TITLE
Fix issue #2830

### LINKED ISSUE #2830: Immediately resolves name as soon as I enter ".eth", but this excludes the ability to enter many names
**Describe the bug**
When entering an ENS name into a Recipient field, as soon as I enter a possible ENS suffix, e.g. ".eth" or ".xyz", the app immediately resolves the name and doesn't let me keep typing. This is a problem because subdomains exist in ENS. E.g. the name evan.ethereum.eth exists, but when I try to type it in as soon as I get to "evan.eth..." it resolves the name and doesn't let me keep typing. This would also be a problem if I tried to send to "brantly.xyz.eth", the app cuts me off as soon as i typed in "brantly.xyz", even though "brantly.xyz.eth" and "brantly.xyz" are two different names with different owners and records.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to MetaMask Mobile on Android
2. Tap "Send"
3. Try to type in to the Recipient field the ENS name "evan.ethereum.eth"
4. You'll see that it cuts you off as soon as you type in "evan.eth..."

**Expected behavior**
You should be able to type in any name, and the app should never stop you from typing in more. As you type in, could present possible names below for you to select, but it shouldn't stop you from typing more.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21+
 - OS: latest Android
 - App Version: v2.4.0 (746)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
Could lead to lost funds

- Add stats if available on % of customers impacted
potentially everyone

- Is this visible to all users?
yes

- Is this tech debt?
no, you just have a wrong implementation of ENS

### PR DESCRIPTION
**Pull request by tommasini**
**Description**
The input text is not longer transformed in a formatted text with was impossible to keep writing.
Now it is a text input with a check icon that tell us that the address it is valid.

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

Resolves #2830 
Resolves the fact that we could not write many names like "evan.ethereum.ether" and now we can access that addresses too with this solution.

### CODE REVIEW

**Comment by tommasini** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Fatxx — COMMENTED** [review]
Why did this `android/app/src/main/assets/fonts/metamask.ttf` file changed?

**Comment by tommasini** [comment]
I was incapable of unstage or delete that change since the fork of the
project. That just persisted in the commit changes.


A ter, 1 de fev de 2022, 12:09, André Fatia ***@***.***>
escreveu:

**Comment by tommasini** [comment]
I have a proposal for the design of the Address Input in sendFlow first step, (Send To). With the last one we couldn't keep writing and my proposal it's that the address of the wallet only appear in the third step of confirmation, that way the UX will not be compromised.
Simulator Screen Shot - iPhone 11 Pro - 2022-02-08 at 12 20 19
Simulator Screen Shot - iPhone 11 Pro - 2022-02-08 at 12 20 31
Simulator Screen Shot - iPhone 11 Pro - 2022-02-08 at 12 20 35

**Comment by gantunesr** [comment]
@omnat @yanrong-chen @jakehaugen wdyt?

**Comment by chrisleewilcox** [comment]
Not able to checkout this branch, getting a reference exception.  This branch does not look like it's aligned with other dev branches for checkout.  Can we please update the branch reference so I can checkout and test this change?

**Comment by chrisleewilcox** [comment]
- Recent or contacts name and address is not displayed in the To: field after tap/selecting them. This behavior does not match production.
https://recordit.co/0D4vlUPD9u

- Tapping <return> on the keypad simulates tap on Next button behind keypad and goes to next screen. Not sure if this behavior is desirable.

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
Recent or contacts name and address is not displayed in the To: field after tap/selecting them. This behavior does not match production.

**Comment by tommasini** [comment]
Thanks, @chrisleewilcox! I will look into it!

**Comment by tommasini** [comment]
New PR for this issue created here:
https://github.com/MetaMask/metamask-mobile/pull/3967

**Pull request closed without merging**
