### PR TITLE
feat: add portfolio button to asset action buttons

### PR DESCRIPTION
**Pull request by meppsilon**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

This PR adds a button to the wallet view that, when clicked, opens the browser to the portfolio dapp. We hope that this feature improves mobile users experience by providing them with quick access to additional portfolio-specific views.

**Screenshots/Recordings**

Screenshot 2023-03-09 at 4 36 23 PM

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by Cal-L — COMMENTED** [review]
Left some comments

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Review by Cal-L — APPROVED** [review]
translations LGTM

**Review by cortisiko — COMMENTED** [review]
@meppsilon questions for you:
1.
Should a new browser tab always open when I tap on the portfolio button? Right now if I were to connect to the pdapp via the portfolio button > return to the wallet > tap on the portfolio button again, a new browser tab opens up. If I repeat this `n` times then I will have `n` browser tabs opened for the portfolio dapp. 

See [recording](http://recordit.co/j0rhYrWioS)

2
Maybe this is something the design team can answer: 

With languages such as Russian or Filipino, there are ellipsis that prevents the users from seeing the full text on the buttons

[See prod behavior](https://www.screencast.com/t/kEJmh6jiyMpU) vs [Your branch ](https://www.screencast.com/t/QG7rF5gzD2)

**Comment by meppsilon** [comment]
Hey @cortisiko,

1. I think that's the expected behavior for now. In a future release, we might try to redirect the user to an existing browser tab but for now, this simple behavior is expected.
2. Yea, that is a better question for design but I'm not sure if there is a way around this unless we wrap the buttons around to another level.

**Review by cortisiko — APPROVED** [review]
this PR looks good @meppsilon 🌮 🌮 🌮

**Pull request merged**
