### PR TITLE
chore: split the SDKConnect class into smaller chunks and add unit tests

### PR DESCRIPTION
**Pull request by omridan159**
## **Description**

Split the SDKConnect class into smaller chunks to make the code more testable and add unit tests.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by andreahaku — DISMISSED** [review]
LGTM

**Review by andreahaku — APPROVED** [review]
LGTM

**Comment by christopherferreira9** [comment]
Tiny tiny detail that may have come from a different branch. The `console.warn` in the video can be ignored.

https://github.com/MetaMask/metamask-mobile/assets/104831203/6c0c938f-34c4-478f-94c9-41d89274a110

**Steps:**
1. Connect via QR Code and select "Do not remember me"
2. Refresh dapp
3. A loader is presented even though it can't resume since it did not save the room.

**Expected result:** 
The loader is not presented

**Actual result:** 
You get a loader

**Comment by christopherferreira9** [comment]
Since the bug reported doesn't break the overall functionality and is of low severity this is going to merged and https://github.com/MetaMask/metamask-mobile/issues/8079 was opened.

**Pull request merged**
