### PR TITLE
Custom Gas + Data hotfixes

### PR DESCRIPTION
**Pull request by EtDu**
**Description**

A couple of bug fixes

**Checklist**

**Issue**

Fixes https://trello.com/c/ESDSkNmz/171-data-not-showed-on-approve-modal
Fixes https://trello.com/c/6cI8Cm7K/177-deeplinking-bugs
Fixes https://trello.com/c/0rESeMgP/173-changing-to-gas-selectors-from-gas-input-and-back-to-gas-input-with-a-gas-price-error-crashes-the-app

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
LGTM

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
I see the data, however, it's not scrollable to show me all of the data as compared to extension; seen here = https://recordit.co/7WyO7lKu4u

Screen Shot 2020-07-09 at 9 38 42 PM

**Comment by EtDu** [comment]
@ibrahimtaveras00 should be good

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
I have my currency set to fiat, and upon clicking on deploy contract on https://metamask.github.io/test-dapp/ site to test if data is scrollable the app crashed; seen here = http://recordit.co/UwSOKhH9nb

Screen Shot 2020-07-14 at 9 16 56 PM

although it does look like the deeplink issue was fixed when fiat is set = http://recordit.co/AXjBl8Vud7

Also, when primary currency is set to native, I see this warning when tapping on deploy contract

Screen Shot 2020-07-14 at 9 20 43 PM

**Review by ibrahimtaveras00 — APPROVED** [review]
All issues have been resolved, QA Passed

**Pull request merged**
