### PR TITLE
bugfix: issue #2763

### LINKED ISSUE #2763: Play Store: Error: while converting number to string, invalid number value
```
com.facebook.react.common.JavascriptException: Error: while converting number to string, invalid number value '${}', should be a number matching (^-?[0-9.]+)., stack:
u@1489:1008
toWei@1489:1813
toWei@1702:2372
handleETHPrimaryCurrency@3495:8253
updateAmount@3495:9240
onChange@342:2638
```

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

_Write a short description of the changes included in this pull request._

I was able to repro going to payment request and putting an address as amount.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #2763

### CODE REVIEW

**Review by rickycodes — COMMENTED** [review]
rather than introducing another util method can we use something from one of the 3rd party deps? i only took a brief look, but I see `ethers` has https://docs.ethers.io/v5/api/utils/bytes/#utils-isHexString

maybe that could work?

**Comment by estebanmino** [comment]
good call @rickycodes 👌

**Review by rickycodes — APPROVED** [review]

**Comment by cortisiko** [comment]
Testing Device: samsung galaxy S8 (physical device) 

**Issue 1**

With fiat as my primary currency, I can request a non-decimal amount. Meaning I can input a non numerical value as my request amount and I am taken to the “Send Link” view. 


To reproduce:
Go to settings > general. 
Change your primary currency to Fiat. 
Return to the wallet view
While on the wallet view, long tap on your wallet address to copy it. 
tap on the receive button
tap on the request payment button 
Tap on ETH as your asset
Paste your wallet address in the amount field. 
Tap on done. Notice you are now on the Send link view

See behavior [here](http://recordit.co/TOaO5SzPL3)

**Comment by cortisiko** [comment]
**Issue 2** 
Going through the request flow, If I were to request a specific amount then tap on the “next” button  the keyboard does not collapse. 

To reproduce:
on the wallet view, tap on the receive button
tap on the request payment button 
Tap on ETH as your asset
Enter 4 in the amount field. 
From the keyboard, Tap “done” 

See behavior [here](http://recordit.co/Cq7w62xi2g) vs the [play store build](http://recordit.co/SImIJ0cgUh)

**Review by cortisiko — CHANGES_REQUESTED** [review]
I found a couple issues. Sending this puppy back to dev

**Review by cortisiko — APPROVED** [review]
fix looks good 🚀

**Pull request merged**
