### PR TITLE
Removes case sensitivity from ENS detector

### LINKED ISSUE #2414: Recognize uppercase .ETH wallet addresses
**Describe the usability problem**
If someone uses an uppercase .ETH address in the Add Contact screen, it's not recognized.

**Screenshots**
Screenshot_20210320-192342__01

Screenshot_20210320-192415__01

**Expected behavior**
I think it should be case insensitive, so it Just Works TM if someone gives me their address in all caps and I paste it. As it was, I had to guess why it was not working and try changing the extension.

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

### PR DESCRIPTION
**Pull request by Pixeladed**
**Description**

Detect ENS top level domain insensitively. `isENS` will now return true for both `metamask.eth` and `metamask.ETH`

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2414

### CODE REVIEW

**Comment by ShevaSHIO** [comment]
5c83b8f

**Comment by ShevaSHIO** [comment]
12482e2

**Comment by ShevaSHIO** [comment]
4d2e8ff

**Comment by rickycodes** [comment]
Hi Pixeladed! thanks for the contribution! this looks good to me!

**Review by rickycodes — APPROVED** [review]

**Pull request merged**
