### PR TITLE
Bugfix: new send flow amount balance

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

Adding balance section missing in new send flow pr

image

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

### CODE REVIEW

**Comment by ibrahimtaveras00** [comment]
**Issue 1:**

In the case of attempting to send a collectible, when I get to the Send > Amount view the "Next" CTA is disabled and I cannot proceed.  Shows the below warning

Screen Shot 2020-01-23 at 6 23 17 PM


Question: 

Not really an issue, but I am curious.  If I go to settings > general and change to fiat currency instead of native, should the balance on the send > amount view also show up as fiat?

**Comment by estebanmino** [comment]
@ibrahimtaveras00 you have a video of this? i can't repro

**Review by ibrahimtaveras00 — APPROVED** [review]
Fix looks good on both OS's, QA passed 👍

**Review by brunobar79 — APPROVED** [review]
LGTM!

**Pull request merged**
