### PR TITLE
ci: Github action to check issue body matches issues templates and add labels to issue when needed

### PR DESCRIPTION
**Pull request by gauthierpetetin**
## **Description**

This PR introduces a new Github action, to achieve the following:
1. Check if issue matches an existing issue template ('general-issue.yml' or 'bug-report.yml')
2. Add an `INVALID-ISSUE-TEMPLATE` label in case issue doesn't match any of the templates
3. Add an `external-contributor` label in case issue was created by someone external to the MetaMask organisation
4. Add a `regression-prod-x.y.z` label when possible, when `x.y.z` value can be extracted from 'bug-report.yml' template

We will be able to leverage `regression-prod-x.y.z` and `external-contributor` labels to improve our bug triage process and our metrics collection.

[Same PR for Extension repo](https://github.com/MetaMask/metamask-extension/pull/21184)

## **Manual testing steps**

1. Go on this [test repo](https://github.com/gauthierpetetin-test/repo_test/issues/new?assignees=&labels=type-bug&projects=&template=bug-report-extension.yml&title=%5BBug%5D%3A+)
2. Fill the bug report issue form
6. Make sure the release version you indicate in the form has x.y.z format
7. Click on "Submit new issue"
8. Wait for ~30s and 2 new labels shall appear on the issue you just created (`regression-prod-x.y.z` and `external-contributor`)
9. Edit the issue's description by indicating a different release version
10. Wait for ~30s and the `regression-prod-x.y.z` shall be updated accordingly
11. Edit the issue by deleting the whole description
12. Wait for ~30s and the `INVALID-ISSUE-TEMPLATE` shall be added
 
### **Before**

NA

### **After**

https://recordit.co/Sq7fvCwkr5

## **Related issues**

Fixes https://github.com/MetaMask/mobile-planning/issues/1293

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [ ] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by wachunei** [comment]
Would it be possible for the issue template to indicate the required sections as HTML comments? I usually delete the screenshots sections when the code is not related to the UI, eg:
```md
<!-- Required, don't delete -->
### Screenshots

````

**Comment by Cal-L** [comment]
> Would it be possible for the issue template to indicate the required sections as HTML comments? I usually delete the screenshots sections when the code is not related to the UI, eg:
> 
> ```
> 
> ### Screenshots
> ```

@gauthierpetetin on Pedro's note - Would it make sense to check post editing if required fields are still populated and apply  the invalid label accordingly? For example, I can edit the issue and provide an empty string in the description section and it would still be considered valid. Or do you think that would be too much friction?

**Comment by gauthierpetetin** [comment]
> Would it be possible for the issue template to indicate the required sections as HTML comments?

@wachunei the majority of sections are optional in the new templates we introduced in September, and get automatically filled with `_No response_` string in case you don't provide any info. Besides leaving the section as optional, the intention was to prevent behaviours where engineers would systematically delete all optional sections from issue's description, without considering them one by one and asking themselves whether or not they have some info to provide for each section. In your situation, would it be ok to leave the screenshots section empty, rather than deleting it?

> Would it make sense to check post editing if required fields are still populated and apply the invalid label accordingly?

@Cal-L the Github action is triggered every time, issue gets created or updated (cf. [here](https://github.com/MetaMask/metamask-mobile/pull/7379/files#diff-a3b8233fed654cd208a8571855d6bfd55bfe8c71eb03f3b50c11dc520e335e7bR6-R7)) and labels are updated accordingly. Does that correspond to what you suggest?

**Comment by Cal-L** [comment]
What I meant was if you delete the body of the description post issue creation, it doesn't see it as invalid.

**Comment by gauthierpetetin** [comment]
@Cal-L the behaviour you describe seems included in this PR (cf. second 25' in the [recording](https://recordit.co/Sq7fvCwkr5)). Do you confirm?

**Comment by Cal-L** [comment]
> @Cal-L the behaviour you describe seems included in this PR (cf. second 25' in the [recording](https://recordit.co/Sq7fvCwkr5)). Do you confirm?

Since these changes are meant to verify the template and not necessarily the body content, will consider it out of scope.

**Review by Cal-L — DISMISSED** [review]
Lgtm

**Comment by gauthierpetetin** [comment]
I just pushed one last fix to address @NicholasEllul 's comment made [here](https://github.com/MetaMask/metamask-extension/pull/21184#discussion_r1355650632).

**Review by sethkfman — APPROVED** [review]
lgtm

**Pull request merged**
