### PR TITLE
Added type declaration for deprecated Checkbox library

### PR DESCRIPTION
**Pull request by pedrosimao**
**Description**

Added a type declaration that overwrites the original `@react-native-community/checkbox` type, so we can have a `deprecation` message visible on IDEs

_1. What is the reason for the change?

Make developers aware that `@react-native-community/checkbox` is deprecated.

**Screenshots/Recordings**

Screenshot 2023-07-25 at 16 06 28

**Issue**

https://github.com/MetaMask/metamask-mobile/issues/6885

**Checklist**

* [x] There is a related GitHub issue

### CODE REVIEW

**Comment by pedrosimao** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by georgewrmarshall — COMMENTED** [review]
Hey @pedrosimao, this is great! I pulled your branch and checked that the deprecation message is working as intended. I just want to check with @Cal-L that this would be a scalable way to deprecate third-party libraries in favour of the component-library components

**Comment by georgewrmarshall** [comment]
Also looks like there is a conventional commit convention that needs to be addressed

**Comment by pedrosimao** [comment]
Ohh, sorry, I just noticed I should have documented the update in the `changelog`, right?

**Comment by pedrosimao** [comment]
@georgewrmarshall Ok, commit name fixed... I guess the changelog is generated automatically based on the commit title? (which is not according to Conventional Commits)
If @Cal-L thinks this is a good way of documenting deprecation of external Libs I will go ahead and do the same for the other libs that are also being deprecated (on other github issues)

**Comment by pedrosimao** [comment]
@georgewrmarshall any news on this one?

**Comment by georgewrmarshall** [comment]
Hey @pedrosimao, thanks for following up. I'll make sure to chase this up with the mobile team next week. We've all just got back from a week break so sorry for the lack of correspondence on this. Thanks for your patience

**Comment by georgewrmarshall** [comment]
Hey @pedrosimao, we recently updated SonarCloud settings so external contributor PRs would pass but I think you may have to close this PR and create a new one. Would you mind doing that and we should be able to get this in

**Review by Cal-L — APPROVED** [review]
LGTM!

**Comment by pedrosimao** [comment]
@georgewrmarshall no problem. I just re-synced my original branch and it seems the SonarCloud actions along with the other jobs were passed again. Let me know if I still need to create a new PR (and close this one). Anyway I think it stills need a second review approval. Whenever we will be able to merge this PR I can add more deprecate the other libs and replace them (according to the open issues).

**Review by georgewrmarshall — APPROVED** [review]
LGTM! Thanks for your contribution @pedrosimao 🙏

**Pull request merged**
