### PR TITLE
Revert "feat: migrate to native primary currency (#8720)"

### PR DESCRIPTION
**Pull request by salimtb**
This reverts commit 4c45aa2b2b630bdca0122278ebbe47ca7f8f00c3.

## **Description**
revert PR remove primary currency toggle due to a product decision

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to General settings
2. you should find now the toggle Crypto/fiat

### **Before**

Screenshot 2024-03-22 at 14 29 26

### **After**

Screenshot 2024-03-22 at 15 39 03

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by NicolasMassart** [comment]
Q: why does the revert scope on migrations (and migration tests) involves more than what was changed in the initial PR?

**Comment by salimtb** [comment]
> Q: why does the revert scope on migrations (and migration tests) involves more than what was changed in the initial PR?

hey @NicolasMassart ,
the migration scope has been affected because some migration files have been merged after the migration contained on the revert (the one for this PR was 35, then 36 and 37 were merged )  which means that after the revert, 36 becomes 35 and 37 becomes 36.
the other option would be to make migration 35 obsolete ( return null ) and have less impact on the changes.
let me know what your thoughts about it

**Comment by NicolasMassart** [comment]
> let me know what your thoughts about it
@salimtb thanks for this explanation. So it's just renaming/moving, understood.
Less changes is nice, the 35 with null option is tempting. But then it means we will forever have an empty 35. So maybe shifting all migrations back by one is cleaner long term.
Let's keep it like this, I will re-review.

**Review by NicolasMassart — APPROVED** [review]
Looks good to me.

**Pull request merged**
