### PR TITLE
Improvement/protect funds everywhere

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

Added the sticky bar to start account backup process everywhere but these views because it blocked the buttons.

https://github.com/MetaMask/metamask-mobile/pull/1514/files#diff-3df4426e7ab346d10de9af4518c13e37R55

Video https://recordit.co/ZEattFiNav

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

### CODE REVIEW

**Review by andrepimenta — APPROVED** [review]
Looks good to me! 👍

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Overall looks good; just saw one issue:

On Android upon confirming a txn, the warning banner hides on top of the txn notification
seen here = https://recordit.co/GMJqjKeDTn

Screen Shot 2020-05-28 at 8 33 39 PM

Another thing I noticed, not really a bug since it behaves as the currently implemented flow; when skipping the backup process it automatically directs you back to the browser.

seen here = https://recordit.co/G892w6m6Qi

Do we want to follow this format or keep the user on whichever view they were previously on before tapping on the warning banner @omnat @estebanmino @cjeria?

FYI, doing the secure your wallet flow does correctly keep you on whichever view the user was last on.

**Comment by cjeria** [comment]
The backup recovery phrase notification behavior is changing soon (before v1 launch?) with a gradual nudging to back up, however, I presume this situation is still an edge-case that will occur. So to avoid alert notifs overlapping, we could use this special sticky alert banner under the top app bar which works in both app views. WDYT? @omnat 

image

> Do we want to follow this format or keep the user on whichever view they were previously on before tapping on the warning banner?

I agree let's take the user back to the screen they were previously coming from.

**Comment by omnat** [comment]
Yeah makes sense to send the user back to the screen they were on before tapping the backup prompt.

Overlapping - agree, would be good to show the backup prompt after user closes out the tx notification (or when tx notification clears out). Alternatively stack it on top of tx notif so both are visible and drop it down after tx notification clears. Your call @cjeria

**Review by ibrahimtaveras00 — APPROVED** [review]
Looks good on both OS's, QA Passed 👍

**Comment by cjeria** [comment]
I agree with Omna's first suggestion. Let's overlap the TX notif above the backup prompt for now.

**Pull request merged**
