### PR TITLE
patch: (webview upgrade) improve browser experience

### PR DESCRIPTION
**Pull request by jpcloureiro**
## **Description**

This change is part of the file react-native-webview+11.13.0.patch, a collection of patches that we need to apply on top of react-native-webview.

Webview changes can be reviewed here:
https://github.com/MetaMask/react-native-webview-mm/pull/8

Original Pull Request:
https://github.com/MetaMask/metamask-mobile/pull/5238

### **Before**

Notice there's no user prompt before downloading a file

https://github.com/MetaMask/metamask-mobile/assets/1649425/6579222b-bd40-418b-a687-bcfe54ef8164

### **After**

Notice there's an user prompt before downloading a file

https://github.com/MetaMask/metamask-mobile/assets/1649425/3dc7089a-ed3f-4e4f-863f-aac556340e14

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by MarioAslau — APPROVED** [review]
Looks good!

**Review by NicolasMassart — APPROVED** [review]

**Comment by chrisleewilcox** [comment]
@jpcloureiro I merged https://github.com/MetaMask/metamask-mobile/pull/8654/files and that may have caused conflicts with this branch now.  Can you take a look at the merge conflicts?

**Comment by chrisleewilcox** [comment]
@jpcloureiro running into an issue when playing videos in browser.  App becomes unresponsive and continuously generating log output after video is played in browser.
https://drive.google.com/file/d/1FvhsZ6ufEuzTSCFnTflPNHnqwflLImZs/view?usp=sharing

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
See issue https://github.com/MetaMask/metamask-mobile/pull/8585#issuecomment-2014128558

**Comment by jpcloureiro** [comment]
> @jpcloureiro running into an issue when playing videos in browser. App becomes unresponsive and continuously generating log output after video is played in browser. https://drive.google.com/file/d/1FvhsZ6ufEuzTSCFnTflPNHnqwflLImZs/view?usp=sharing
> 
> * with in-app browser navigate to https://testfile.org/
> * tap video
> * tap download 33MB video file
> * after video starts playing pause the video
> * app is unresponsive
> * not able to tap on anything in the app
> * log output is continuous
> 
> Expected:
> 
> * app continues to respond pausing or playing video with in-app browser
> * log output is not continuous

Oh this is no good. I'll look into it

**Comment by jpcloureiro** [comment]
We have the same problem in production v7.18.0 (1281).
@chrisleewilcox can you create a ticket for this issue?

**Comment by chrisleewilcox** [comment]
@jpcloureiro here is the bug created: https://github.com/MetaMask/metamask-mobile/issues/9052

**Comment by chrisleewilcox** [comment]
QA Passed.  See issue for tests recordings.

**Review by chrisleewilcox — APPROVED** [review]
LGTM

**Pull request closed without merging**
