### PR TITLE
Upgrade swaps-controller v4

### PR DESCRIPTION
**Pull request by wachunei**
**Description**
This PR upgrades to swaps-controller as module. **Depends on #2416**, do not merge before #2416

**TODO**

* [x] Replace tgz with v4.0.0 once published

---
PD: Tests are failing because of the breaking change from v7 -> v8 controllers architecture (current code is v7 style, while SwapsController is a v8 controller).

### CODE REVIEW

**Comment by mobularay** [comment]
@wachunei is this work in-scope of this sprint (new work?)?

**Comment by wachunei** [comment]
Yeah this is part of BSC Swaps release

**Review by estebanmino — APPROVED** [review]
working for me

**Review by ibrahimtaveras00 — APPROVED** [review]
QA Passed 👍🏽

**Pull request merged**
