### PR TITLE
Upgrade to Jest 27 for improved performance and RN upgrade compatibility

### PR DESCRIPTION
**Pull request by Fatxx**
**Description**

This pull request upgrades our testing framework from Jest 26 to Jest 27, taking advantage of improved performance, better error messages, and new features that will help streamline our testing process and ensure a higher quality codebase.

**Changes**

- Upgraded Jest from version 26 to version 27
- Updated all dependencies and configurations related to Jest

This PR will also accommodate future support for React Native and Detox upgrades. 

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Related with https://github.com/MetaMask/mobile-planning/issues/477

**Checklist**

* [ ] There is a related GitHub issue
* [x] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by Fatxx** [comment]
@SocketSecurity ignore-all

**Review by Cal-L — APPROVED** [review]
LGTM. Placing QA spot check since it doesn't affect runtime code or functionality. Will run iOS e2e on Bitrise to verify that those are passing.

**Comment by Fatxx** [comment]
LGTM ✅

**Review by cortisiko — APPROVED** [review]
This only affects the unit tests. Detox was updated and tests passed. ✅

**Pull request merged**
