### PR TITLE
Fix .xyz ENS Domain Resolution

### PR DESCRIPTION
**Pull request by Alec2435**
**Description**

Fix issue where .xyz domains registered as an ENS but missing a `contenthash` aren't resolved by traditional DNS (i.e. [101.xyz](https://101.xyz)). This is achieved by detecting an empty `contenthash` and catching the error in the part of the navigation code that was meant to bypass failed ENS resolutions.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

N/A

### CODE REVIEW

**Comment by Alec2435** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by gantunesr — COMMENTED** [review]
LGTM.

QA Review pending.

**Comment by gantunesr** [comment]
Hey @Alec2435, can update your branch to main for our QA

**Review by gantunesr — APPROVED** [review]
LGTM. Waiting on branch update to start QA

**Comment by plasmacorral** [comment]
> LGTM. Waiting on branch update to start QA

**Comment by tommasini** [comment]
Hello @Alec2435 thank you so much for this pull request!
I merged a [PR](https://github.com/MetaMask/metamask-mobile/pull/4173) that solves the problem of the URLs that end on .xyz and are top-level domains and not ENS, do you believe that your PR will add more value for the solution that we found?

**Comment by sethkfman** [comment]
@Alec2435 we are going to close this PR. If you feel that this is still an issue please reopen.

**Pull request closed without merging**
