### PR TITLE
Update password & seedphrase backup flow

### PR DESCRIPTION
**Pull request by andrepimenta**
This is a PR for the update of the password & backup flow that includes five PRs/tasks:

Create password (required step)
https://github.com/MetaMask/metamask-mobile/pull/1622
https://trello.com/c/EOp3hZu9/121-create-password-required-step

Prompt to backup seedphrase:
https://github.com/MetaMask/metamask-mobile/pull/1647
https://trello.com/c/ytGa96Ps/123-prompt-me-to-backup-my-seedphrase

Manual Seedphrase Backup Designs
https://github.com/MetaMask/metamask-mobile/pull/1641
https://trello.com/c/dxgEt2zb/124-save-my-seedphrase-manually-by-writing-it-down

Feature/update import extension tip:
https://github.com/MetaMask/metamask-mobile/pull/1668
https://trello.com/c/JqpSbZ7b/122-inform-me-that-my-password-is-same-as-extension

Feature/fingerprint in login
https://github.com/MetaMask/metamask-mobile/pull/1651
https://trello.com/c/JHZAyoof/132-allow-me-to-use-fingerprint-option-to-log-in

### CODE REVIEW

**Review by rickycodes — APPROVED** [review]

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
🐛

**Comment by cjeria** [comment]
The header and subheader copy in the carousel needs to be updated to the latest copy. Here's a direct link to the [designs](https://www.figma.com/file/Jw1v9k1BkHclNZDTZzXFVk/Mobile-Seed-Phrase-Backup?node-id=1256%3A564)
image

**Comment by ibrahimtaveras00** [comment]
**Issue 9:**

I'm noticing that for the fingerprint feature, we correctly show it when launching app (and if I cancel I'm still able to initiate it again), however, if I'm already logged in, and then I log out, tapping on the finger print does nothing; seen here = http://recordit.co/G58PvrDM6w 

Is this buggy, or is this how it was intended to work @cjeria / @andrepimenta ?

**Comment by ibrahimtaveras00** [comment]
**Issue 11:**

The title METAMASK is misaligned on this view

Screen Shot 2020-07-20 at 6 34 04 PM

**Comment by ibrahimtaveras00** [comment]
**Issue 12**

Seems like we missed the security feature of blocking screenshots on Android on import via seed phrase flow

this branch = https://recordit.co/S1jrlwY8SA
verses
current production = https://recordit.co/EfpHJ3ehig

**Comment by ibrahimtaveras00** [comment]
In addition to Issue 4 above which was for android, on iOS I'm noticing that by swiping left I get to the create password view which I'm assuming would create a brand new wallet and I'm unsure if we provide a warning

upon checking this flow out it does look like we attempt another wallet creation = http://recordit.co/Ns8Zuwyuep

perhaps we don't allow any way to get back to that view?  Disable swiping and native android back button probably should do the trick

**Comment by ibrahimtaveras00** [comment]
**Issue 13** 

Similar to issue 3, when I am already logged in then I log out and attempt to create a new wallet, on prod I'm prompted with a warning, however, on this branch there is no warning; seen here = http://recordit.co/Znp4SVYphn

**Comment by ibrahimtaveras00** [comment]
Not really an issue per-se but more of an observation 

On a smaller device, (i'm currently on iPhone 5s simulator) after a user inputs password, the page doesn't automatically scroll to the bottom, and there is no indication that the user should scroll down to continue, I'm wondering if this would confuse some users; seen here = http://recordit.co/5b0gKog21T

**Comment by ibrahimtaveras00** [comment]
**Issue 14:**

On a smaller device (left in screencast and screenshot is Android Galaxy_Nexus emulator) the confirm CTA on the manual seed phrase back up flow is covering the password text input field; seen here = https://recordit.co/DyDpWNQBwu

Screen Shot 2020-07-20 at 8 51 23 PM

to get here you have to do the create wallet > create password > skip backup > then tap on alert on bottom of screen, then continue with backup

**Comment by andrepimenta** [comment]
@ibrahimtaveras00 you can QA again. This is the report for the issues found:

- Issue 1
I think you forgot to do `yarn install`. I think you also have to do `yarn start:ios` or `yarn start:android`  again because it is a native module

- Issue 2:
Fixed

- Issue 3
Will be solved by Esteban PR

- Issue 4
Fixed

- Issue 5
Fixed

- Issue 6
Fixed

- Issue 7
Fixed

- Issue 8:
Fixed

- Copy on carousel (cjeria):
Fixed

- Issue 9:
When we logout we basically remove everything stored in the keychain including the fingerprint that is why the warning. 
You do have to put manually the password again, and then, the fingerprint will work on next attempts. I removed the biometric button on those situations.

- Issue 10:
This is a limitation of our current version of the library we are using for biometrics. Right now it’s only fingerprint and Face ID. We should update the library to allow more biometrics right after V1.

- Issue 11:
Fixed

- Issue 12:
Fixed

- Issue 4a:

Fixed

- Issue 13:
Fixed

- Improvement create password on smaller device:
Fixed

- Issue 14:
Fixed

**Comment by ibrahimtaveras00** [comment]
- Majority of all of **issue 6** is fixed only one exception is the view with the title "Secure you wallet" still shows as colored in even though the step is not completed yet.

image

- **Issue 8 a:** issue 8 is fixed, however, I noticed that on iOS when the keyboard is open, and you're finished typing, there is no way to tap the Save CTA (on android it's not such a big deal as I can tap the native back button to dismiss the keyboard) 

seen here = https://recordit.co/lgt43Hqg0z


**Other issues found today:**

- **Issue 15** If you have the app installed but haven’t created a wallet yet, and then open a deep link  = https://metamask.app.link/dapp/uniswap.exchange then the app will give you this error
image

seen here = http://recordit.co/5F30U79R6T

- **Issue 16** The confetti animation upon syncing with extension is glitching on Android devices (tried on Google Pixel + Samsung Galaxy) 

Video seen [here](https://consensys.slack.com/archives/GBW7S9FSN/p1595447108235400)

- **Issue 17:** I noticed that when you have already synced or imported your wallet, and then choose to log out, and create a new wallet, if you skip the back up we don’t show the sticky alert on the bottom of the screen anymore; seen here = https://recordit.co/LI9JKtOrqp

steps:
- sync with extension, or import your seed phrase
- open drawer and tap log out > YES
- Tap Go Back
- Select Create Wallet
- Tap remind me later and skip 
- once you're on wallet view, there is no sticky alert at the bottom to bring you back to the backup flow

Also there is a small copy update from @omnat; change to Settings > Security & Privacy on this Wallet imported view

There were a few UI issues I saw on some devices that I pinged @rickycodes about
- Nexus S on the onboarding carousel when you first launch the app (get started CTA is missing) 
- Adding spaces in between steps on the Scan QR code steps modal

**Comment by ibrahimtaveras00** [comment]
**Issue 18:**

On a newly created wallet from develop that never had funds sent, as soon as funds are sent on this branch, I get the old secure your wallet modal, but it took me to the new create password flow and created a new wallet (funds lost) = http://recordit.co/aytLTHBHvT

Here at the 1 second mark you can see my address on account 1 with funds:

image

But the newly created wallet with a new address as account 1 with no funds: 

image

**Comment by cjeria** [comment]
Let's reduce the size of the graphic by ~30% - ~50% to match the design. That should help not hide the text below the button as well as make room to vertically center the "Remind me later" button/text.

image

**Review by ibrahimtaveras00 — APPROVED** [review]
we are QA Passed 🚀

**Pull request merged**
