### PR TITLE
On-ramp: Add #5870 localization

### PR DESCRIPTION
**Pull request by wachunei**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

This PR adds the translated strings for #5870 

**Screenshots/Recordings**

~~_If applicable, add screenshots and/or recordings to visualize the before and after of your change_~~

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by Cal-L — APPROVED** [review]
LGTM

**Comment by cortisiko** [comment]
So a couple of things here: 
In prod, the linked text [“Import tokens”](http://recordit.co/wlWQhsXkqg) was on a separate line and that link was tappable.

Are we now making the entire line [“Don’t see your token? Import tokens”](http://recordit.co/ACJDuQpf9Z) tappable? 

If the answer to the above is yes, then we need to decrease the font size of the [import token](https://www.screencast.com/t/oRjFY5Eim) link for languages with long translated strings such as Filipino.   

compared to [prod v6.1.2 ](https://www.screencast.com/t/h3TmJQoY)

**Review by Cal-L — APPROVED** [review]
@wachunei confirms that the text will be centered but the link itself can wrap. Code LGTM and will defer to @cortisiko for anymore questions.

**Review by cortisiko — APPROVED** [review]
✅ ✅ ✅

**Pull request merged**
