### PR TITLE
React native upgrade 0.62.2 hermes rebased

### LINKED ISSUE #1201: Migrate to React Native v0.61.+
Sooner or later we will get pay the price of being behind and the migration itself it's a considerably big project.

Things to take into account:

- Need to create a new project and start moving things in.
- Make sure packages support pods instead of react-native link
- Try hermes and compare with current performance of v8

### PR DESCRIPTION
**Pull request by andrepimenta**
This is the react native 0.62.2 upgrade with the Hermes engine enabled. The code that enables Hermes can be found here.

The Hermes documentation can be found here.

The performance tests should be done in release mode.

For other info about the upgrade check #1586.

Issue

Resolves #1201 (Hermes point)

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
LGTM 🤞

**Comment by omnat** [comment]
[React Native upgrade #2](https://trello.com/c/JAVWAOdX/70-react-native-upgrade-2)

**Comment by ibrahimtaveras00** [comment]
@andrepimenta, @estebanmino, @omnat 

It is in my opinion that v8 is still smoother than hermes; see performance comparisons below:

In all screen casts, this branch in release mode is on left (Samsung Note 9 device) and playstore is on right (Google Pixel 3 XL)

side by side comparison of devices if interested = https://www.gsmarena.com/compare.php3?idPhone1=9163&idPhone2=9257

I am connected to the same wifi on each device

**Launch app > drawer > wallet** 

Notice how long it takes the drawer to open and how long it takes to go to wallet.  I've noticed that v8 responds faster to touch in comparison to hermes

seen here = https://recordit.co/IxFT5Tyev1

Switching networks on wallet view > tapping on collectibles 

seen here = https://recordit.co/VdW77s4P9D

switching accounts on collectibles view > going to tokens > open drawer > switch accounts > go to collectibles > go to txn history and scroll > tap on a txn > view on etherscan > go to wallet > tokens > search token > tap token > select token > remove token 

seen here = https://recordit.co/rFEbuacIa2

on wallet view, switch networks > tap on ETH asset > tap send > transfer between accounts > select account > enter amount > on confirm tap edit and edit gas > send txn

The app actually crashed on hermes branch in this example

seen here = https://recordit.co/s7GdUuof81

on browser, go to faucet > donate > connect > Edit > change gas and amount > send > view on etherscan 

this one was pretty much the same in regards to performance 

seen here = https://recordit.co/9JpQMNlSug

Send collectible flow on mainnet (there was a crash on hermes branch)

seen here = https://recordit.co/90csr3fE96

These are just some examples.  Overall I feel like v8 definitely responds quicker to touch and just feels smoother overall IMO

Feel free to take a look on your devices to see if it's the same experience for you.

**Comment by ibrahimtaveras00** [comment]
This may help too 

https://sentry.io/organizations/metamask/issues/?project=2299799&query=is%3Aunresolved+hermes%3Atrue&statsPeriod=14d

Screen Shot 2020-05-22 at 12 20 53 AM

**Comment by andrepimenta** [comment]
I guess Hermes is still too new to be added now. I also found this performance comparison:
https://docs.google.com/spreadsheets/d/1XB6fuk-NYZbCDikxQOAJemE-P8cfbsfdXivTeVwcwIk/edit#gid=469794458

So I think it's better for now to stick with our V8. I also updated our V8 to the newest version (on the updated libs branch).

**Pull request closed without merging**
