### PR TITLE
feat: update walletconnect se-sdk

### PR DESCRIPTION
**Pull request by abretonc7s**
## **Description**

Update walletconnect se-sdk to latest 1.8.1

## **Related issues**

Fixes:

## **Manual testing steps**

1. Documentation and evidence is include in the comments

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by abretonc7s** [comment]
@SocketSecurity ignore npm/@walletconnect/sign-client@2.13.3
@SocketSecurity ignore npm/@walletconnect/core@2.13.3
@SocketSecurity ignore npm/@walletconnect/types@2.13.3
@SocketSecurity ignore npm/@walletconnect/utils@2.13.3
@SocketSecurity ignore npm/@walletconnect/web3wallet@1.12.3

**Review by andreahaku — DISMISSED** [review]
LGTM

**Review by elefantel — DISMISSED** [review]
Looks good

**Comment by christopherferreira9** [comment]
QA was performed by the folks at WalletConnect themselves.

**Review by elefantel — DISMISSED** [review]
Looks good

**Review by elefantel — APPROVED** [review]

**Comment by christopherferreira9** [comment]
Test cases performed by WalletConnect:
image (2)

**Comment by sethkfman** [comment]
Team will be following up with unit testing ticket [here](https://github.com/orgs/MetaMask/projects/60/views/3?pane=issue&itemId=71293115). Deemed sufficiently tested by WC and internal team via manual testing.

**Review by sethkfman — APPROVED** [review]
LGTM

**Pull request merged**
