### PR TITLE
UI/CustomGas: fix inconsistent low gas error

### LINKED ISSUE #1833: Gas too low error message inconsistent
**Describe the bug**
The `gas price extremely low` error message that appears when editing the advanced custom gas controls is broken in   some cases. User reported the error displaying even after entering 6000 GWEI

**Screenshots**
Screenshot_20200911-154207

**To Reproduce**
_Steps to reproduce the behavior_
1. Create a swap in Uniswap
2. Edit the gas, tap 'advanced'
3. Clear the gas price field
4. Type 1000
5. Error message stays

**Expected behavior**
Error message is supposed to clear if gwei is above safe low

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by EtDu**
Fixes "gas price extremely low" error message showing up inconsistently. 

Resolves #1833

### CODE REVIEW

**Review by rickycodes — APPROVED** [review]

**Review by ibrahimtaveras00 — APPROVED** [review]
This issue is fixed, QA Passed 👍 

There were some other issues I noticed, where I couldn't tap save on android, and that no error shows up whatsoever on wallet send flow, but I'm assuming those two issues will be fixed in these issues :

[Gas Issue One](https://trello.com/c/Hz0K0YDF/247-gas-estimation-seems-off-advanced-gas-not-working)
[Gas Issue Two](https://trello.com/c/TyjdNnRN/228-unify-customgas-components-for-dapp-wallet-txs)

**Review by nicc938 — APPROVED** [review]

**Comment by EtDu** [comment]
@ibrahimtaveras00 Yes, I have that one captured. https://github.com/MetaMask/metamask-mobile/issues/1834

**Review by nicc938 — APPROVED** [review]

**Review by omnat — COMMENTED** [review]
https://trello.com/c/oRRxpJsW/231-make-insufficient-fee-error-descriptive-add-link-to-buy-eth
@EtDu is this the copy you updated here?

**Comment by EtDu** [comment]
@omnat No, this is a different issue. I haven't gotten to that one yet.

**Pull request merged**
