### PR TITLE
feat: add missing `wallet_requestPermissions` and `wallet_getPermissions` to the mobile API.

### PR DESCRIPTION
**Pull request by shanejonas**
**Description**
Added missing methods `wallet_requestPermissions` and `wallet_getPermissions` to the mobile API.

This brings it in line with the extension API so that dapps that build against requestPermissions don't have to have extra logic to do `requestAccounts` instead.

fixes https://github.com/MetaMask/MetaMask-planning/issues/861

**Screenshots/Recordings**

some screenshots of it working in the new api playground:

### `wallet_requestPermissions`
image
image
#### error case:
image

### `wallet_getPermissions`

image

### CODE REVIEW

**Review by Woodpile37 — APPROVED** [review]

**Review by Woodpile37 — APPROVED** [review]

**Review by Cal-L — DISMISSED** [review]
LGTM

**Comment by sethkfman** [comment]
E2E Tests: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/6463c0ac-989b-4240-82dc-20af3242a639

**Comment by sethkfman** [comment]
E2E Run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/bbdfea59-e8f5-493c-9c1b-e7ac3dd9593c

**Review by sethkfman — APPROVED** [review]
LGTM

**Pull request merged**
