### PR TITLE
[FIX] Issue #207

### PR DESCRIPTION
**Pull request by gantunesr**
**Description**

[Issue #207](https://github.com/MetaMask/mobile-planning/issues/207)

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by chrisleewilcox** [comment]
After setting custom spend limit and approving USDT ==> UNI swap, I am not able to approve swapping back the uni for usdt now. Always getting the JSON-RPC error...
https://recordit.co/nOhFzutlbh

**Comment by chrisleewilcox** [comment]
After setting custom spend limit and approving USDT ==> UNI swap, I am not able to approve swapping back the uni for usdt now. Always getting the JSON-RPC error...
https://recordit.co/nOhFzutlbh

**Comment by chrisleewilcox** [comment]
Getting way too many JSON-RPC errors during approval and swaps that I don't feel confident the testing will be effective for swaping on dapps.  Please address JSON-RPC errors.

**Review by sethkfman — APPROVED** [review]
LGTM

**Pull request merged**
