### PR TITLE
Defaults to current network if chain id not specified in QR codes

### LINKED ISSUE #3847: Network Not Found - Missing chain id.
**Describe the bug**
Within Metamask 4.1.1 (Android), using QR Code to scan in code from my desktop screen.  The error message appears within the mobile app:

Network Not Found
Missing chain id.

**Screenshots**
[img]https://i.imgur.com/x3Y42to.png[/img]

**Smartphone (please complete the following information):**
 - Phone: Umidigi F1
 - OS: Android 9
 - App Version: 4.1.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by Fatxx**
**Description**

Use current network as default if chain id is not specified in QR codes or deeplinks.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #3847 and https://github.com/metamask/mobile-planning/issues/178

### CODE REVIEW

**Review by cortisiko — APPROVED** [review]
🌮 🌮 🌮 🌮

**Review by gantunesr — APPROVED** [review]
lgtm

**Comment by mobularay** [comment]
Take-away from Mar 24 sprint review: @Fatxx @omnat @andrepimenta to discuss the logic on how chainID and QR code should interact with each other

**Review by gantunesr — CHANGES_REQUESTED** [review]
Waiting on resolution for this PR

**Comment by Fatxx** [comment]
Still discussing with @omnat possible changes.

**Review by gantunesr — APPROVED** [review]

**Review by cortisiko — APPROVED** [review]
🌮 🌮 🌮 🌮 🌮 🌮 🌮

**Pull request merged**
