### PR TITLE
feat: Update transaction controller to v7.1.0

### PR DESCRIPTION
**Pull request by tommasini**
## **Description**
This PR aims to update transaction controller to version 7.1.0, in order to complete the update to controllers version 61.

All the changes are present in this core branch for an easy review: patch/mobile-transaction-controller-7-1-0

## **Related issues**

Fixes:

## **Manual testing steps**

1. Performed EIP 1559 transaction
2. Performed sendflow transaction

## **Screenshots/Recordings**

EIP 1559: https://recordit.co/m55xYCyBQX
Sendflow tx: https://recordit.co/T462M1VbYL

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by tommasini** [comment]
@SocketSecurity ignore npm/@metamask/transaction-controller@7.1.0

It seems that the issue presented on this version, were already existing (detected when core repo converted to mono repo) and with an ethereumjs lib that we currently use and test

**Comment by sleepytanya** [comment]
QA [build](https://app.bitrise.io/build/03e5f158-4c30-4fb1-9843-c410208ecce9?tab=artifacts), Sepolia, Linea Goerli and mainnet for swaps:

- [x]  Transactions - send native token origin MM
- [x]  Transactions - send native token origin dapp
- [x]  Transactions - send ERC20 token origin MM
- [x]  Transactions - send ERC20 token origin dapp
- [x]  Transactions - send ERC721 token origin MM
- [x]  Transactions - send ERC721 token origin dapp
- []  Transactions - speed up transaction
- []  Transactions - cancel transaction
- [x]  Tokens - import ERC20 token origin MM
- [x]  Tokens - import ERC20 token origin dapp
- [x]  Tokens - import ERC721 token origin MM 
- [x]  Tokens - import ERC721 token origin dapp
- [x]  Tokens - import ERC1155 token origin MM 
- [x]  Tokens - import ERC1155 token origin dapp 
- [x]  Tokens - approve ERC1155 token
- [x]  Tokens - approve ERC20 token
- [x]  Tokens - approve ERC721 token
- [x]  ENS - name resolution (works on mainnet only, the same way it works on extension)
- [x]  Gas fee - EIP-1559 gas
- [x]  Gas fee - legacy gas
- [x]  Sign - eth sign
- [x]  Sign - personal sign
- [x]  Sign - sign in with ethereum
- [x]  Sign - sign typed with data
- [x]  Permissions - connecting and disconnecting from a dapp
- [x]  Swap - swap eth
- [x]  Incoming transactions history
- [x] custom nonce
- [x] cancel transaction using custom nonce 
- [x] stuck multiple transactions (cancel / speed up)

**Review by MarioAslau — DISMISSED** [review]
LGTM

**Review by Cal-L — DISMISSED** [review]
LGTM, would be great if we can get a second pair of eyes WRT the patches as well. cc @matthewwalsh0

**Comment by sleepytanya** [comment]
Transactions regression passed.
[Updated usage](https://github.com/MetaMask/metamask-mobile/pull/8784) of OP Goerli to OP Sepolia  works as expected:


https://github.com/MetaMask/metamask-mobile/assets/104780023/d797efd6-cb38-42ef-bc3b-0bb52723cf98

**Review by matthewwalsh0 — APPROVED** [review]

**Comment by tommasini** [comment]
@SocketSecurity ignore-all
It seems that no packages were added/removed/updated during this updated to transaction controller, we can accept this risk

**Pull request merged**
