### PR TITLE
[FIX] Android Keyboard Text Entry

### LINKED ISSUE #3460: Android Keyboard Issues
**Description**
Multiple users have been reporting unable to type text fields in the application. 

**Technical Requirements**
Remove keyboard learning for gboard only

**Acceptance Criteria**
Samsung and other platform keyboards work with patch
Gboard keyboard learning is disabled

PR
#3459

### PR DESCRIPTION
**Pull request by sethkfman**
**Description**

Added a check for users using `gboard` as a keyboard and removing keyboard learning during the use of the MetaMask app. 

**Checklist**

* [X] There is a related GitHub issue
* [X] Tests are included if applicable
* [X] Any added code is fully documented

**Issues**

Related #3460

### CODE REVIEW

**Review by cortisiko — APPROVED** [review]
okay so I tested:

- browser keyboard interactions, deleting a wallet, searching for tokens, adding a token, adding an NFT, requesting a token, searching for a token(s) in the swaps flow & Entering your password in the secure your wallet flow.  

- enabled gboard then repeated the first bullet point

- enabled swiftKey Keyboard then repeated the first bullet point

- disabled gboard and enabled samsung keyboard and repeated the first bullet point

with that being said, 🌮 🌮🌮🌮🌮🌮

**Review by CryptoGGytrs52 — APPROVED** [review]

**Review by Cal-L — CHANGES_REQUESTED** [review]
Request to remove extra RN patch changes. LGTM after that's addressed

**Comment by sethkfman** [comment]
@Cal-L Updated RN patch.

**Review by Cal-L — APPROVED** [review]
LGTM

**Pull request merged**
