### PR TITLE
[IMPROVEMENT] Warn when exporting SRP

### LINKED ISSUE #3544: Warn when exporting SRP
### **Description**

Goal: Reduce exposure of SRP. 
Intended effect: Users do not share their SRP with phishers/attackers.

### **Technical Details**

-   Implementation details
-   Insight to what needs to be done
-   Etc.

### **Acceptance Criteria**

- Update to unify reveal SRP flow per [new logic](https://www.figma.com/file/8z4Csc3wlOIkUz2OP1eTZW/Secure-UX-Improvements?node-id=447%3A7924) 
- Require password (biometrics shouldn't override this requirement)
- Only reveal SRP after user holds the "Hold to reveal" button until it unlocks (need to define time duration)
- Make this button as a re-usable component
- If the user copies the SRP to clipboard, flush it after X seconds (same as current time)
- Ship this with translations for all supported languages

### **References**

Design file: https://www.figma.com/file/8z4Csc3wlOIkUz2OP1eTZW/Secure-UX-Improvements?node-id=44%3A1391
Links from UI to the articles: 
Secret Recovery Phrase (SRP) link: https://metamask.zendesk.com/hc/en-us/articles/4404722782107-User-guide-Secret-Recovery-Phrase-password-and-private-keys
Non-custodial wallet link: https://metamask.zendesk.com/hc/en-us/articles/360059952212-MetaMask-is-a-non-custodial-wallet

Notion doc with story description: https://www.notion.so/Warn-me-about-risks-when-I-m-exporting-my-seed-phrase-f610550a8c464240a46880b06ebbdc42

### PR DESCRIPTION
**Pull request by andreahaku**
### **Description**

Goal: Reduce exposure of SRP. 
Intended effect: Users do not share their SRP with phishers/attackers.

User Story: https://www.notion.so/Warn-me-about-risks-when-I-m-exporting-my-seed-phrase-f610550a8c464240a46880b06ebbdc42
Design: https://www.figma.com/file/8z4Csc3wlOIkUz2OP1eTZW/Secure-UX-Improvements?node-id=44%3A1391
Metrics: https://docs.google.com/spreadsheets/d/1hxWnGzJI_8pfa8CwDqqoWAwkzuTyx6AukkmRBl3asC0/edit#gid=1224808665

**Checklist**

* [X] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #3544

### CODE REVIEW

**Review by sethkfman — COMMENTED** [review]
Minor spelling issue

**Review by sethkfman — APPROVED** [review]
LGTM

**Review by plasmacorral — CHANGES_REQUESTED** [review]
I have 3 observations, 2 of which may be bugs and the first of which is a merge blocker.

#1 description: SRP modal displayed after selecting "show private key", entering password, and tapping "next".  This is a merge blocker.

#2 description :CTA for long press does not set user expectation on how long to hold

#3 description: 'Hold to reveal SRP" CTA occasionally does not reveal SRP after being held and may merit further investigation.

Steps to reproduce: Import using SRP, set password, tap hamburger menu, tap 'settings', tap 'security and privacy', tap 'show private key' (for number 1) else tap 'reveal secret recovery phrase', then press and hold 'hold to reveal SRP' 

Screenshot for #1:
IMG_0013

Android Logs (showing #1): 
[Android_MetaMask State logs -  v4.0.1 (814).zip](https://github.com/MetaMask/metamask-mobile/files/8037100/Android_MetaMask.State.logs.-.v4.0.1.814.zip)

iOS logs (showing #1 & 3):
[IOS_state-logs-v4.0.1-(814).json.zip](https://github.com/MetaMask/metamask-mobile/files/8037103/IOS_state-logs-v4.0.1-.814.json.zip)


1) The new SRP modal is shown when the user selects "show private key".  The copy in the modal is SRP specific.  While I would like to eventually see the press to hold functionality added to private key reveal, presenting SRP copy over show private key is not ideal. (See screenshot) If we were to consider making the copy less specific then we could potentially introduce press to hold for reveal to SRP and private keys at the same time.  In the current state, I am withholding QA approval pending a resolution.
2) The spinning animation to help set the user expectation of how long to hold the CTA for is not implemented.  The press to hold function works, but a user will currently not have an expectation of how long to hold.  I think its important to help establish this expectation and would like to see this implemented before we merge.
3) I have noticed twice now that when I first tap and hold and the button, the SRP is not presented.  I have seen this on both iOS as well as Android. I was able to capture it in the iOS logs.  It was actually the 4th time I pressed and held the CTA before the SRP was presented. I'd love to give you a video, but these screens aren't able to be recorded.  While I have seen it at least once on android (having to hold a second time) I was not able to capture that behavior in the android logs I am sharing here.

**Review by plasmacorral — CHANGES_REQUESTED** [review]
I forgot to mention the links not working, and saw a couple other things jumping back in: 

4) No links on the "Reveal Secret Recovery Phrase" page
	4a) The blue font leads me to believe that I can click and link out for more info but tapping the blue font does nothing.  "Secret Recovery Phrase (SRP)" should link to here: https://metamask.zendesk.com/hc/en-us/articles/4404722782107-User-guide-Secret-Recovery-Phrase-password-and-private-keys 
	
	4b) "Non custodial wallet" should link here https://metamask.zendesk.com/hc/en-us/articles/360059952212-MetaMask-is-a-non-custodial-wallet).  

5) Missing Hyphen on the "Reveal Secret Recovery Phrase" page
	"Non custodial" should be hyphenated to remain consistent with other support docs.

6) Truncated title on smaller screens
	On the "Reveal Secret Recovery Phrase" page the title is cut off on the iphone 13 mini and displays "Reveal Secret Recover..."  Should this be dynamically sized to fit on the smaller screen?

7) One more missing link on the on the "Keep your SRP safe" modal
	On the "Keep your SRP safe" modal, the "but phishers might" should link to here https://metamask.zendesk.com/hc/en-us/articles/4407169552667-Scammers-and-Phishers-Rugpulls-and-airdrop-scams and does not when tapped.

**Review by plasmacorral — CHANGES_REQUESTED** [review]
8) "Backup now" has no press and hold to display SRP.  
To remain consistent, we should implement press and hold to reveal functionality for the user that has not previously completed a backup to protect their wallet.

Steps to reproduce: Create new wallet, set password, Remind me later on Secure your wallet, I understand, skip, tap the burger menu, tap settings, tap security and privacy, tap backup now, tap start, enter password and tap confirm, tap view to reveal the SRP.

**Comment by andreahaku** [comment]
@plasmacorral I've updated the code and:

1. SRP modal no longer appears when revealing the private key. No change to the actual `reveal private key` flow is made as the task it focused on SRP
2. waiting for the component to be created
3. I've not been able to reproduce the issue. I'll try again and if I'll do I'll fix it.
4. added links
5. added missing hyphen
6. this is the same for every title in the app
7. added missing link
8. out of the scope of the task

**Review by plasmacorral — APPROVED** [review]

**Review by plasmacorral — CHANGES_REQUESTED** [review]
Can confirm that concerns # 1, 4, 5, and 7 are now resolved on iOS and Android (to the extent I could verify links on Android with the currently known deep linking issue).

Unfortunately, I found an issue that also exists in what I tested yesterday as well as today in the latest commit b719adecdd30887f1a47f316d99da391d30ff39f.  I believe this may also be a merge blocker.

9. The 60 second clipboard timer does not expire on Android and can be pasted for as many as 4+ minutes.
     Using a OnePlus 6 A6003, running android 10 security update September 1, 2020 I noticed that the 60 second clipboard timer does not work as expected.  I do have a video that I can send direct, but I am able to paste the SRP for >4 minutes after copy.
     
Steps to recreate: Restore a wallet, set password, tap hamburger menu, tap settings, tap security and privacy, tap reveal secret recovery phrase, enter password, tap next, tap  and hold 'hold to reveal SRP', tap copy to clipboard, open Notes application and paste SRP.  Rinse and repeat over several minutes and note that SRP continues to be successfully paste after 60 seconds.
     
    
[MetaMask State logs -  v4.0-1.1 (814).zip](https://github.com/MetaMask/metamask-mobile/files/8043962/MetaMask.State.logs.-.v4.0-1.1.814.zip)

**Review by plasmacorral — CHANGES_REQUESTED** [review]
Ok, I revisited 9. on a Pixel 3a running Android 12 with the Febuary 5, 2022 security update.  I have MetaMask dumpstate logs, as well as an android bug report and possibly a system trace covering 2 issues, both #9 and #3.  I also have a video recording of the device showing several unsuccessful tap and holds of the new "Hold to reveal SRP" button. 

[MetaMask State logs -  v4.0.1 (814).zip](https://github.com/MetaMask/metamask-mobile/files/8045122/MetaMask.State.logs.-.v4.0.1.814.zip)


[dumpstate-stats.txt](https://github.com/MetaMask/metamask-mobile/files/8045123/dumpstate-stats.txt)


[bugreport-sargo-SQ1A.220205.002-2022-02-10-18-48-11-dumpstate_log-18912.txt](https://github.com/MetaMask/metamask-mobile/files/8045124/bugreport-sargo-SQ1A.220205.002-2022-02-10-18-48-11-dumpstate_log-18912.txt)

**Comment by andreahaku** [comment]
@plasmacorral I've added the animated 'hold to reveal' button. Can you please check if this also solves the issues with Android not being consistent on pressing. Thanks :)

**Review by plasmacorral — CHANGES_REQUESTED** [review]
Tap and hold to reveal functionality is not currently working on android.  I have directly shared state logs and an android bug report.  On iOS the button can be tapped and held to reveal SRP.

Will pause further QA tests until there are some changes made for the android build.

**Comment by plasmacorral** [comment]
> > 9. The 60 second clipboard timer does not expire on Android
> 
> Is 9. still a problem?

Yes.  Its a problem in that the expectation is set for the user that the clipboard will be purged after 60 seconds, but that is still not happening.  

There is suspicion that this may be a limitation within android and if that's the case, we will at least need a copy update before this can be merged.  @andreahaku is planning to investigate this further and will advise on our path forward.

**Review by plasmacorral — CHANGES_REQUESTED** [review]
Can confirm that (2) is addressed and functioning on both iOS and Android.

(9) is still a concern that I would not approve merging in the current state.  For android devices we wither need to adjust the copy to remove the 60 second clipboard purge, or figure out how to make it more effective.  I can still copy/paste well after 60 seconds.    

I am still experiencing (3) sporadically.  I suspect that it has to do with sensitivity to the position of where the user is touching and holding.  If I am slow and deliberate with a consistent pressure, everything seems to work fine.  However, if there is variation in the pressure applied or even a slight of shift of the held position, the hold is released even if the finger/stylus is not picked up. 

I further explored this after changing Settings>Accessibility>Touch & hold delay.  I tested short, medium and long.  Changing the settings did not notably change the experience.

As-is, I could accept that I am not executing the "ideal" tap and hold with consistent pressure in the exact same position.  However, I am curious if within the app we can adjust the sensitivity for the button and make this more user friendly? If I am aggressive or punchy with my tap, the button does not respond as a (this) user might hope.

Below are footage and recent logs for (3):
https://recordit.co/oziYihVwnm
State logs:
[MetaMask State logs -  v4.1-1.0 (816).zip](https://github.com/MetaMask/metamask-mobile/files/8120861/MetaMask.State.logs.-.v4.1-1.0.816.zip)
Android bug report:
[bugreport-guamna_t-RZAS31.Q2-146-14-5-2022-02-22-17-17-12-1.zip](https://github.com/MetaMask/metamask-mobile/files/8120863/bugreport-guamna_t-RZAS31.Q2-146-14-5-2022-02-22-17-17-12-1.zip)

**Comment by bschorchit** [comment]
> Last commit updates the copy for Android when copying SRP ("Secret Recovery Phrase copied to clipboard" plain and simple). Let me know what you think about it.

Looks good to me! Thanks, Andrea!

**Review by plasmacorral — APPROVED** [review]
Observations 1,2,4,5,7, & 9 have been fixed and verified.
Observation 8 is out of scope for this change
Observation 6 appears throughout the app and is not a blocker here
Observation 3 is something I still occasionally experience, but I believe it to be related to variable position/pressure in the held tap and do not consider it to be a blocker.

With all that said, this is my approval.

**Pull request merged**
