### PR TITLE
fix: fix inconsistency in the popular tab

### LINKED ISSUE #8250: [Bug]: inconsistency in the Popular tab , it should be displayed im Lower case
### Describe the bug

It appears there is an inconsistency in the display of text within the "Popular" tab of the app. The text that is currently showing in uppercase should instead be displayed in lowercase.

### Expected behavior

_No response_

### Screenshots/Recordings

_No response_

### Steps to reproduce

1. Go to Add Network
2. Check the difference between "popular tab" and "custom network tab"

### Error messages or log output

_No response_

### Version

7.1.0

### Build type

None

### Device

Iphone 13

### Operating system

iOS

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by salimtb**
## **Description**

fix inconsistency in the Popular tab , it should be displayed im Lower case 

## **Related issues**

Fixes: [#8250](https://github.com/MetaMask/metamask-mobile/issues/8250)

## **Manual testing steps**

1. Go to add Network
2. You can see the popular tab in UpperCase

### **Before**
Screenshot 2024-01-11 at 10 04 11

### **After**
Screenshot 2024-01-11 at 10 03 32

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by NicolasMassart — COMMENTED** [review]
The change in the app is ok for me, but according to the Slack discussion, you should also update e2e for this change:
https://github.com/MetaMask/metamask-mobile/blob/main/e2e/selectors/Settings/NetworksView.selectors.js#L13
Ideally this would be part of the requirements for done in the issue. Creating an issue even if you have a Slack thread is a good practice. Consider Slack is not preserving messages indefinitely and is not available to people outside Consensys. Having an issue on the repo itself, even if it seems redundent with the Slack, is good for contributors to understand the code changes.

**Comment by salimtb** [comment]
> The change in the app is ok for me, but according to the Slack discussion, you should also update e2e for this change: https://github.com/MetaMask/metamask-mobile/blob/main/e2e/selectors/Settings/NetworksView.selectors.js#L13 Ideally this would be part of the requirements for done in the issue. Creating an issue even if you have a Slack thread is a good practice. Consider Slack is not preserving messages indefinitely and is not available to people outside Consensys. Having an issue on the repo itself, even if it seems redundent with the Slack, is good for contributors to understand the code changes.

hello @NicolasMassart ,
thanks for your comment :) , an issue on github has been created and linked to this PR now, i agree it's a better practice.
regarding the e2e tests, the modification has already been made on the`e2e/selectors/Settings/NetworksView.selectors.js` file, is there anything else I need to do ?

**Review by cortisiko — DISMISSED** [review]
LGTM

**Review by cortisiko — DISMISSED** [review]

**Review by tommasini — APPROVED** [review]
LGTM

**Pull request merged**
