### PR TITLE
test: fix mock server

### LINKED ISSUE #12544: Fix mobile mocking server and pipeline

### PR DESCRIPTION
**Pull request by vinistevam**
## **Description**

This PR addresses an issue with the mock server spotted in confirmation tests during E2E runs. Previously, the mock server did not properly support multiple instances of the mobile app when running tests across multiple workers in the pipeline, leading to conflicts and unreliable behaviour.

**Changes:**
**Port Management for the Mock Server:** A specific port is now assigned to the mock server via the `withFixtures` helper function. This ensures that each test worker uses an isolated and unique mock server instance.

**App Initialization Updates**: The mobile app is now launched with the specified mock server port, ensuring requests are correctly routed to the corresponding server.

Re-enabled security alerts E2E tests.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/12544

## **Manual testing steps**

1. Bitrise

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by vinistevam** [comment]
Run 2 https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/08d2bb7a-1ed1-46c6-9c14-4e9688e43ad9?tab=workflows

**Comment by vinistevam** [comment]
Run 3 https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/21642cc1-c1a7-41a3-abbe-465ac617e164?tab=workflows

**Review by Andepande — APPROVED** [review]
LGTM

**Review by cortisiko — APPROVED** [review]
🚀 🚀 🚀

**Pull request merged**
