### PR TITLE
fix: update usage of OP goerli to OP Sepolia

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

This PR's replaces the reference to OP goerli to OP sepolia.
Users that switch to OP goerli should still see the warning, and if they have already made transactions on OP goerli, they should still see them on activity tab.

Including the /compare diff URLs on core for visibility:

Core PR: https://github.com/MetaMask/core/pull/3999

https://github.com/MetaMask/core/compare/patch/mobile-transaction-controller-6-1-0...fix/update-OP-testnet-to-OP-sepolia

https://github.com/MetaMask/core/compare/patch/mobile-transaction-controller-7-1-0...fix/update-OP-testnet

## **Related issues**

Fixes: https://github.com/MetaMask/mobile-planning/issues/1569

CORE PR: https://github.com/MetaMask/core/pull/3999

## **Manual testing steps**

1. Add OP goerli to your networks
2. You should still see the warning of OP goerli
3. Create transactions on OP goerli
4. You should see them in your activity tab

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/10994169/abd9976a-04c0-4d37-8659-8a620b637240

### **After**

https://github.com/MetaMask/metamask-mobile/assets/10994169/3eb5e152-2a18-4ae2-914f-f9899a641e64

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by MarioAslau — DISMISSED** [review]
Looks good!

**Review by MarioAslau — DISMISSED** [review]
Lgtm!

**Comment by tommasini** [comment]
Hey @sahar-fehri , the core branch that follows the transaction-controller patch was updated?

**Review by tommasini — CHANGES_REQUESTED** [review]
Heyy, please add on the description the commit to the core branch with the new transaction-controller code, and if let me know if you have the time to do the same for the transaction controller version 7.1 branch `patch/mobile-transaction-controller-7-1-0` ?

**Comment by sahar-fehri** [comment]
> please add on the description the commit to th

Hey @tommasini , were you asking about this PR https://github.com/MetaMask/core/pull/3999 ?

**Review by matthewwalsh0 — APPROVED** [review]

**Review by tommasini — APPROVED** [review]
LGTM! Let's re run e2e with the final changes!

**Pull request merged**
