### PR TITLE
added Presearch as the default search engine

### PR DESCRIPTION
**Pull request by carrabre**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

Metamask currently only has DuckDuckgo & Google as options for default search. There are a few web3 search engines - this pull request makes it easy for one of them to be used. Both Metamask and Presearch are onboarding millions of users to web3. It would make sense to add Presearch as the default search engine ergo this pull request. This quick and easy change makes it easier for web3 users to search on a web3 search engine.

**Screenshots/Recordings**

https://user-images.githubusercontent.com/40183833/196310494-71410339-b831-44d8-878c-0842fc2683d2.mov

simulator_screenshot_C3C19238-46C7-4CB4-A408-9B7B23C4F036

**Issue**

Progresses #???

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

### CODE REVIEW

**Comment by carrabre** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by carrabre** [comment]
https://github.com/MetaMask/metamask-mobile/issues/5150#issue-1423250737

**Comment by gantunesr** [comment]
Hey @carrabre, thank you for your contribution. We're going to discuss your PR with the engineering and product team and get back to you as soon as possible.

cc @sethkfman @omnat

**Comment by carrabre** [comment]
How do is sign for CLA?

**Comment by carrabre** [comment]
> Hey @carrabre, thank you for your contribution. We're going to discuss your PR with the engineering and product team and get back to you as soon as possible.
> 
> cc @sethkfman @omnat

Awesome sounds great, thank you!

**Comment by carrabre** [comment]
> Hey @carrabre, thank you for your contribution. We're going to discuss your PR with the engineering and product team and get back to you as soon as possible.
> 
> cc @sethkfman @omnat

Hey @sethkfman @omnat, just checking in to see what the status of this is. Is there anything you'd need from our side?

**Comment by omnat** [comment]
Thanks @carrabre this is a very interesting proposition. We are revisiting our browser strategy moving forward in the coming months. I've added this PR as a feature request to capture this idea. We'll consider this as a path in our browser strategy before accepting this PR (to avoid taking on maintenance). Sorry for the long wait before my response on this.

**Comment by carrabre** [comment]
> Thanks @carrabre this is a very interesting proposition. We are revisiting our browser strategy moving forward in the coming months. I've added this PR as a feature request to capture this idea. We'll consider this as a path in our browser strategy before accepting this PR (to avoid taking on maintenance). Sorry for the long wait before my response on this.

No worries! Get that there is a lot happening in the space rn and that the holidays are just around the corner. 

Appreciate your thoughts. We should chat online about it - maybe some time in early January? Shoot me a message on twitter! https://twitter.com/alexcarrabre.

**Pull request closed without merging**
