### PR TITLE
Fix remove bookmark functionality

### LINKED ISSUE #1396: Unable to remove a Favorite URL in the Favorites tab on homepage
Seen here = https://recordit.co/Z0d6BlMwK3

Steps to reproduce:
- add any URL to favorites 
- go to homepage and tap on the Favorites tab
- attempt to remove that favorite

### PR DESCRIPTION
**Pull request by rickycodes**
Resolves #1396

### CODE REVIEW

**Review by estebanmino — COMMENTED** [review]
is `req` always an object or it could be undefined?

**Comment by rickycodes** [comment]
@estebanmino looks like it's always defined if you look at the rest of the file we're already using `req.params[0]` and `req.params[1]` all over the place... pretty sure this was just a mistake (regression)

**Review by danjm-temp — APPROVED** [review]

**Comment by danjm-temp** [comment]
Yeah, in the context of the `createAsyncMiddleware` callback, `req` should always be defined

**Comment by rekmarks** [comment]
`json-rpc-engine` always errors before calling any middlewares if `req` is `null`/`undefined`, or a non-`Object`.

**Review by estebanmino — APPROVED** [review]

**Review by ibrahimtaveras00 — APPROVED** [review]
Looks good on both OS's, QA Passed 👍

**Pull request merged**
