### PR TITLE
Add Alert component

### PR DESCRIPTION
**Pull request by wachunei**
**Description**

This PR adds a reusable and flexible Alert component:
Screen Shot 2020-12-10 at 23 54 04

Example code:

```js
<Alert small>
    A 12px small text{' '}
    <Text reset bold>
        really tiny
    </Text>
</Alert>

<Alert type="warning">
    Lorem ipsum dolor sit amet,{' '}
    <Text reset bold>
        consectetur
    </Text>{' '}
    asd adipiscing elit <Text link> A link</Text> inside.
</Alert>

<Alert type="error">
    Short error{' '}
    <Text reset bold>
        Bold text
    </Text>
</Alert>

<Alert
    renderIcon={() => (
        <IonicIcon style={{ fontSize: 22, color: colors.blue, marginRight: 8 }} name="md-arrow-down" />
    )}
>
    A 12px regular text{' '}
    <Text reset bold>
        really bold
    </Text>{' '}
    with any random icon of your choice.
</Alert>

<Alert
    type="warning"
    renderIcon={() => (
        <IonicIcon
            style={{ fontSize: 20, color: colors.yellow700, marginRight: 8, marginTop: 2 }}
            name="ios-notifications-outline"
        />
    )}
>
    Lorem ipsum dolor sit amet,{' '}
    <Text reset bold>
        consectetur
    </Text>{' '}
    asd adipiscing elit <Text link> A link</Text> inside.
</Alert>

<Alert
    type="error"
    onPress={() => { console.log("💔")}}
    renderIcon={() => (
        <IonicIcon
            style={{ fontSize: 22, color: colors.red, marginRight: 8 }}
            name="ios-heart-dislike"
        />
    )}
>
    {/* Chidren can be a render function if you want to render more than text */}
    {textStyle => (
        <View>
            <Text style={textStyle}>
                Short error,{' '}
                <Text reset bold>
                    Bold text
                </Text>
                , a dislike icon.
            </Text>
            <Text style={textStyle} small>
                (And also you can press me)
            </Text>
        </View>
    )}
</Alert>
```
**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
lgtm @ibrahimtaveras00 could you qa this prompting errors and warnings on the send flow?

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
A few warnings pop up when initiating alerts 

Screen Shot 2020-12-15 at 4 30 42 PM
Screen Shot 2020-12-15 at 4 30 48 PM
Screen Shot 2020-12-15 at 4 30 57 PM

Easiest way to reproduce is to have an address with 0 ETH, then initiate the send flow, and use this as your send to address = 0xdac17f958d2ee523a2206206994597c13d831ec7

**Comment by wachunei** [comment]
@ibrahimtaveras00 good catch, had some incorrect PropTypes set, fixed them! :D

**Review by ibrahimtaveras00 — APPROVED** [review]
Looks good, QA Passed 👍🏽

**Pull request merged**
