### PR TITLE
bugfix/protect wallet modal receive request

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

https://recordit.co/hRjvtiHwkc

Protect wallet modal wasn't working when closing QA code

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

### CODE REVIEW

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Tapping on the QR modal works 

However, tapping on copy nor share do not work

image

It only works if I kill the app and relaunch; seen here = https://recordit.co/bAIj0XGWWY

**Comment by estebanmino** [comment]
@ibrahimtaveras00 fixed

**Review by andrepimenta — APPROVED** [review]
👍

**Review by ibrahimtaveras00 — APPROVED** [review]
fixes look good, QA Passed 👍

**Pull request merged**
