### PR TITLE
feat: Update gas fee controller to version 6.1.2

### PR DESCRIPTION
**Pull request by tommasini**
## **Description**

Update 2 minor versions of gas fee controller -> final version 6.1.2

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

Sepolia transaction: https://recordit.co/42yD3oSRno

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by tommasini** [comment]
This PR will pass the linter when the network controller [PR](https://github.com/MetaMask/metamask-mobile/pull/8952) is merged and this branch receives that updated code.

**Review by Cal-L — DISMISSED** [review]
LGTM. Would be good to get a review from confirmations and/or swaps team as well

**Comment by sleepytanya** [comment]
QA build, physical Samsung s24+
https://app.bitrise.io/build/2b42504b-dfaa-48b2-8d33-dc73ed780f5a?tab=artifactsIt was 
Ethereum mainnet https://etherscan.io/address/0x2990079bcdEe240329a520d2444386FC119da21a

Nonce 940 was sent with Market gas settings, 941 - Aggressive and 942 with Low gas - gas prices match user settings.
Linea Goerli https://goerli.lineascan.build/address/0x2990079bcdEe240329a520d2444386FC119da21a
Nonce 124 Market settings, 125 Aggressive and 126 Low gas - gas prices match user settings.






[12:56](https://consensys.slack.com/archives/D06FPPNURPA/p1711040164468039)
https://goerli.lineascan.build/address/0x2990079bcdEe240329a520d2444386FC119da21a
https://etherscan.io/address/0x2990079bcdEe240329a520d2444386FC119da21a

**Review by Cal-L — APPROVED** [review]
Lgtm

**Pull request merged**
