### PR TITLE
fix(deps): eth-json-rpc-middleware@4.3.0->9.0.1

### PR DESCRIPTION
**Pull request by legobeat**
## **Description**
Update `eth-json-rpc-middleware` from `4.3.0` (2019-10-05) to `9.0.1` (2022-10-05).

## **Related issues**
- Preparation for #11952
- #11978

#### Blocked by
- [x] #11980

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/eth-json-rpc-middleware@9.0.1

network access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/ethereumjs-abi@0.6.6

False positive - this package is already part of runtime dependencies (also "new" author ok)

**Review by tommasini — APPROVED** [review]
LGTM

**Review by Cal-L — APPROVED** [review]
LGTM

**Review by sahar-fehri — APPROVED** [review]

**Review by Mrtenz — APPROVED** [review]

**Pull request merged**
