### PR TITLE
Customizable Search Engine

### PR DESCRIPTION
**Pull request by carrabre**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

We've implemented a feature that enables users to add whichever search engine they'd like as the default. We've also added Presearch as the new default search engine. Having Presearch by default provides the privacy standards of DuckDuckGo, while also bringing components of web3 being a decentralized search engine. Enabling users to add their own custom search engine will make for a better customer experience as well!

**Screenshots/Recordings**

https://user-images.githubusercontent.com/40183833/226741187-c384a097-c527-4e87-98b6-496ac87b7151.mp4

**Issue**

Progresses #???

**Checklist**

* [x] There is a related GitHub issue
* [] Tests are included if applicable
* [x] Any added code is fully documented

### CODE REVIEW

**Comment by mayocube** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mrjismyname** [comment]
Presearch as a default search engine option would be super.

**Comment by tgaper** [comment]
great

**Comment by freestriker00** [comment]
Will love to see presearch on Metamask.

**Comment by jejopl** [comment]
I would love to see presearch on metamask!

image

**Comment by tuhinsharma121** [comment]
a web3 wallet must have a web3 search engine.

**Comment by davviAD** [comment]
Presearch is the perfect fit for Metamask, it's the only truly decentralized web3 search engine.

**Comment by mohanaugust** [comment]
Wow. Great to see Presearch being added as a default search engine !

**Comment by Alpha-NDong** [comment]
Presearch on Meta Mask would be a great fit!!!

**Comment by KingKohei** [comment]
Every browser should give freedom of choice to its users, especially a web3 browser.
Presearch is a great choice as default search engine. It protects the users privacy and lives the spirit of a decentralized world! If Metamask wants to stay at the top of the game this is the way to go.

**Comment by nxlevel** [comment]
Awesome, I would love this. I actually use Presearch as my main search engine for over a year now.

**Comment by amplevine** [comment]
Presearch is an excellent choice. I've been using them for over 3 years and love the whole ethos of what they are about.

**Comment by hugomcconnell** [comment]
This would be a fantastic addition to metamask - please incorporate this!

**Comment by carrabre** [comment]
FYI - the comments are from this twitter post, not spam - https://twitter.com/presearchnews/status/1638424606162956288?s=20

**Comment by mad409** [comment]
> Presearch as a default search engine option would be super.

Sounds good, Presearch!

**Comment by carrabre** [comment]
Referencing this comment - https://github.com/MetaMask/metamask-mobile/issues/5150

**Comment by Geelbuik3421** [comment]
A must have for a Web3 product as MM.

**Comment by zonpower** [comment]
Excellent idea. I use Presearch for 91%+ of the time for my searches.

**Comment by carrabre** [comment]
Any updates?

**Comment by jejopl** [comment]
@estebanmino @rickycodes @gantunesr

**Comment by tuhinsharma121** [comment]
lets merge it!

**Comment by mohanaugust** [comment]
> lets merge it!

How to ?? PR is closed.

**Pull request closed without merging**
