### PR TITLE
refactor(ramp): use statusDescription in order details

### PR DESCRIPTION
**Pull request by wachunei**
> [!NOTE]  
> This PR points to https://github.com/MetaMask/metamask-mobile/pull/9008, the current PR will point to main once that PR is merged

## **Description**

This PR adopts a new property for the order details status description, this will deliver a description for every possible state.

## **Related issues**

Fixes: https://consensyssoftware.atlassian.net/browse/RAMPS-1408

## **Manual testing steps**

1. Go to any ramp order details
2. Pull to refresh, the description must be displayed

## **Screenshots/Recordings**

No visible changes

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by NicolasMassart — COMMENTED** [review]
Q: are these new texts visible by users? If yes, they should be translated, right?

**Comment by wachunei** [comment]
@NicolasMassart Yes they are visible to the users, unfortunately our Ramp API does not have a translation system yet, but it is coming.

**Review by NicolasMassart — APPROVED** [review]
Looks good to me.

**Comment by bkirb** [comment]
@wachunei LGTM for QA ✅

**Pull request merged**
