### PR TITLE
refactor: Update core controllers (v45)

### PR DESCRIPTION
**Pull request by Gudahtt**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

Update core controllers to match the v45 monorepo release. The network controller has been updated to v7, and the assets controllers have been updated to v5.1.0.

The phishing controller and message manager updates have been held back to reduce the scope of the PR. They will be updated in a later PR.

Release notes: https://github.com/MetaMask/core/releases/tag/v45.0.0

**Issue**

This relates to https://github.com/MetaMask/mobile-planning/issues/877

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

### CODE REVIEW

**Comment by Gudahtt** [comment]
This depends upon:
* https://github.com/MetaMask/metamask-mobile/pull/6872
* https://github.com/MetaMask/metamask-mobile/pull/6898

**Comment by Gudahtt** [comment]
This has been rebased onto #6898 .

Passing e2e test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/9577199b-c426-47ea-8371-7fbed7eb4a30

**Review by tommasini — CHANGES_REQUESTED** [review]
Amazing, very happy to see that we are pushing forward the version with phishing controller improvements, for that controller use less memory/bandwidth 

Notice here that we would need to change the addAsset of asset controller where it's used, because the structures of the arguments changed on this assets controller version from
`addToken(address, symbol, decimals, image, interactingAddress)`
to
`addToken(address, symbol, decimals, { name, image, interactingAddress })`

with this said we should change on the following places:
useAddressBalance.ts --> line 45
` TokensController.addToken(
          contractAddress,
          symbol,
          decimals,
          { image,
          name,}
        );`
        
UI/AddCustomToken.js --> line 120
`
TokensController.addToken(address, symbol, decimals, {name})
`

useHandleSuccessfullOrder.ts --> line 48
`TokensController.addToken(address, symbol, decimals, {name})`

SearchTokenAutocomplete --> line 110
`TokensController.addToken(address, symbol, decimals, {image: iconUrl, name})`

UI/Swaps --> line 531 
`TokensController.addToken(address, symbol, decimals,{ name})`

QuotesView --> line 351
`TokensController.addToken(address, symbol, decimals,{ name})`

SendFlow/Confirm --> lien 527
`TokensController.addToken(address, symbol, decimals, {image, name})`

**Comment by Gudahtt** [comment]
Thanks @tommasini . I think those requested changes have already been made (in https://github.com/MetaMask/metamask-mobile/pull/6898, which this PR is based on). Let me know if there are nay that were missed

**Review by tommasini — DISMISSED** [review]
Sorry, totally missed that dependency! Looks good to me!

**Comment by Gudahtt** [comment]
All blockers have been resolved, so this has been rebased onto `main`. Diff should be the same as before, when it was approved by @tommasini

**Review by Cal-L — APPROVED** [review]
code LGTM

**Review by cortisiko — APPROVED** [review]
🌮 🌮  🌮 🌮

**Pull request merged**
