### PR TITLE
switch to native event

### PR DESCRIPTION
**Pull request by witmicko**
Partial fix for [#697](https://github.com/MetaMask/mobile-planning/issues/697)

### CODE REVIEW

**Review by sethkfman — COMMENTED** [review]
LGTM. I would like @andrepimenta to confirm that removing `isMainFrame` as a check will not impact the backgroundBridges.

**Review by sethkfman — APPROVED** [review]
LGTM

**Comment by sethkfman** [comment]
@chrisleewilcox @cortisiko Do you think this ticket could be covered by E2E testing? You will have to drill into a few links to see the description.

**Comment by cortisiko** [comment]
@sethkfman at this moment in time, we don't have E2E coverage for the fix in the above ticket.

**Pull request merged**
