### PR TITLE
bugfix: instapay notifications amount

### LINKED ISSUE #935: Push notification for InstaPay is missing the amount

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

We weren't using locales for notifications correctly

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #935

### CODE REVIEW

**Review by brunobar79 — APPROVED** [review]
LGTM!

We should also change the copy of the message, saying that you received DAI instead of $ to be consistent with the rest of the feature.

**Comment by estebanmino** [comment]
@brunobar79 good call

updated

image

**Comment by ibrahimtaveras00** [comment]
Can't get instaPay notifications to work on iOS nor on Android (I am receiving normal send/receive push notifications) 

For instance: 
image

When I had the iOS app in the background and attempted to tap on it again I saw this (I was last on instaPay view) 

image

**Comment by estebanmino** [comment]
@ibrahimtaveras00 updated https://recordit.co/0ueEbRvxQd

**Review by ibrahimtaveras00 — APPROVED** [review]
Fixes look good, QA Passed 👍 

image

**Pull request merged**
