### PR TITLE
Update terms and privacy links

### LINKED ISSUE #2436: Update links to Privacy policy and Terms of Use
Replace the links: 
- metamask.io/terms to https://consensys.net/terms-of-use/ 
- metmask.io/privacy to https://consensys.net/privacy-policy/

These links appear within the 'Settings' > 'About'. 
Worth checking in the code if here's anywhere else where we link to Terms of Use and Privacy Policy.

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #2436

### CODE REVIEW

**Review by rickycodes — APPROVED** [review]
LGTM

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
When I tap here on wallet setup view, nothing happens 

image

nonetheless the same link on the import seedphrase works

**Comment by estebanmino** [comment]
@ibrahimtaveras00  this was included in https://github.com/MetaMask/metamask-mobile/pull/2176 but I just fixed it

**Review by ibrahimtaveras00 — APPROVED** [review]
This seems to work now on a fresh install = https://recordit.co/6kcrEtsDdg

However, it still doesn't work after you delete your wallet, and attempt to open terms and conditions on wallet setup view.  I opened another issue though since this is outside the scope of this PR, found here = https://github.com/MetaMask/metamask-mobile/issues/2462

**Pull request merged**
