### PR TITLE
Add CircleCI Badge

### PR DESCRIPTION
**Pull request by Zidail**
**Description**

Adds a CircleCI Badge to the README.md

Zidail_metamask-mobile_at_add-circleci-badge

**Note: Might require a token depending on CircleCI project settings, but for now, seems ok as the last test passed and the badge is also "passing".

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves none.

### CODE REVIEW

**Comment by brunobar79** [comment]
Thanks for the PR. Could you update it to specify the `develop` branch which is our default?

**Review by brunobar79 — CHANGES_REQUESTED** [review]
Thanks for the PR!  Could you update it to specify the develop branch which is our default?

**Comment by Zidail** [comment]
@brunobar79 Sure thing! Done!

**Review by brunobar79 — APPROVED** [review]
Thanks!

**Pull request merged**
