### PR TITLE
patch: (webview upgrade) Android filename validation when downloading from browser

### PR DESCRIPTION
**Pull request by jpcloureiro**
## **Description**

This change is part of the file react-native-webview+11.13.0.patch, a collection of patches that we need to apply on top of react-native-webview.

Original Pull Request:
[#6844](https://github.com/MetaMask/metamask-mobile/pull/6844)

Webview changes can be reviewed here:
[MetaMask/react-native-webview-mm#7](https://github.com/MetaMask/react-native-webview-mm/pull/7)

```
Scenario: Download file with invalid file name
  Navigate to websites using browser address bar.
    Given the app displayed the splash animation
    And I have imported my wallet
    And I tap No Thanks on the Enable security check screen
    And I tap No thanks on the onboarding welcome tutorial
    And I navigate to the browser
    And I have 1 browser tab displayed
    When I download a file with invalid filename
    Then an error message should appear
    And the file is not download
```

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/1649425/aa7d07a8-ab95-4f36-9325-bdcd6760dcd0

### **After**

https://github.com/MetaMask/metamask-mobile/assets/1649425/3e3fd1cf-5593-4afb-8045-4666cad494cd

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by tommasini — APPROVED** [review]
LGTM

**Comment by chrisleewilcox** [comment]
@jpcloureiro

- I am not able to download a file on android emulator, app is crashing
- This PR has failing audit issue


https://github.com/MetaMask/metamask-mobile/assets/6626407/69109194-7477-4ea2-a5cb-96f8aeace66f

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
Please review issues in previous comments.

**Comment by jpcloureiro** [comment]
@chrisleewilcox the "Extra Small file" button redirects to a non HTTPS URL. Our Android in-App browser rejects any request that is not HTTPS.

The same happens in prod, 7.17.1(1280)

For more context see https://github.com/MetaMask/metamask-mobile/issues/923#issuecomment-521334934

**Comment by chrisleewilcox** [comment]
Test pass: https://recordit.co/CPCG3iPeNS

**Review by chrisleewilcox — APPROVED** [review]
LGTM

**Pull request merged**
