### PR TITLE
fix: fix require misname of @metamask/react-native-button

### PR DESCRIPTION
**Pull request by legobeat**
## **Description**

- The package is now named `@metask/react-native-button`. This fixes the dependency field in the manifest as well as requires and patch accordingly.
  - chore: expand jest `transformIgnorePatterns` to cover new package name  

## **Related issues**

- Port of patch: https://github.com/MetaMask/react-native-button/pull/6
- Release package to remove need of patching our own as well as pulling in unreleased code: https://github.com/MetaMask/react-native-button/pull/5

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [ ] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by wachunei** [comment]
Should this include v3 and remove the patch as well?

**Review by wachunei — DISMISSED** [review]
LGTM

**Comment by Cal-L** [comment]
Could you provide some screenshots or vids showing that the button looks line/is working?

**Comment by Cal-L** [comment]
Confirmed working - 
image

**Comment by Cal-L** [comment]
started E2E smoke tests - https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/bf829352-ad45-4897-8be8-0a906a441e88

**Comment by Cal-L** [comment]
Looks good - 
image

**Comment by Cal-L** [comment]
Started e2e smoke - https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/c1c6a955-1dbb-42b9-a4d8-f0236e02dff5

**Review by wachunei — APPROVED** [review]

**Review by leotm — APPROVED** [review]

**Pull request merged**
