### PR TITLE
Fix NFT transfer with big token id

### PR DESCRIPTION
**Pull request by wdv4758h**
**Description**

Current implementation does not work with big token id. This will cause NFT transfer failure, since the id will be converted to something not correct.

For example:
```javascript
> // the hex is 0x159ffe6f22fd5cc42c524df6fd5e28d0de38f34e
> // and this big number is 
> decimal = '123456789012345678901234567890123456789012345678'

> // original implementation
> parseInt(decimal).toString(16)
'159ffe6f22fd5d00000000000000000000000000'

> // new implementation
> toBigNumber.dec(decimal).toString(16)
'159ffe6f22fd5cc42c524df6fd5e28d0de38f34e'
```

This PR simply change the conversion to use BigNumber, which is already in the codebase.

**Screenshots/Recordings**

**Issue**

Hex string conversion failure cause NFT transfer failure.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by wdv4758h** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gantunesr** [comment]
Thanks for the contribution @wdv4758h, do you mind adding some basic tests cases to verify that this issue is fixed

**Comment by wdv4758h** [comment]
Test for big number is added.
Here is the screenshot of test failure **before** the patch:
without-patch
The test will pass after the patch.

**Comment by gantunesr** [comment]
Thanks @wdv4758h. The PR LGTM, I'll move forward for our QA team to test it. They'll point out in this PR any issues they find.

**Review by gantunesr — COMMENTED** [review]
LGTM

**Comment by gantunesr** [comment]
@wdv4758h I see linting error in the code, can you fix it please

```
/home/runner/work/metamask-mobile/metamask-mobile/app/util/number/index.test.ts
Error:   4[8](https://github.com/MetaMask/metamask-mobile/runs/7463846736?check_suite_focus=true#step:5:9)3:12  

error  Replace `toHexadecimal('12345678[9](https://github.com/MetaMask/metamask-mobile/runs/7463846736?check_suite_focus=true#step:5:10)0[12](https://github.com/MetaMask/metamask-mobile/runs/7463846736?check_suite_focus=true#step:5:13)345678901234567890123456789012345678')` with `⏎······toHexadecimal('123456789012345678901234567890123456789012345678'),⏎····`  prettier/prettier

✖ 2 problems (1 error, 1 warning)
```

**Comment by wdv4758h** [comment]
@gantunesr done, the `yarn lint:fix` is applied.

**Comment by Fatxx** [comment]
Hey @wdv4758h!

Thank you very much for your contribution.

I was testing the issue https://github.com/metamask/metamask-mobile/issues/4092 and I can confirm that these changes solve the problem reported.

Please check the following:

Current bug: 

https://user-images.githubusercontent.com/575479/181347737-3586520d-ffce-4d04-8c1e-58c9bdc04104.mp4

Fix running the same flow on this PR:

- https://recordit.co/0dBeC4XSs6
- Transaction: https://etherscan.io/tx/0x9e3e650cb8310a1f7278d16d81328207e31b55cc867f297f64237337cf874e35

**Review by cortisiko — APPROVED** [review]
I have tested on polygon, BSC and main net:  swaps, sending ERC-721's, Sending ENS ERC-721's, sending ERC-20's and native currencies 

this is 🌮  🌮  🌮  🌮

**Pull request merged**
