### PR TITLE
fix issues 2100

### LINKED ISSUE #2652: Storage Limit Issue
Please find the previous closed thread. It is still an ongoing issue : https://github.com/MetaMask/metamask-mobile/issues/2100

Storage limit issue
1. When opening the metamask app I can't login because I'm asked to enter my password then it says storage space full. My device has available storage. 

2. Over the past month or more sometimes when I try to login with my faceid Metamask asks for my password, then displays a error message about storage being corrupt. After deleting the app and restoring the seed phrase all works again for a while, then it randomly stops working again. I have had to delete the app and reinstall over 5 times already. 

FB15D3E4-7B94-4710-A884-FF7AC7C620BF

Previous issue happened on Android, my issue happening on iOS
* Device: iPhone iOS 14.5.1
* App Version - 2.2.0
Acceptance Criteria:
1. User shouldn't ever be locked out of their wallet
2. The new storage solution musn't compromise on security of user data

### PR DESCRIPTION
**Pull request by 0xGaryWu**
/**
	 * fix bug: https://github.com/MetaMask/metamask-mobile/issues/2100
	 * 
	 * reason: redux-persist load storage data by 'getItem' API with a timeout (5 seconds default) when app ’cold start',
	 * on some old devices, I/O is slow and 'readfile' operation may take long time Occasionally, when this happened, timeout
	 * will lead to redux-persist rehydrate state with undefined and an Error(https://github.com/rt2zz/redux-persist/blob/master/src/persistReducer.js#89).
	 * 
	 * solution: the easy way to fix is to set a big timeout on config, Go further, we could save 'keyring' etc some important
	 * data to separate files or backup for this. the second way is not complicated, we could set
	 * serialize and deserialize to false to get JSON object and modify setItem/getItem API to save/load data.
	 */

### CODE REVIEW

**Comment by sethkfman** [comment]
@liangwu Thank you for the submission. We are reviewing and testing your suggestion for extending the timeout beyond the default settings.

**Comment by liangwu** [comment]
> @liangwu Thank you for the submission. We are reviewing and testing your suggestion for extending the timeout beyond the default settings.

thanks, I can reproduce this bug on my oneplus(2/10), you could reproduce it if add more delays in function getItem before return. 

I found this, because I received an error ( redux-persist: persist timed out below) when state rehydrate.
https://github.com/rt2zz/redux-persist/blob/master/src/persistReducer.js#L89-L100

`      timeout &&
        setTimeout(() => {
          !_sealed &&
            _rehydrate(
              undefined,
              new Error(
                `redux-persist: persist timed out for persist key "${
                  config.key
                }"`
              )
            )
        }, timeout)`

**Review by rickycodes — APPROVED** [review]
lgtm

**Review by sethkfman — APPROVED** [review]
This looks good. Thank you for the contribution!

**Pull request merged**
