### PR TITLE
fix: update sepolia nickname

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Update `Sepolia Test Network` to `Sepolia`.
Update `Linea Sepolia test Network` to `Linea Sepolia`.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go Settings => Networks
2.You should see Sepolia instead of Sepolia Test Network and Linea Sepolia instead of Linea Sepolia Test Network

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/10994169/7f5232be-f946-4614-a94d-ac7a08ba00b4

### **After**

https://github.com/MetaMask/metamask-mobile/assets/10994169/c68fc8b6-63be-442e-86fb-e445cf302b63

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by seaona** [comment]
:information_source: it looks like this PR will fix the Networks name miss-match identified here

https://github.com/MetaMask/metamask-extension/issues/24043

**Comment by sahar-fehri** [comment]
> @sahar-fehri is this same solution planned for Extension? It looks like this change can fix the Networks name miss-match identified [here](https://github.com/MetaMask/metamask-extension/issues/24043)

Hey @seaona thnx for mentioning this, i saw that on extension we are displaying correctly "Sepolia" in the network list switcher but when you try to sign it displays "Sepolia test network" , will look into this 🙏

**Review by Cal-L — COMMENTED** [review]
Do we need a migration if Sepolia Test Network or Linea Sepolia Test Network was previously added as networks?

**Comment by sahar-fehri** [comment]
> Do we need a migration if Sepolia Test Network or Linea Sepolia Test Network was previously added as networks?

Hey @Cal-L ! I dnt think its necessary. The `networkControllerState`, and it looks like the following

`{"networkConfigurations": {}, "networksMetadata": {"mainnet": {"EIPS": [Object], "status": "available"}, "sepolia": {"EIPS": [Object], "status": "available"}}, "providerConfig": {"chainId": "0xaa36a7", "rpcPrefs": {"blockExplorerUrl": "https://sepolia.etherscan.io"}, "ticker": "SepoliaETH", "type": "sepolia"}, "selectedNetworkClientId": "sepolia"}`

No need to update the nickname, same goes for the Base [PR](https://github.com/MetaMask/metamask-mobile/pull/9682) 🙏

**Review by pedronfigueiredo — APPROVED** [review]

**Pull request merged**
