### PR TITLE
fix: hot fix for ledger account select screen to provide disclaimer copy information.

### PR DESCRIPTION
**Pull request by dawnseeker8**
## **Description**

This PR will be hot fix for 7.28.1 to provide disclaimer copy information in ledger account select screen to notify user that current MM mobile ledger use BIP44 derivation path.

## **Related issues**

Fixes:

## **Manual testing steps**

1. go to import hardware wallet
2. Select Ledger
3. you should see the disclaimer copy information there.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by vivek-consensys** [comment]
Tested on iOS 17.6.1 and Android 14, disclaimer text displayed as expected. 


https://github.com/user-attachments/assets/a8f975d3-e916-4bc7-b49d-f58821fcf7da

IMG_0136

**Review by Daniel-Cross — APPROVED** [review]
Looks good!

**Comment by dawnseeker8** [comment]
@metamaskbot update-attributions

**Review by Daniel-Cross — CHANGES_REQUESTED** [review]
Some issues with the `attribution.txt` file that need addressing.

**Review by Daniel-Cross — APPROVED** [review]
Looks good to me!

**Comment by sethkfman** [comment]
SonarCloud not needed for temporary string change.

**Pull request merged**
