### PR TITLE
Updating Swaps backend controls

### PR DESCRIPTION
**Pull request by nikoferro**
**Description**

Adding additional platform specific backend controls to swaps.

**Issue**

See MMS-307

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [x] Any added code is fully documented

Documentation for this change was added on swaps-api

### CODE REVIEW

**Comment by sethkfman** [comment]
@nikoferro Is this feature flag coming from server metadata?

**Comment by nikoferro** [comment]
@sethkfman yes exactly, we are updating the feature flags for mobile on the backend and this change is related to those updates

**Review by sethkfman — APPROVED** [review]
LGTM

**Comment by sethkfman** [comment]
@nikoferro Do you have permission to merge this ticket into the repo?

**Pull request merged**
