### PR TITLE
fix: App slower when changing account and switching network

### LINKED ISSUE #9250: [Bug]: app very slow and sluggish when switching accounts especially on android device
### Describe the bug

When switching accounts on wallet view the app is very slow and sluggish to finish switching accounts.

Wallet setup:
- 3 wallet accounts
- 1 imported account
- 1 imported ENS account (notice that ENS accounts in the wallet seem to contribute to slowness)
- 2 hw accounts

Physical device: 
- Samsung A42 Android 13
- iPhone 12 iOS 17.4

### Expected behavior

Switching accounts should be very responsive in the app without noticeable delays.

### Screenshots/Recordings

Uploading Screen Recording 2024-04-15 at 12.43.42 PM.mov…

### Steps to reproduce

GIVEN I am on wallet view
WHEN I tap account drop-down (randomly very slow to display select account modal)
AND I tap account to select (randomly very slow to switch to accounts and select account modal goes away)
THEN wallet view is displayed (randomly wallet view is shaded before for awhile before I can tap or interact)
AND I can immediately tap or interact with wallet view (randomly very slow when I tap a component on wallet view)

### Error messages or log output

_No response_

### Version

7.21.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by tommasini**
## **Description**
This PR reduces the number of api calls that happen when switching account and network, on cold and warm app starts.

* Transactions are being fetched for all the accounts instead of just the selected one, that was fixed by adding a patch to the TransactionController to only fetch per account selected (36 fetches to eth_getTransactionReceipt and counted 40+ eth_getBlockByHash, to 0 since when we are switching network on an account that doesn't have transactions)
Screenshot of main branch with eth_getTransactionReceipt requests:
The selected account was not orangefox.eth
https://etherscan.io/tx/0x7ce730e2e87520e179d4e351e5cfe80565c346f9ab7688a3391306422e01f0a9

* Fixed a bug on Transaction controller where the getBlockByHash request was failing silently because it was missing one param.

* ~~ENS fetches now only once we switch network and we change the selected account (This was looping by number of accounts and being retriggered, one 1 second, counted 15+ fetches to [ens contract](https://etherscan.io/address/0xa2c122be93b0074270ebee7f6b7292c7deb45047) , now it's just fetching once it switches network and for the selected account)~~
* Request parallelization of token balances. (This was not optimized on number of requests but on the parallelization of the requests to have a response quicker from all of them)
* Update pooling of token balances from 10000 to 180000 miliseconds
* Added a boolean to not let the updateBalances runs if there is an update in progress. (Probably change this to use mutex when implementing on core it's a good idea)

A snapshot was updated on this PR! It seems that this snapshot was indeed wrong, and now it have the right mocked data.

Check this transaction controller core branch with the changes: mobile-patch-performance-tx-controller-13-0-0
(Once this is approved, this changes need to be merged on the patch/mobile-transaction-controller-13-0-0 branch)

Assets controller patch easy to ready, the core branch is this one: patch/mobile-assets-controllers-26-performance.
(Once this is approved, this changes need to be merged on the patch/mobile-assets-controllers-26 branch)

**Next steps**

* Postpone transactions requests to views that will show transactions (exg: Asset View, Activity View)

**Product Changes**
* ~~ENS is now get by the selected account and not every account~~ This was addressed in other PR already
* Transactions status is now updated only on the selected account (This still decrease the number of requests if the user has multiple accounts with multiple transactions)

## **Related issues**

Fixes: #9250 #9249 

## **Manual testing steps**

1. 
2.
3.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by sethkfman** [comment]
@tommasini Can you quantify the number of API calls you have reduced by this change? Is it possible that we will see improvements on UI load performance in the Wallet View?

**Comment by tommasini** [comment]
Yeah I didn't take screenshots but we can do a comparison with the main branch using flipper @sethkfman

**Review by Cal-L — APPROVED** [review]
LGTM! Are these changes also applied to core already?

**Comment by tommasini** [comment]
On the transaction controller changes, the way that transaction statuses are being fetched really change on next versions, so there was not a follow-up to core, althought this will be saved on a core branch to help next upgrades (The core branch is: patch/mobile-transaction-controller-13-0-0)

Regarding the assets controllers, this should be redirected to the core repo! I believe since now the focus is the controller upgrades, we can do it when we update assets-controllers to the latest version, begin to remove all the patch with core PRs
The work is saved on this branch: patch/mobile-assets-controllers-26

**Review by vinistevam — APPROVED** [review]

**Pull request merged**
