### PR TITLE
fix: Duplicate key in Settings and Privacy

### PR DESCRIPTION
**Pull request by gambinish**
## **Description**

```
ERROR  Warning: Encountered two children with the same key, `0x89`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
 ```

## **Related issues**

Fixes: No issue, found while developing

## **Manual testing steps**

1. Add Polygon, and add a custom RPC Polygon
2. Go to Network Settings
3. Should not see duplicate key error in logs

## **Screenshots/Recordings**

N/A

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by tommasini — DISMISSED** [review]
LGTM! I believe this will change by Network Controller upgrade!

**Review by vinnyhoward — DISMISSED** [review]

**Review by andreahaku — DISMISSED** [review]
LGTM

**Review by NicolasMassart — COMMENTED** [review]
should [line 712](https://github.com/MetaMask/metamask-mobile/pull/11664/files#diff-2b913eb31628daca1d527bfece703633980e523a67b95426b1a331959e899a05R712) also be fixed?

**Review by sahar-fehri — DISMISSED** [review]

**Review by NicolasMassart — DISMISSED** [review]
Looks good to me. Thanks!

**Review by vinnyhoward — APPROVED** [review]

**Pull request merged**
