### PR TITLE
@ethereumjs/tx-regression-test

### PR DESCRIPTION
**Pull request by rickycodes**
this is for @ibrahimtaveras00 to test the changes from https://github.com/MetaMask/controllers/pull/489

### CODE REVIEW

**Comment by rickycodes** [comment]
functionality to be tested in regression:

- send/approve transaction
- cancel a transaction
- speed up a transaction

**Comment by rickycodes** [comment]
we should also test dapp functionality as well.

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
**Issue 1:**

Unable to speed up the following txn's on mainnet:
- normal send flow for both ETH and ERC20 token
- Dapp txn (confirm/approve)

Issue = intrinsic gas too low

seen here = https://recordit.co/4iOyvNVcCY

**Review by ibrahimtaveras00 — APPROVED** [review]
QA Passed 👍🏽

**Comment by rickycodes** [comment]
closing this now that https://github.com/MetaMask/controllers/pull/489 is merged thanks leyenda!

**Pull request closed without merging**
