### PR TITLE
fix: Move permission middleware to be later than rpc method middleware

### LINKED ISSUE #9443: [Bug] Browser: not able to connect to opensea using MetaMask with in-app browser on android device
Expected: Wallet can connect to opensea.io with MetaMask option without creating a new browser tab or being asked to sign into Google Play. Just connected to opensea like how it's working with iOS devices.

Actual: A message will constantly appear when tapping the metamask option to connect. In some occasions,  making it hard close the tab and to open a new one in the browser. 

Samsung Galaxy s21 ultra Android 13:
Prod v7.20.1

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUdmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b03c56cd9482650e476a49868c7e16223e0a68e8/Screen_Recording_20240426_215941_MetaMask.mp4)

Release 7.22

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVNmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2807f8ec9b7c826baa2ca5cea31e0a7be05a7aa/Screen_Recording_20240426_210605_MetaMask.mp4)

### PR DESCRIPTION
**Pull request by Cal-L**
## **Description**

~~This PR adds `eth_accounts` to the unrestricted methods list that is used by the permission system as a temporary workaround to fix the broken deeplink behavior when connecting to OpenSea. The breaking change happened when we introduced the permission middleware - https://github.com/MetaMask/metamask-mobile/pull/9521, which resulted in `eth_accounts` being handled by the permission middleware instead of RPCMethodMiddleware. Before the PS middleware was introduced, an unauthorized RPC error was caught and MetaMask would return an empty array. After the PS middleware was introduced, MetaMask would throw the error instead. Our suspicion is that OpenSea changes the connect button behavior to deeplink whenever `eth_accounts` encounters an error.  By adding `eth_accounts` method to the unrestricted list, the method skip the PS middleware and be handled by RPCMethodMiddleware, which preserves the old behavior.~~

Update: The general sentiment is to follow extension's implementation for now to preserve the correct behavior and to remove the need to manage eth_accounts in the unrestricted list. The change moves permission middleware to be later than rpc method middleware

## **Related issues**

fixes #9443 
fixes MetaMask/mobile-planning#1796

## **Manual testing steps**

1. Open OpenSea.io in the MetaMask in-app browser
2. Tap connect
3. Notice that the permissions flow will appear instead of being redirected to the app store

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/10508597/56bd2b4d-d6a7-4fca-a9b8-be1fee27da18

### **After**

https://github.com/MetaMask/metamask-mobile/assets/10508597/631b2f78-6b8a-45c9-a744-609b4ad51733

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [X] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [X] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by tommasini — DISMISSED** [review]
LGTM! We had this json rpc method handled by the json rpc middleware until now as you mention on the description!

**Review by kumavis — DISMISSED** [review]
as I understand it, this would expose addresses to all websites without approval of the user. if this is correct, I find it an unacceptable privacy issue even if temporary

**Comment by naugtur** [comment]
Silent failure or empty result are acceptable. Returning the correct value without permission is not. 
@Cal-L It's not clear to me from the testcase if the result is undefined because there's nothing to return or it's a silent failure. Please expand the tests to show actual addresses being returned for an authorized request and an empty result for an unauthorized one.

cc @leotm

**Comment by tommasini** [comment]
I don't think this is causing a privacy issue because at the RPCMethodMiddleware file, where we handle the [eth_accounts](https://github.com/MetaMask/metamask-mobile/blob/e7d980e1ab443665fc095e5f88d93dda123e3f73/app/core/RPCMethods/RPCMethodMiddleware.ts#L497) rpc method, we call  [getPermittedAccounts](https://github.com/MetaMask/metamask-mobile/blob/e7d980e1ab443665fc095e5f88d93dda123e3f73/app/core/RPCMethods/RPCMethodMiddleware.ts#L301) , which [awaits](https://github.com/MetaMask/metamask-mobile/blob/e7d980e1ab443665fc095e5f88d93dda123e3f73/app/core/Permissions/index.ts#L175) the permission controller [executeRestrictedMethod](https://github.com/MetaMask/core/blob/a794c31f15bacb9d893fe56f15a84e35a21c426b/packages/permission-controller/src/PermissionController.ts#L2322) that returns an error if the user is not connected to the dapp


https://github.com/MetaMask/metamask-mobile/assets/46944231/d6545aa8-077b-461f-80cc-df756bf04d81

**Comment by tommasini** [comment]
>  It's not clear to me from the testcase if the result is undefined because there's nothing to return or it's a silent failure

We checked the test and it seems the [mock](https://github.com/MetaMask/metamask-mobile/blob/c0c3b8e4901cc82becbcea4e07facf60e5ebcbec/app/core/RPCMethods/RPCMethodMiddleware.test.ts#L258) of `getPermittedAccounts` took us to a wrong behaviour (a response with a result undefined instead of an permission error), because `getPermittedAccounts` mock doesn't have an error as a response. 

I would say next steps is to work on the unit tests to mock the `getPermittedAccounts` behaviour as it is, since it's just mocking the possible accounts by hostname [here](https://github.com/MetaMask/metamask-mobile/blob/c0c3b8e4901cc82becbcea4e07facf60e5ebcbec/app/core/RPCMethods/RPCMethodMiddleware.test.ts#L258)

**Comment by Cal-L** [comment]
> as I understand it, this would expose addresses to all websites without approval of the user. if this is correct, I find it an unacceptable privacy issue even if temporary

@kumavis This wouldn't be exposing addresses without user approval since `eth_accounts` on the rpc method middleware level uses permission controller under the hood. To preserve existing API behavior, an authorized error from the permission controller will result in the dapp receiving an empty array.

**Review by tommasini — APPROVED** [review]
LGTM! 
Based on the changed this doesn't look to have any privacy concerns
Will defer to you @naugtur for one last look

**Review by leotm — APPROVED** [review]
lgtm ^
- PermissionController middleware now added after RPCMethodMiddleware like metamask-extension
- eth_accounts addresses not managed/exposed in unrestricted list w/o approval
- empty array correctly returned, instead of throwing error (causing deeplink store redirect)
- tests remain intact

**Pull request merged**
