### PR TITLE
refactor: Update core controllers (v47)

### PR DESCRIPTION
**Pull request by Gudahtt**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add the appropiate QA label when dev review is completed
    - `needs-qa`: PR requires manual QA.
    - `No QA/E2E only`: PR does not require any manual QA effort. Prior to merging, ensure that you have successful end-to-end test runs in Bitrise. 
    - `Spot check on release build`: PR does not require feature QA but needs non-automated verification. In the description section, provide test scenarios. Add screenshots, and or recordings of what was tested.
5. Add `QA Passed` label when QA has signed off (Only required if the PR was labeled with `needs-qa`)
6. Add your team's label, i.e. label starting with `team-` (or `external-contributor` label if your not a MetaMask employee)

**Description**

The package `@metamask/assets-controllers` has been updated to v6, which brings core packages up-to-date with v47 of the core monorepo.

**Issue**

This closes https://github.com/MetaMask/mobile-planning/issues/877

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

### CODE REVIEW

**Comment by Gudahtt** [comment]
This depends upon #6902

**Comment by Gudahtt** [comment]
This has been rebased onto #6902

Passing e2e test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/5e6851f8-0d0f-40c2-8c13-655ee997779b

**Review by tommasini — COMMENTED** [review]
~~Since `setProviderType` is now async,  should we create an issue to change the codebase? 
Since this controller update only changes the assets-controllers version, I don't know if it would be okay to do it here.~~

~~Let me know what do you think~~

I'm a little bit confused, the `setProviderType` on the change log of version 47 is turned to async, but on the change log of the network controller it's just on version 8.0.0. I believe this will not crash anything, but just checking if we should update the network controllers to 8.0.0 to do this update on assets-controllers.

**Comment by Gudahtt** [comment]
Thanks for looking into that @tommasini . I hadn't noticed that entry before. It looks like it's invalid.

The linked PR is indeed for the network controller - the only impact it had on assets-controllers was in a test. That network controller change wasn't even included in that release - it was in v48, the release after this one. So that entry is invalid for two different reasons. I'll update it now.

**Comment by Gudahtt** [comment]
This was the only functional change for assets-controllers in that release: https://github.com/MetaMask/core/pull/1166/

**Review by tommasini — DISMISSED** [review]
Thanks for the explanation and for looking into that!!
Looks good to me 🚀

**Comment by Gudahtt** [comment]
The blockers have been merged, so this has been rebased onto `main`

**Comment by cortisiko** [comment]
Hey @Gudahtt, testing is still ongoing. I did however notice a bug. 

After importing a wallet, I notice my transaction history is not displayed. See the recording here: http://recordit.co/Wsn77E1xy2 

Compared to prod v7.5: http://recordit.co/02UDZRtvci 


To reproduce:
Import a wallet with transaction history on mainnet 
when you get to the wallet view go to the transaction history view
notice previous transactions do not appear

**Review by cortisiko — APPROVED** [review]
Looks good. ✅

**Comment by Gudahtt** [comment]
For further context on the bug referenced a few comments back: we later discovered that it was introduced by #6998 and is being addressed in #7042

**Pull request merged**
