### PR TITLE
feat(ramp): add event when user expands quotes

### PR DESCRIPTION
**Pull request by wachunei**
> [!NOTE]
> This PR is based on https://github.com/MetaMask/metamask-mobile/pull/8680 

## **Description**

This PR adds an event when the user expands the quotes to explore more options in the simplified view

## **Related issues**

https://consensyssoftware.atlassian.net/browse/ONRAMP-1407

## **Manual testing steps**

1. Go through a buy or sell flow
2. After receiving quotes, tapping on the Explore more options link if available must trigger a new event.

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by wachunei** [comment]
Leaving this as a draft until the event properties are reviewed. Can you please take a look @lorenzosantos?

**Review by Cal-L — DISMISSED** [review]
Lgtm

**Comment by bkirb** [comment]
LGTM, I verified the event appeared in logs with Pedro ✅

**Comment by wachunei** [comment]
@Cal-L can you please re-review, this has just changed the base branch 🙏

**Review by Cal-L — APPROVED** [review]
LGTM

**Pull request merged**
