### PR TITLE
E2E Establish performance baseline

### PR DESCRIPTION
**Pull request by cortisiko**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

The purpose of this PR is to establish a baseline for the performance E2E tests. This will be the first of many performance tests that will run on a nightly basis. You can read up more on the proposed approach for the performance tests [here](https://docs.google.com/document/d/1yTMIeCe2E6JDece4g-XoABfDJsOgAJd3qoBq1Ca6JyE/edit).

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by NicolasMassart — COMMENTED** [review]
Comment: Maybe you could add a tag like `@performances` or something on this scenario? This would probably help clarify the purpose of the test and eventually allow to run all perf tests using the tag.

**Comment by cortisiko** [comment]
@NicolasMassart very valid point. I went ahead and added the appropriate tag and moved the test into a new folder called "Performance"

**Review by NicolasMassart — COMMENTED** [review]
Good clarifications!

**Review by SamuelSalas — APPROVED** [review]

**Review by sethkfman — APPROVED** [review]
LGTM

**Pull request merged**
