### PR TITLE
chore: bump Node to v16.20

### PR DESCRIPTION
**Pull request by gantunesr**

### CODE REVIEW

**Comment by gantunesr** [comment]
Executing E2E in [here](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/df8b82d2-4273-45cb-ad71-80c944860a0c).

**Comment by gantunesr** [comment]
Executing E2E in [here](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/19a8f4f2-3e19-4e4e-b0b5-cb1f261dfbf4).

**Comment by gantunesr** [comment]
[E2E Successful](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/adc9688b-93d2-4475-be49-546e1f270575)

**Comment by gantunesr** [comment]
[Successful QA builds](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/efe46f92-37c5-46d0-9601-645660ffde05)

**Review by sethkfman — APPROVED** [review]
LGTM

**Pull request merged**
