### PR TITLE
feat(ramp): add getStarted flag for sell

### PR DESCRIPTION
**Pull request by wachunei**
## **Description**
This PR adds the local state for the Get Started view in the sell flow: a boolean that will determine to show this view for every new Sell user.

## **Manual testing steps**
1. Open the Sell flow
2. The Get Started onboarding view must render
3. Click on the CTA "Get Started" and close the Sell flow
4. Opening the Sell flow again must not show the Get Started onboarding anymore

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by bkirb** [comment]
@wachunei LGTM I verified the get started flow ✅

**Review by georgeweiler — APPROVED** [review]

**Review by NicolasMassart — COMMENTED** [review]
what's "AGG" ?

**Comment by wachunei** [comment]
@NicolasMassart AGG is "aggregator", this was introduced because before the on-ramp feature we had direct integration to each of the providers without aggregating.

**Review by Cal-L — COMMENTED** [review]
LGTM

**Pull request merged**
