### PR TITLE
Bugfix/speedup transactions

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

The validation method was wrong. I also moved it to an method in utils.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

### CODE REVIEW

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Speeding up and canceling work fine on regular send flow 👍 

**Issue 1:**

I did a token swap on uniswap, however, when I tapped on the speed up button nothing happened and I got the following warning:

{"code": -32000, "message": "insufficient funds for gas * price + value"}

Seen here = https://recordit.co/DCyD54MJTm

Screen Shot 2020-07-09 at 9 58 20 PM

**Issue 2:**

I believe the button's color should be updated to primary-blue

**Review by andrepimenta — APPROVED** [review]
LGTM! 👍

**Comment by estebanmino** [comment]
added a change for that issue on https://github.com/MetaMask/controllers/pull/249

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Only remaining issue is the color of the speed up and cancel CTA when tapping on the notification to bring up the txn history modal, then tapping on either speed up or cancel 

Screen Shot 2020-07-16 at 12 24 27 PM

Screen Shot 2020-07-16 at 12 27 40 PM

**Review by ibrahimtaveras00 — APPROVED** [review]
Fix looks good, QA Passed 👍

**Pull request merged**
