### PR TITLE
Fix send transactions sometimes showing balance undefined and infinite loaders with ERC20 tokens

### PR DESCRIPTION
**Pull request by EtDu**
Title speaks for itself. 
From https://consensys.zendesk.com/agent/tickets/53150
Screenshot_20200902-140225641

### CODE REVIEW

**Comment by EtDu** [comment]
@ibrahimtaveras00 To reproduce consistently for QA:
1) Scan a receive QR code
2) Click edit in top left corner
3) change asset to an ERC-20 tokens
4) change the amount and press Next

**Comment by rdymac** [comment]
Other cases that might be affected by this issue: 53379, 51793

**Review by rickycodes — APPROVED** [review]

**Review by ibrahimtaveras00 — APPROVED** [review]
This works for the steps to reproduce how @EtDu described 👍 

However, I don't think this fix will work for the other issue @rdymac described = 53150 as I couldn't withdraw from our test-dapp
seen here = https://recordit.co/kpV304DD5Y

Screen Shot 2020-09-25 at 5 47 18 PM

But I believe that is out of the scope of what this PR actually fixes so I will at least pass this PR

**Comment by EtDu** [comment]
@ibrahimtaveras00 The problem you found here isn't only with mobile, it occurs on the extension as well. It's a bug having to do with the way gas estimation works. I do feel we could do better at displaying the error message to the user instead of doing nothing though

**Comment by omnat** [comment]
New support issue came up 57946 (trying to send sxp), looks like this is still happening. 
@EtDu @ibrahimtaveras00

**Comment by EtDu** [comment]
#1889 updated fix!

**Pull request merged**
