### PR TITLE
Fix day and month numbers in toDateFormat

### PR DESCRIPTION
**Pull request by danjm**
Before:

Screenshot from 2020-05-11 13-01-41

After:

Screenshot from 2020-05-11 13-11-10

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
😅

**Comment by ibrahimtaveras00** [comment]
I noticed we are no longer showing the year, is that intentional? 

image

CC: @cjeria

**Comment by cjeria** [comment]
I've made some observations regarding dates between extension and mobile.

- In extension -  In the new TX history list, they are not showing dates at all, only within the tx detail view is the date visible.  Only **Month**, **day**, and **time**, no year (see screenshot below).

- In mobile - We only show **Month**, **day** and **time** (no year) in both the TX history list and detail view. This is in my current build of mobile v0.2.15.

The straightforward direction is to add the year in mobile in both the tx history list and in the tx detail. Alternatively, we could follow the extension's pattern and remove the nonce + date from the tx history list but I'd add the year in the detail view. 

e.g. Jan 6, 2020 at 1:57pm

cc @omnat WDYT?

image

**Comment by cjeria** [comment]
I've made some observations regarding dates between extension and mobile.

- In extension -  In the new TX history list, they only show dates (**month + day**) when a tx has been successfully processed.  And only **Month**, **day**, and **time**, no year in the detail view (see screenshot below).

- In mobile - We only show **Month**, **day** and **time** (no year) in both the TX history list and detail view. This is in my current build of mobile v0.2.15.

The easier direction is to add the year in mobile in both the tx history list and in the tx detail. Alternatively, we could follow the extension's pattern and remove the nonce and only show **Month**, **day**  from the tx history list but I'd suggest adding the year in the detail view. 

e.g. Jan 6, 2020 at 1:57pm

cc @omnat WDYT?

image

**Review by ibrahimtaveras00 — APPROVED** [review]
Looks good on both OS's, QA Passed 👍

**Pull request merged**
