### PR TITLE
Initial iPad adjustments

### LINKED ISSUE #3488: Adding iPad Support
**Describe the usability problem**
When using the MetaMask app on an iPad, the app doesn't fill the entire screen - it's a "streched" iPhone app. This is affecting the user experience of iPad users and I've seen other people on Reddit ([#1](https://www.reddit.com/r/Metamask/comments/oja4c6/suggestion_for_devs_ios_ipad_app_support/), [#2](https://www.reddit.com/r/Metamask/comments/o1wqtv/ipad_app/)) requesting the same change. Please, implement this whenever possible. I really like using MetaMask and this is the only UX breaking issue I'm currently having with the app, and I would be very happy if this gets implemented.

**Expected behavior**
The app should fill the entire screen.

**Technical Details**
I get that this might not be something of top priority, however the changes needed to add iPad support are very minimal and the user experience for all iPad users will drastically improve. The app layout already supports dynamic screen sizes, it's just that iPad support is _disabled_. 
In the project settings of the iOS project, under _Deployment Info_, the iPad checkmark should be set to true like so:

settings

When this is done, the app starts to fill the entire screen and it **looks pretty good** IMO. Here are some iPad Pro 12.9" Simulator Screenshots I've taken to prove my point. No other changes are applied except applying the iPad checkmark mentioned above.

**Screenshots**
| Before | After |
| ------ | ----- |
|home-portrait-before|home-portrait-after|
|menu-portrait|menu-portrait-after|
|popup-portrait|popup-portrait-after|
|browser-portrait|browser-portrait-after|

P.S: Landscape support for iPad would also be nice, but I totally understand that it's out of scope of this issue and would require a bit more work than adding iPad support.

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

### PR DESCRIPTION
**Pull request by wachunei**
**Description**

This PR attempts to add iPad support minimizing changes and adjusting UI issues only.

**Issue**

Resolves #3488

### CODE REVIEW

**Comment by chrisleewilcox** [comment]
Please address check failures and branch conflicts.

**Comment by wachunei** [comment]
This became very stale, switching back to draft until I revisit and rebuild it.

**Comment by sethkfman** [comment]
@wachunei this PR seems very out of date. Please update and reach out for a PR review. Thx

**Comment by wachunei** [comment]
A new PR has been opened https://github.com/MetaMask/metamask-mobile/pull/5312

**Pull request closed without merging**
