### PR TITLE
fix: CI flakey unit tests TypeErrors on react-native/jest/setup.js global.performance

### LINKED ISSUE #8051: Flakey CI unit tests
### What is this about?

Occurring recently in CI on a mixture of our unit test shards

### Scenario

_No response_

### Design

_No response_

### Technical Details

_No response_

### Threat Modeling Framework

_No response_

### Acceptance Criteria

CI passing consistently

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

- https://github.com/facebook/react-native/issues/35701
- https://consensys.slack.com/archives/C02U025CVU4/p1701901498852149

### PR DESCRIPTION
**Pull request by leotm**
## **Description**

Fix recent CI flakey failing unit tests:
`TypeError: Cannot assign to read only property 'performance' of object '[object global]'`

Failing at: https://github.com/facebook/react-native/blob/v0.71.14/jest/setup.js#L20-L22
_Nb: https://github.com/facebook/react-native/blob/v0.72.0/jest/setup.js 404 file no longer exists in this future RN ver_

Reconsider current node/jest/RN vers we're using (see [issue](https://github.com/facebook/react-native/issues/35701) and [comment](https://github.com/MetaMask/metamask-mobile/pull/8046#issuecomment-1847072391) below)

> it broke between node 18.18 and 18.19 - [Jest relies on descriptor.writable](https://github.com/jestjs/jest/blob/v28.1.3/packages/jest-environment-node/src/index.ts#L88) but it's not longer returned in the descriptor

Nb: Node 18.19 [changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2023-11-29-version-18190-hydrogen-lts-targos)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/8051

## **Manual testing steps**

Run unit tests

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by leotm** [comment]
some unit tests passing now: 6/9/10

**Comment by leotm** [comment]
just when appeared fixed in https://github.com/MetaMask/metamask-mobile/pull/8046/commits/47116335769342ef1e4d4a1a6d0aa75651ccda52

the last 2 commits resulting in no change indicate something else is flakey :suspect: TBC

**Comment by leotm** [comment]
converted back to draft until flakiness resolved, solution appears to be mix of correct
- jest ver
- node ver
- react-native/jest/setup.js patch
- disabling unit tests one by one based on fail history

**Comment by leotm** [comment]
consider bumping to Jest monorepo deps to ^29.2.1 for official RN 0.71.14 compat
https://github.com/facebook/react-native/blob/v0.71.14/template/package.json#L27

**Comment by leotm** [comment]
can confirm CI breaking on Node 18.19 https://github.com/MetaMask/metamask-mobile/actions/runs/7135792916/job/19433229298#step:3:11

passing on 18.18.2 https://github.com/MetaMask/metamask-mobile/actions/runs/7135792916/job/19433229559#step:3:11

final solution: RN patch reverted, Node vers restricted

**Comment by leotm** [comment]
> E2E test started on Bitrise: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/16c6de0b-876a-47d6-9759-8531d9e8321b You can also kick off another Bitrise E2E smoke test by removing and re-applying the (Run Smoke E2E) label

unit tests passing, git clones failing :suspect:

**Review by cortisiko — APPROVED** [review]

**Pull request merged**
