### PR TITLE
Bugfix/homepage injection

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

We had some issues on the injection of data to our home site
1. Was being injected twice, `onLoadStart` and `onLoadEnd`
2. The dapps site wasn't getting the data sometimes, so I added it to `injectedJavaScriptBeforeContentLoaded`
3. If you go to a category and press one, then to a site, then back, the favorites are getting lost. Fixed in https://github.com/MetaMask/metamask-mobile/compare/bugfix/homepage-injection?expand=1#diff-6b45a5c860cb93a60df5eb3c17e26a42R319

Fixes https://trello.com/c/mbsceQNr/252-when-metametrics-is-enabled-i-cannot-interact-with-browser-homepage-tabs-nor-favorites

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

### CODE REVIEW

**Review by rickycodes — APPROVED** [review]
LGTM

**Review by andrepimenta — CHANGES_REQUESTED** [review]
I think there might be a security issue, if the homepageScripts are on injectedJavaScriptBeforeContentLoaded, that means that every website will have access to those, which means every website will have access to the user bookmarks for example no?

Should we consider having on the homepage a way to only perform certain actions after the script is injected?

**Review by andrepimenta — APPROVED** [review]
LGTM!

**Review by ibrahimtaveras00 — APPROVED** [review]
QA Passed

**Pull request merged**
