### PR TITLE
chore: rename `isprivateConnection` to `isPrivateConnection `

### PR DESCRIPTION
**Pull request by cryptodev-2s**
## **Description**

This PR corrects a typo in `isPrivateConnection`, which was previously named `isprivateConnection`.

## **Related issues**

Fixes:

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Daniel-Cross — DISMISSED** [review]
Approved!

**Review by NicolasMassart — APPROVED** [review]
Looks good to me.

**Review by NicolasMassart — CHANGES_REQUESTED** [review]
I initially approved but then realised that there's no unit test update for this change... Because there's no unit test. Not your fault, this funciton was not tested before.
But if you are annoyed by a case issue in the function name so much that you create a PR to update it, I would imagine that the lack of tests on this function is even more an issue for you. At least it is for me.
So ideally, given how simple this function is, and the fact we already have a test file for this utils file, you only have to add a very simple test, even AI generated, and I would approve the name change.

**Review by NidhiKJha — DISMISSED** [review]

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by Gudahtt** [comment]
For the PR title, I'd recommend that it be changed to "chore" even though this is fixing something, because "fix" typically means bug fix, which this is not. "chore" would be better because it would communicate to the author of the changelog that this can be omitted.

Also could you please update the PR description checklist?

**Review by NicolasMassart — APPROVED** [review]
Thank you!

**Review by EtherWizard33 — APPROVED** [review]
LGTM

**Pull request merged**
