### PR TITLE
[FIX] [6.6.0] - Import tokens and NFTs button now visible 

### PR DESCRIPTION
**Pull request by tommasini**
**Description**
This PR aims to change the styles for the Tokens and NFTs import buttons to be visible
**Screenshots/Recordings**
http://recordit.co/izQVai7Beu

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by Cal-L — APPROVED** [review]
LGTM

**Comment by chrisleewilcox** [comment]
@tommasini this does not fix the Import NFTs link button.  I am still not seeing that button for other networks.  I only see the link for Ethereum Main Network.  Can you take a look?
https://recordit.co/zo5ezr9Z41

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
Please take review Import NFTs link not showing for other networks.

**Comment by tommasini** [comment]
Great catch @chrisleewilcox , My commit it was not feature Wise, it was style adjustment and it was me that got confused

Here is a new [recording](http://recordit.co/izQVai7Beu) (it's updated on the PR description as well)

**Review by chrisleewilcox — APPROVED** [review]

**Pull request merged**
