### PR TITLE
update Keystone links

### PR DESCRIPTION
**Pull request by soralit**
**Description**

Keystone needs to update some info on the connect QR hardware wallet page. Mirror PR in extension: https://github.com/MetaMask/metamask-extension/pull/17677

**Screenshots/Recordings**

Before:
image
 

After: 
image

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by gantunesr** [comment]
Looks like this PR is blocked because of an issue regarding forked repos.

https://github.com/MetaMask/metamask-extension/pull/17754

**Comment by soralit** [comment]
Hey @gantunesr , sorry for late reply. Get busy on the hardware development these days. 
I just saw the pr in extension has been merged, do you think this PR can be merged now? 
https://github.com/MetaMask/metamask-extension/pull/18792

**Review by gantunesr — COMMENTED** [review]
LGTM

**Comment by gantunesr** [comment]
@soralit can you update your branch to `main`?

**Comment by plasmacorral** [comment]
Tested against commit 507d74d97975aae48ea331cb85f5b27e1efba0c7 from local branch https://github.com/MetaMask/metamask-mobile/compare/main...build/modify-keystone-link

The new `Learn More`, and pre-existing`How it works?`, and `Tutorial` links were verified on the following devices/OS:

-   Pixel 2 - Android 9
-   Redmi Note 9 - Android 10
-   Samsung a515f - Android 11
-   Samsung s21 - Android 12
-   Samsung S23 Ultra - Android 13
   & 
-   iPhone Xs - iOS 14.4
-   iPhone Xs - iOS 15.3
-   iPhone 12 mini - iOS 16

However, only a black page was able to be rendered on:
-   iPhone 6s - iOS 12.1
-   iPhone Xs - iOS 13.4
This black page was observed in MetaMask, as well as with Chrome and Safari.  I suspect this may be a limitation for older versions of iOS?
https://recordit.co/h2EIXdbuuL

**Review by gantunesr — APPROVED** [review]

**Pull request merged**
