### PR TITLE
Improvement/update keychain lib

### PR DESCRIPTION
**Pull request by andrepimenta**
**Description**

Update keychain library.

@ibrahimtaveras00 It's important to test updating the app from previous versions, and making sure the biometrics and 'remember me' still works. Also now we should support: 
- TouchId (iOS)
- FaceId (iOS)
- Fingerprint (Android)
- Face (Android)
- Iris (Android)

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
LGTM

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
**Issue 1:**

When I come from a previous version (I tested coming from v0.2.19) that already has a password set (both with or w/o biometrics) when I attempt to log in the first time, I get the following error:

Screen Shot 2020-09-10 at 12 30 30 PM

Screen Shot 2020-09-10 at 12 57 50 PM

seen here = https://recordit.co/5qlqauXsuU (notice on the second attempt by just pressing log in it works)

**Issue 2:**

I am unable to get face recognition (android) nor iris scanner (android) to work; seen here = https://recordit.co/986vZPHcow

Basically the first time I try the scan is successful but it doesn't log me in and prompts me a second time.  On the second attempt it's successful but then still doesn't log me in with this error

Screen Shot 2020-09-10 at 7 42 40 PM

Device I tested = Samsung Galaxy Note 9 SM N960U

**Issue 3:**

Continuing from above issue, I'm still able to log in when I manually type my password.  However, when I go to Settings > Security & Privacy I seen "Sign in with Fingerprint?" even though I used Iris/Face recognition and don't have fingerprint enabled on the device; seen here = https://recordit.co/kjPBjQ9ASH

**Issue 4:**
Even though I have iris scanner or face recognition enabled (I have fingerprint disabled on a device level) it still shows me the finger print icon rather than the intended icon.  Also the text says fingerprint still.

Seen here:
image

**Comment by estebanmino** [comment]
could potentially fix 
https://github.com/MetaMask/metamask-mobile/pull/1811
https://github.com/MetaMask/metamask-mobile/pull/1607
https://github.com/MetaMask/metamask-mobile/pull/1496

**Comment by ibrahimtaveras00** [comment]
In release mode, I was not able to reproduce issue 1, but all the other issues were still happening and couldn't see the [following designs](https://github.com/MetaMask/metamask-mobile/pull/1651#issue-440048646) on Android with the exception of fingerprint

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
**Issue 2** 

I am still not able to get face recognition to work at all on android, while it asks me to confirm my face twice and passes however can't log in

seen here = https://recordit.co/wAcDdxWw9t

here is the error:

Screen Shot 2020-10-20 at 7 36 46 PM

**Issue 2A:**

Iris scanner does work now on android however, a few issues arise (as well as fingerprint) in three scenarios 

**scenario 1:**
When I kill the app and relaunch, it prompts me for biometrics correctly, however, when I immediately kill and relaunch it doesn't prompt me for anything and just logs me in 

seen here = https://recordit.co/NDfmrj6pGJ

**scenario 2:**
when I set the app to lock immediately or within 5 seconds and wait the proper 5 seconds or longer, and I put app in background, then go back to app it correctly prompts for biometric on first attempt, however, on subsequent attempts it doesn't prompt me for anything and logs me in right away; seen here = https://recordit.co/lDSe5b8ttb

**scenario 3:**
following above scenario, when I set app to lock immediately and put app in background it works, however, when I kill and relaunch, it doesn't work; seen here = https://recordit.co/n31V6KRjdF

these correctly work with fingerprint on current playstore version; seen here = http://recordit.co/za47JrvyoI

**Issue 3** Fixed, now it says biometrics for Android

**Issue 4** N/A anymore since the device itself prompts the format 

New Issues...

**Issue 5:**

on iPhone even when I have the simulator open which doesn't have biometrics I get prompted as touch ID or Face ID in import seedphrase and create new password views

Screen Shot 2020-10-20 at 9 45 27 PM

Similarly, iPhone 5s doesn't even support touch ID but it still shows as an option on create password/import seedphrase views, and shows in the security setting and furthermore, when I kill the app and relaunch, I'm not prompted for anything and am logged in right away 

seen here = https://recordit.co/WaITh5o9Hf

**Issue 6:**

We are aware that pin doesn't work at all on android, and when I have pin enabled it works as if no biometrics are enabled.  However, on iOS when I ONLY have pin/passcode enabled, I run into a few issues.

**6A:**
It shows as touch ID even though I don't have touch ID enabled (only pin/passcode)

Screen Shot 2020-10-20 at 10 20 21 PM

**6B:**

When I attempt to create password in this state I get the following error 

Screen Shot 2020-10-20 at 10 21 15 PM

seen here = https://recordit.co/bL0ienRbqx

**6C:**
In this state, the only way I can get it to work is if I disable "sign in with touch ID"
It shows as disabled on settings, I then enable it
Upon disabling passcode, and killing/relaunching and attempting to log in with my password, I can't and in a broken state; seen here = https://recordit.co/Upbilod5Fa

Screen Shot 2020-10-20 at 10 27 26 PM

Currently on appstore we don't have the option for passcode; seen here = https://recordit.co/0f7tT75VSc

**Issue 7:**

When I only have Iris enabled on Android, and I sync with extension I get this prompt (even though I don't have fingerprint enabled) perhaps it should say biometrics like in settings?

Screen Shot 2020-10-20 at 10 35 57 PM

Also, I should note, that when I ONLY have face recognition enabled on my device, I don't get this prompt at all when syncing with extension and instead only asks me to enter my password when I launch the app

**Comment by estebanmino** [comment]
Issue 1: Won't fix, we should wait for a dep update.
Issue 2: Fixed
Issue 5:
You can do a configuration on sim, I think if this is working correctly on real devices we're fine.
image
Issue 6: @andrepimenta can you take this one?
Issue 7: Wording is solved, Face ID is related to Issue 1

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
New Issues I'm seeing:

- when I came from an earlier version with PIN enabled it worked and asked for pin
but when I go to security settings I don’t see the option to toggle it off or even enable faceID/touchID

- If you have PIN enabled then log out, and log back in, PIN will be toggled off in Settings > Security and will not ask for PIN on subsequent launches unless the user re-enables it

**Review by ibrahimtaveras00 — APPROVED** [review]
All fixes look good, QA Passed 👍

**Pull request merged**
