### PR TITLE
Inject inpage js

### PR DESCRIPTION
**Pull request by brunobar79**
- Added react-native-fs to be able to read the inpage.js as a string for injection
- Added react-native-wkwebview-reborn to get support of WKUserScript 

Btw, tests are breaking because of this: https://github.com/itinance/react-native-fs/issues/404 
(and I have no idea how to fix it 🙄 )

### CODE REVIEW

**Review by bitpshr — COMMENTED** [review]
Partial review, looking great so far.

**Review by bitpshr — APPROVED** [review]
Some minor style suggestions for consistency, but this is awesome.

**Review by bitpshr — CHANGES_REQUESTED** [review]
Ah, one thing I noticed is that clicking a link within the new webview opens up a mobile Safari window instead of opening the URL within the same webview.

**Comment by TEU7ZoTHLa7sZchXmdqZn5pE75ikooVNfv** [comment]
0x39b2558f63EFf50B8b9326D4c6a7b0443AAFD495

**Pull request merged**
