### PR TITLE
feat: add a return to app modal only for ios 17 when an sdk operation is done

### PR DESCRIPTION
**Pull request by omridan159**
## **Description**

This PR introduces a 'Return to App' modal for iOS 17 users to address the incompatibility of Minimizer.goBack() in the latest iOS version. The modal, triggered post-SDK operations. It's specifically tailored for iOS 17, ensuring it does not interfere with the functionality on older iOS versions. 

### **After**

Screenshot 2023-11-15 at 18 12 24

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by abretonc7s — DISMISSED** [review]
LGTM

**Review by andreahaku — DISMISSED** [review]
LGTM

**Comment by christopherferreira9** [comment]
**Test Case 1 (iOS):**
Connect to dapp -> Accept in MetaMask
You should get the message saying to return to the dapp

**Test Case 2 (Android):**
Connect to dapp -> Accept in MetaMask
You should **not** get the message saying to return to the dapp

**Test Case 3 - Reject (iOS):**
Connect to any dapp -> Request to sign or any other RPC
You should get the message saying to return to the dapp

**Test Case 4 - Reject&Approve batch (iOS):**
Connect to any dapp -> Request a batch and approve all RPC 
You should get the message saying to return to the dapp when rejecting or when completing the whole batch

**Test Case 5 - QRCode (iOS):**
Connect to dapp -> Accept in MetaMask
You should **NOT** get the message saying to return to the dapp

**Test Case 6 - QRCode (Android):**
Connect to dapp -> Accept in MetaMask
You should **NOT** get the message saying to return to the dapp

**Comment by christopherferreira9** [comment]
iOS:

Uploading Screen Recording 2023-11-15 at 18.48.47.mov…

Android:

https://github.com/MetaMask/metamask-mobile/assets/104831203/90f7cf46-600f-4b3d-938c-fff5ba824363

iOS QRCode:

https://github.com/MetaMask/metamask-mobile/assets/104831203/4830d210-5f12-4520-b53e-48c912571e67

**Review by abretonc7s — DISMISSED** [review]

**Review by andreahaku — APPROVED** [review]
LGTM

**Comment by christopherferreira9** [comment]
LGTM

**Pull request merged**
