### PR TITLE
Bugfix: android back

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

Fixes a bug in android where hardware back button wasn't working as expected

Before https://recordit.co/kt9m01GYxt
After https://recordit.co/ue6oxkZPAw

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

### CODE REVIEW

**Review by brunobar79 — APPROVED** [review]
LGTM!

**Review by ibrahimtaveras00 — APPROVED** [review]
looks good, QA Passed 👍

**Review by ibrahimtaveras00 — APPROVED** [review]
Last fixes look good, QA Passed 👍

**Review by brunobar79 — APPROVED** [review]
LGTM!

**Pull request merged**
