### PR TITLE
Get paste context working for password fields (onboarding)

### LINKED ISSUE #1826: Android: Security: Cannot paste password into password creation page.
**Describe the bug**
On the Create Password activity, I am unable to long-press on the password field to paste a password.  No matter how long I long-press, the paste option never appears.

This is a security issue because it means that users cannot use a password manager, they must use a human memorized password (known to be terrible for security).

**To Reproduce**
_Steps to reproduce the behavior_
1. Copy a password from somewhere (e.g., password manager)
2. Get to the Create Password screen.
3. Try to paste the password.
4. Notice that you cannot.

**Expected behavior**
I can paste a password into the password creation field.

**Smartphone (please complete the following information):**
 - Device: OnePlus
 - OS: Android
 - App Version: 1.0.2

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### PR DESCRIPTION
**Pull request by rickycodes**
**Description**

This ensures paste context comes back for the password fields on onboarding:

image

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #1826

### CODE REVIEW

**Review by EtDu — COMMENTED** [review]
Does the desired effect fail if we leave the width as 100% in styles without having it inside the state being modified on component mount?

**Comment by rickycodes** [comment]
sadly yes. you can read more about the issue here: https://github.com/facebook/react-native/issues/9958#issuecomment-365624780

fb has multiple "stale" issues outlining the problem. you can see another fix we applied for the same thing here: https://github.com/MetaMask/metamask-mobile/pull/1548

**Comment by rickycodes** [comment]
I've seen others solve it by mounting the text component with `editable={false}` and then changing it to `true` to get the desired result. maybe that's cleaner solution and we should try that instead?

**Review by EtDu — APPROVED** [review]
I'd say as long as there are no perf drawbacks from using setTimeout then no problem

**Review by ibrahimtaveras00 — APPROVED** [review]
Fix looks good now, QA Passed 👍

**Pull request merged**
