### PR TITLE
Allow webview debugging in dev mode + XIP

### LINKED ISSUE #923: Allow to use http://your_local_ip for development
If I try to open http://192.168.1.10:3000 it says

ERR_CLEARTEXT_NOT_PERMITTED

Here it explains how to fix it
https://github.com/flutter/flutter/issues/30368

OS: Android

### PR DESCRIPTION
**Pull request by EtDu**
**Description**

Enables webview debugging on Android during dev mode, and temporarily allows xip connections so we can use http://LOCAL_IP for development

Resolves #923

### CODE REVIEW

**Comment by estebanmino** [comment]
what about allowing `http` by default? I'm in favor of it, we do it on ios and we don't on android just because you have to do other configuration https://stackoverflow.com/a/51902630 cc @andrepimenta since you're working on the browser refactor

**Comment by EtDu** [comment]
I think we should use a similar solution for iOS, instead of arbitrarily allowing http

**Comment by omnat** [comment]
Trust judgement of @andrepimenta on this.

**Comment by EtDu** [comment]
Changed PR based on recent decisions:
- allow http always with warning (separate PR)
- allow webview debugging in dev mode

**Comment by EtDu** [comment]
@ibrahimtaveras00 For QA:
1) See if you can debug android webview https://github.com/MetaMask/metamask-docs/pull/169/files#diff-ea52e377c8d802334edebc350d1ea8a1R101
2) See if you can connect to a server running on a computer using the same wifi as the phone https://github.com/MetaMask/metamask-docs/pull/169/files#diff-ea52e377c8d802334edebc350d1ea8a1R83

**Review by ibrahimtaveras00 — APPROVED** [review]
✅

**Pull request merged**
