### PR TITLE
[WIP] SES lockdown() - LavaMoat Compatibility

### PR DESCRIPTION
**Pull request by bentobox19**
Compatibility Documentation: https://github.com/LavaMoat/docs/issues/1

* Add `ses` dependency
  * Tell babel to ignore its transformation
  * Tell metro to accept a `.cjs` file as dependency entry point
* Add SES `lockdown()` call
* Modifications required for the application to work
  * Disable default integration in `Sentry`
  * Add patches
    * React Native to disable `Promise` polyfill
    * Metro React Native Babel Preset to disable two plugins
    * `ethjs` dependencies leveraging babel runtime
    * `web3` dependency assigning a frozen intrinsic.

Extensive QA required ❗

### CODE REVIEW

**Comment by bentobox19** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bentobox19** [comment]
Requesting advice for next steps regarding QA Iterations, @sethkfman

cc: @kumavis

**Comment by bentobox19** [comment]
Forced pushed a shorter and cleaner version of the changes needed to run `lockdown()`.

**Comment by bentobox19** [comment]
New force push

**Comment by bentobox19** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gantunesr** [comment]
Closed per sync with @bentobox19

**Pull request closed without merging**
