### PR TITLE
Update @metamask/swaps-controller

### PR DESCRIPTION
**Pull request by dan437**
## Description
It changes Arbitrum and Optimism smart contract addresses to lowercase and updates a fn for checking direct wrapping.

### CODE REVIEW

**Comment by cortisiko** [comment]
**Issue**:

 when i attempt to swap an ERC-20 token i get `TypeError: undefined is not an object (evaluating 'destinationToken.toLowerCase')`

see [recording](http://recordit.co/6zF9dIaDg4)

**Comment by rickycodes** [comment]
> **Issue**:
> 
> when i attempt to swap an ERC-20 token i get `TypeError: undefined is not an object (evaluating 'destinationToken.toLowerCase')`
> 
> see [recording](http://recordit.co/6zF9dIaDg4)

perhaps we should consider: `destinationToken?.toLowerCase` upstream? /cc @dan437

**Review by cortisiko — APPROVED** [review]
This is QA passed. I confirmed that https://github.com/MetaMask/mobile-planning/issues/500 and https://github.com/MetaMask/mobile-planning/issues/502 is QA passed. 🌮 🌮

**Review by sethkfman — APPROVED** [review]
LGTM

**Pull request merged**
