### PR TITLE
feat: bump controllers related accounts logic

### PR DESCRIPTION
**Pull request by gantunesr**
## **Description**

**The original PR is https://github.com/MetaMask/metamask-mobile/pull/9318. It was reverted and now the changes are being introduced in this new PR.**

This PR updates several controllers that handle logic related to the wallet and accounts.

- Keyring controller to v13
- Accounts Controller to v11
- Preferences controller v8
 
Some noteworthy points for this changes,

 - Downgrade controller utils to interact with linea sepolia, only function used by preferences controller of controller-utils is `toChecksumHexAddress` and the function is the same on[ v^5](https://github.com/MetaMask/core/blob/add71d194d75a3c720c935f7947d06ee950bd7c7/packages/controller-utils/src/util.ts#L255) and on [v^8](https://github.com/MetaMask/core/blob/a24869b8e7e518f6682058d3eda4c41f0317ccc8/packages/controller-utils/src/util.ts#L263C17-L263C37)
 - Updated flow of create account and import account to update the `ecnryptionLib` that way on the future we can create or import and we will not run the flow  `[recreateVaultWithSamePassword](https://github.com/MetaMask/metamask-mobile/blob/fcfa9d1bd03e16ba18f3e9919b85a854614c2377/app/core/Authentication/Authentication.ts#L110)`, since it was running unnecessarily
 - Updated controllers initialization that had preferencesOnStateChange argument on their constructor (Mostly assets-controllers and PPOM), to have the address checksummed, on this current version PreferencesController starts to listen to KeyringController and that address is now on lower case format, which means that we need to update to a checksummed format for those specific scenarios for the assets controllers keep their data and tokens never disappear from the user for missmatching user address format
- Updated keyring controller patch with the same as extension to prevent the HD wallet disappear, please check the details on this core branch: extension-keyring-controller-v13-patch

## **Related issues**

* Fixes https://github.com/MetaMask/mobile-planning/issues/1689
* Fixes https://github.com/MetaMask/mobile-planning/issues/1697
* Fixes https://github.com/MetaMask/mobile-planning/issues/1693

## **Manual testing steps**

1. Create new wallet
2. Import existing wallet
3. Import private key
4. Upgrade testing 

## **Screenshots/Recordings**

Upgrade from main with Binance Smart Chain Selected, imported account with private key and tokens imported (Multiple chains added, and tokens imported on them also NFT imported on mainnet)

https://github.com/MetaMask/metamask-mobile/assets/46944231/ba6da46f-e923-45c8-b940-53044bf912e9

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by plasmacorral** [comment]
When importing a valid private key by QR code, user is shown an error: "Invalid deeplink Invalid URL:" and the private key string is displayed in the error message.

IMG_0772

Was observed with QA build from PR 9318, with multiple devices:
- Pixel 5a- Android 14
- Samsung a515f- Android 12
- iPhone Xs- iOS 17.4.1

Steps:

1. Import an SRP and get to wallet view
2.  Follow add account flow for importing private key
3. Scan QR of valid private key
4. Observe error

**Review by owencraston — APPROVED** [review]

**Comment by plasmacorral** [comment]
Tested migrations on Android 12, 14 and iOS 17.4.1 with Imported, Ledger and QR accounts present from both 7.18.0 (1268) as well as 7.19.0 (1292).  Custom labels were preserved.  Able to add and remove accounts as expected, change password and biometric auth, create new wallet, import an existing SRP in setup, import private keys after setup, and confirm SRP backup demand when value is added.

Had some observations, but was not able to reproduce outside of the initial occurrence and looks like there have been subsequent changes in both 7.19.0 and 7.20.0 that may resolve the issue observed and not able to be reproduced.

- Observed accounts disappear once updating from 7.18.0 to the branch under test
     - There were two independent fixes for both [Ledger](https://github.com/MetaMask/metamask-mobile/pull/8740) and [QR](https://github.com/MetaMask/metamask-mobile/pull/8741) wallets both going missing, within 7.19.0
- Observed tokens disappear once on an imported account
     - There was a [fix](https://github.com/MetaMask/metamask-mobile/pull/9148) for disappearing tokens within 7.20.0
- Observed private key input appearing in an error message  when importing by QR
     - was present on main and looks like it may have been introduced within 7.22.0, so filed a fresh report [here](https://github.com/MetaMask/metamask-mobile/issues/9517)

**Review by Gudahtt — APPROVED** [review]

**Comment by Cal-L** [comment]
E2E failure not related to this branch since it's failing because of notification prompt

**Review by Cal-L — APPROVED** [review]
LGTM

**Pull request merged**
