### PR TITLE
test: Address App launch times failure test

### PR DESCRIPTION
**Pull request by cortisiko**
…ive waits.

## **Description**

This PR aims to put the app launch times tests back in the green. The tests started failing because of a couple of reasons:

- A new onboarding success screen was added to the app. The launch times test did not get updated correctly
- The website we used for testing had UI changes that broke our tests. We will now use the mm test dapp for this test
- The selectors used to identify elements were incorrect. 

Note: The warm start tests are failing for a legit reason. The launch times are below the expected bench mark of 8 seconds hovering around ~11 seconds

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Cal-L — COMMENTED** [review]
- One smoke test is failing
- Let's we also post a launch time test run in the comments to confirm the fix

**Comment by cortisiko** [comment]
> One smoke test is failing

There seems to be a latency issue with the app? This test does not touch anything swaps related. I will investigate on main and see. 

> Let's we also post a launch time test run in the comments to confirm the fix

Ah, so this is what I was discussing during the stand-up. The point of failure in the tests has been fixed, but the tests still do not pass the 8-second benchmark. App code changes are needed to address the performance issue.

. See Tomas's message here: https://consensys.slack.com/archives/C04GLB755TK/p1716311340155619

**Comment by Cal-L** [comment]
@cortisiko  Could you post a link of the successful app start time test in Bitrise?

**Comment by cortisiko** [comment]
@Cal-L  Because this test relies on changes to the app code to improve performance I went ahead and updated the bench mark from 8 seconds to 12 seconds. 

Here is a screenshot of passing warm start tests
Screenshot 2024-05-21 at 6 37 25 PM

I will kick off a bitrise build right now

**Comment by cortisiko** [comment]
@Cal-L Passing App launch times test on bitrise with adjusted benchmark: https://app.bitrise.io/build/4bb0f921-edf8-4685-a30d-0e2843819686

**Review by Cal-L — APPROVED** [review]
LGTM

**Pull request merged**
