### PR TITLE
get started new design

### PR DESCRIPTION
**Pull request by alaahd**
**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Progresses #???

### CODE REVIEW

**Comment by alaahd** [comment]
@Pedro-vk I have added the @2x and @3x versions of the icon.

**Comment by wachunei** [comment]
@alaahd I forgot to mention we need the dark versions too 🤦  maybe it is better to export as transparent png?

**Review by wachunei — CHANGES_REQUESTED** [review]
Add dark version assets.

**Review by Fatxx — COMMENTED** [review]
Blocking https://github.com/MetaMask/metamask-mobile/pull/3696 by not having design ready yet.

**Comment by wachunei** [comment]
Superseded by #4293

**Pull request closed without merging**
