### PR TITLE
fix: fix account name display in send flow

### LINKED ISSUE #10155: [Bug]: Send to screen showing wrong account names
### Describe the bug

When sending to an account on the `Send to` screen the account names under "Your Accounts" are showing the wrong account names.  Account names should match the Account list modal on the wallet view.

Not able to reproduce on 7.24.4.

Related: #9724 

### Expected behavior

Account names under "Your Accounts" should match the Account list dropdown modal on the wallet view.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/6626407/7bb9db07-e2bf-4317-938d-b7d2e818ef17

### Steps to reproduce

GIVEN I am on Sent to screen
THEN account names under "Your Accounts" matches account names in account list modal on wallet view (FAILED: account names do not match)

### Error messages or log output

_No response_

### Version

7.26.0

### Build type

None

### Device

android samsung galaxy A42

### Operating system

iOS, Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

When a new hardware wallet is imported, the default name is "QR ${index}" which comes from [here](https://github.com/MetaMask/core/blob/5bc115051a0ad410282bb5c7582222ba4bfd5710/packages/accounts-controller/src/AccountsController.ts#L896).

That name is fetched using `useAccounts` hook and displayed inside the `AccountSelector.tsx` component.

However; when the user clicks on the send flow; the name of the imported hardware wallet is different because it is fetched from` preferencesControllerState.identities`.

I think accountsController and identities should be in sync, just not sure how they went out of sync in this issue...

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/10155

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by NicolasMassart — COMMENTED** [review]
Tested and it seems to work

https://github.com/MetaMask/metamask-mobile/assets/4677568/fd77d6f5-5ce6-44bb-81df-08363b1809d5

>[!IMPORTANT]
> Now we need non regression tests: updating unit tests and e2e
> Because they currently don't fail, and given your changes they should...
> This means this specific case is not covered: at least unit tests coverage please.

**Comment by dawnseeker8** [comment]
i have tested this fix with ledger, and confirm the first send flow screen is working ok, please see the video

https://github.com/MetaMask/metamask-mobile/assets/7315988/2c50d194-eea6-48bd-abe9-d53a766353ad

however, find name mismatch in confirm screen.
image

the confirm screen show see `Ledger 1` instead of `Account 2`

**Comment by sahar-fehri** [comment]
> i have tested this fix with ledger, and confirm the first send flow screen is working ok, please see the video
> 
>  Screen_Recording_20240704_001916_MetaMask.mp4 
> however, find name mismatch in confirm screen. image
> 
> the confirm screen show see `Ledger 1` instead of `Account 2`

Thank you @dawnseeker8 !
I have made an update on the account displayed in the confirmation screen, could you please try and test again 🙏

**Comment by sahar-fehri** [comment]
Closing this one as the same issue has been addressed here https://github.com/MetaMask/metamask-mobile/pull/9724

**Pull request closed without merging**
