### PR TITLE
fix: add warning for optimism and arbitrum goerli

### PR DESCRIPTION
**Pull request by sahar-fehri**
## **Description**

Adds a warning when the user switches to either Arbitrum goerli or OP goerli testnet.

This also fixes the fact that once you switch to goerli network and you close the warning. Then switch to Ethereum. Then switch back to goerli, you wont be able to see the deprecation warning again.

## **Related issues**

Fixes:
Related ticket : https://consensyssoftware.atlassian.net/browse/MMASSETS-155

## **Manual testing steps**

1. Go to home page
2. Either use chainlist to add OP goerli network/Arbitrum Goerli. Or you can click on Add network manually and fill the input boxes
3. Click switch network
4. You should see the network deprecation warning.

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/10994169/d1279946-6cbe-42dc-bc8c-53fabec434dd

### **After**

https://github.com/MetaMask/metamask-mobile/assets/10994169/1828b594-0507-41ac-85cc-e41f72703770

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by tommasini** [comment]
> This also fixes the fact that once you switch to goerli network and you close the warning. Then switch to Ethereum. Then switch back to goerli, you wont be able to see the deprecation warning again.

I don't understand what's fixed here by reading the code it doesn't seem that this would change any logic on render level.

**Review by tommasini — APPROVED** [review]
LGTM

**Comment by tommasini** [comment]
Can we also attach the correspondent issue if exists, please?

**Comment by sahar-fehri** [comment]
> Can we also attach the correspondent issue if exists, please?

Dnt think there is an issue for it, here is the ticket though https://consensyssoftware.atlassian.net/browse/MMASSETS-155

**Pull request merged**
