### PR TITLE
feat: v7.33.1

### PR DESCRIPTION
**Pull request by Cal-L**
## **Description**

PR for merging v7.33.1 back into main

Team check-off
- [x] team-confirmations

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by OGPoyraz** [comment]
LGTM, resimulation changes are effective in the build

https://github.com/user-attachments/assets/24f8c5d4-bdf7-4ba4-8206-af7ba39800fb

**Comment by bschorchit** [comment]
Note: I have edited to team-confirmation in the description and gave sign off

**Review by sethkfman — DISMISSED** [review]
LGTM

**Review by sethkfman — APPROVED** [review]
LGTM

**Comment by sethkfman** [comment]
Passing regression - [E2E](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/f3fbd218-2d46-42ee-b4e4-06ce16d2ac93?tab=workflows)

**Pull request merged**
