### PR TITLE
Allow custom network fiat values

### LINKED ISSUE #1929: Disable fiat values when user is connected to a custom or testnet RPC
**Describe the bug**
Users should not see Ethereum mainnet fiat values of a token they have, unless they are on the Ethereum mainnet.  If they are on a testnet or other custom rpc chain, the fiat value should **only** display if it is in fact the value of those tokens on that chain.

Related issue on extension: https://github.com/MetaMask/metamask-extension/issues/9749
support ticket # 60926

**Expected behavior**
No fiat value shows, and the option to set fiat as default is disabled on custom networks.

### LINKED ISSUE #2440: View the FIAT conversion of my tokens
As a user, irrespective of which network I am on, I want to view the FIAT conversion values of my tokens.

Currently we pull FIAT conversion values by the name of the token (this name might be same on mainnet, and so the conversion rate will be shown that of extension).
- Use Coingecko API for price feeds for the custom networks that Coingecko supports.

Consideration:
- Giving the option to add a price feed link on the custom network form (and API), similar to blockexplorer link.
- Add tooltip when pricing information is not available for a token (apply this tooltip also when a token price isn't available on Ethereum mainnet) -- support team shared the insight that users think that a token isn't usable if it doesn't have a price conversion, and get confused on why it's not shown. Indicating that these prices are pulled from Coingecko might be useful.

### PR DESCRIPTION
**Pull request by wachunei**
**Description**

- Allow showing fiat values when using custom networks
- This PR uses `@metamask/controllers` v12

Screen Shot 2021-07-01 at 10 41 13Screen Shot 2021-07-01 at 10 40 55Screen Shot 2021-07-01 at 10 40 27

**Issue**

Resolves #2440 
Fixes #1929

### CODE REVIEW

**Review by sethkfman — COMMENTED** [review]
Will you be needing to update any test cases?

**Comment by wachunei** [comment]
> Will you be needing to update any test cases?

Maybe snapshots, not sure

**Review by Cal-L — CHANGES_REQUESTED** [review]
@wachunei 
Code LGTM. One thing that we should do though (and probably more standard) is to display at least 2 trailing numbers after the decimal for USD. Not sure about other currencies, but I suspect the case for those.

**Comment by wachunei** [comment]
@Cal-L Yeah, we are aware of this issue and there's a proposal we have started a long time ago but have not finished. https://www.notion.so/Mobile-Numbers-a2cfe7926f754eb8a55e4ac356c52b44

**Review by Cal-L — APPROVED** [review]

**Comment by Cal-L** [comment]
@wachunei 
Sounds good, yeah if we're going to handle that as a separate issue, then this PR LGTM. :rocket:

**Comment by wachunei** [comment]
@ibrahimtaveras00 We are merging this. QA needed on develop only to spotcheck the balances showing up back again.

**Pull request merged**
