### PR TITLE
add e2e coverage for automatic security update screen

### PR DESCRIPTION
**Pull request by cortisiko**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

This PR adds e2e test coverage in appium and detox for the automatic security update screen

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by SamuelSalas** [comment]
I was able to execute all the test scenarios on my local machine successfully.

**Review by SamuelSalas — APPROVED** [review]
I was able to execute all the test scenarios on my local machine successfully.

**Review by Cal-L — APPROVED** [review]
LGTM

**Review by chrisleewilcox — DISMISSED** [review]
Not able to build.....

image

**Pull request merged**
