### PR TITLE
[IMPROVEMENT] Use Set when filtering blocklist

### PR DESCRIPTION
**Pull request by Cal-L**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

This PR patches the `PhishingController` to use `Set` when filtering on the blocklist. The improvement here (at least testing locally on iOS) is that look up in `Set` vs using `includes` while filtering reduces same business logic processing time by 4x. This translates to a user experiencing 4x faster cold start times than before.

**Issue**

Progresses #5382

**Test**

We should expect cold start times on iOS to be ~4seconds, while Android (depending on device) shouldn't take more than 10 seconds. (Both times reported by Curtis). Relative to the previous app version, the cold start up times should be noticeably lower.

### CODE REVIEW

**Review by gantunesr — APPROVED** [review]

**Comment by chrisleewilcox** [comment]
Test Scenarios:

- Multiple (numerous) browser tabs opened and connected to websites and dapps (opensea, uni, 1inch, reddit, etc...)
- Navigate through opensea 
- Navigate throughout app while numerous browser tabs connected (Settings, Activity, Wallet view, Import and Request tokens, etc...)
- Execute transactions while numerous browser tabs connected (Send, Swap, QR scan, HW transactions, etc...)

Expected: mobile app usage is not negatively impacted

**Comment by chrisleewilcox** [comment]
Issue #1:  Browser: opensea.io: tapping MetaMask icon on connect wallet takes you download MetaMask page.
Expected: Wallet connects to opensea
https://recordit.co/cVKsYZSFgx

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
Please review issues.

**Comment by chrisleewilcox** [comment]
Issue 2: Uniswap: Swaps: UI components on swap screen are not loading
https://recordit.co/oRTeCz3M7C

NOTE: This currently exist in prod but sites/dapps that are not loading UI fully may be contributing to slowness.  This is not a Uniswap specific issue but this issue is using Uniswap as a specific example.

**Comment by cortisiko** [comment]
Regarding Issue 1 I cannot reproduce it on a physical device: http://recordit.co/qzgkprczPr 
And sim: http://recordit.co/kKp5jKeIo7 

Maybe opensea was having a connectivity issue earlier in the day. 

Regarding issue 2, This seems dapp specific. Uniswap has Skelton loaders that appear for swap prices.

**Review by cortisiko — APPROVED** [review]
Looks good to me!

**Review by chrisleewilcox — APPROVED** [review]

**Pull request merged**
