### PR TITLE
On-ramp: remove hardcoded selected network name

### PR DESCRIPTION
**Pull request by wachunei**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

This PR removes the dependency for network names upon a hardcoded array. The `providerConfig.nickname` and aggregator `chainName` will be used. In the case neither exist, we will use "this network".

This is a continuation of this PR https://github.com/MetaMask/metamask-mobile/pull/6340

**Screenshots/Recordings**

~~_If applicable, add screenshots and/or recordings to visualize the before and after of your change_~~

**QA**

The token list in the Amount To Buy view must display the network `shortName`.

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by gantunesr — APPROVED** [review]

**Comment by bkirb** [comment]
@wachunei I verified I see the short name now in the amount to buy modal

**Comment by wachunei** [comment]
@SocketSecurity ignore @consensys/on-ramp-sdk@1.20.0

**Comment by sethkfman** [comment]
@wachunei Review the Socket.io `Bot Commands` to ignore the commands since the library is one of our own

**Comment by wachunei** [comment]
@sethkfman I'm getting warnings from dependencies that are coming from main, what should we do about these?

**Pull request merged**
