### PR TITLE
Lock KeyringController on logout

### PR DESCRIPTION
**Pull request by rickycodes**
based on feedback from @Gudahtt we now lock the `KeyringController` when we `logout` and when we `lockApp`

### CODE REVIEW

**Review by andrepimenta — APPROVED** [review]
LGTM!

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
The only issue I've found here is on iOS 

- I came from the testflight build 0.2.19 and then synced with extension with Face ID enabled
- I then built this branch and built to the real device 
- Once I was prompted for Face ID I saw the check mark, however, it didn't unlock the app

seen here = https://recordit.co/IbI0JRu9jN

I couldn't reproduce this on Android with an imported account nor fingerprint with a wallet synced with extension = https://recordit.co/sSRW7PpGgr

**Review by ibrahimtaveras00 — APPROVED** [review]
QA Passed

**Pull request merged**
