### PR TITLE
[FIX] Invalid title error on Wallet Connect v1

### PR DESCRIPTION
**Pull request by abretonc7s**
FIX wallet connect v1 integration when title is missing

Fixes [938](https://github.com/MetaMask/mobile-planning/issues/938)

### CODE REVIEW

**Review by andreahaku — APPROVED** [review]
LGTM

**Comment by sethkfman** [comment]
@abretonc7s @andreahaku  Can you point this fix to `release/6.5.0` branch?

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
@abretonc7s @andreahaku please rebase this off of release/6.5.0 branch.  Issue was reported against release/6.5.0.  Create a new PR if you have to but this is not a fix for main branch.

**Comment by deeeed** [comment]
> Fixes [938](https://github.com/MetaMask/mobile-planning/issues/938)

Moved it to a new PR https://github.com/MetaMask/metamask-mobile/pull/6280

**Comment by chrisleewilcox** [comment]
PR #6280 was merged.  Closing this PR.

**Pull request closed without merging**
