### PR TITLE
feat: build your earnings component stub in eth token details

### PR DESCRIPTION
**Pull request by Matt561**
## **Description**

This PR adds staking-related component stubs as part of our mobile pooled staking initiative.

- Added `StakingEarnings` and `TooltipModal` components.
- Added `useTooltipModal()` for easy reuse of tooltip modal.
- Added "Your earnings" section on Ethereum asset details page.
- Added necessary English translations in `en.json`.
- Updated relevant `__snapshot__` files.

Note: The `<StakingEarnings>` component uses mock data temporarily until we've connected it to the backend. This component will also be disabled via the `MM_POOLED_STAKING_UI_ENABLED` feature flag. 

## **Related issues**

[STAKE-782: [FE] Build ‘Your Earnings’ component in ETH token details](https://consensyssoftware.atlassian.net/browse/STAKE-782)

## **Manual testing steps**

Getting to ETH earnings section
1. Click `Ethereum` on main portfolio/tokens list page
2. You should see the new `Your earnings` underneath the balances section (near the top).

Testing `TooltipModal`
1. In the `Your earnings` section, click on the info icon beside "Annual rate".
2. You should see a bottom sheet modal appear with the "Annual rate" tooltip.

### **Before**

https://github.com/user-attachments/assets/bd00a576-7c1a-42e0-b6ff-7e98c84de5e0

### **After**

https://github.com/user-attachments/assets/3e89d88f-9651-41da-8de9-1906c9590b02

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Matt561** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Matt561** [comment]
Hey all,

This is my first PR since joining Consensys. I appreciate any support or guidance in respecting our internal processes.

Please provide any feedback you have to help me improve this and future pull requests 😄

**Review by amitabh94 — DISMISSED** [review]

**Review by tommasini — APPROVED** [review]
Awesome!!! LGTM

**Comment by tommasini** [comment]
Let's just re-run the E2E on the latest version

**Pull request merged**
