### PR TITLE
fix: get Favicons from dedicated metamask.faviconkit.com subdomain

### PR DESCRIPTION
**Pull request by andreaspitzer**
We’re super proud to be MetaMask’s choice for favicons! To ensure continous uptime, we’re giving the project its own dedicated subdomain, and this MR updates the icon URLs to use its dedicated domain name: `metamask.faviconkit.com`

**Description**

We’ve changed occurrences of `https://api.faviconkit.com` to `https://metamask.faviconkit.com`

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [ ] ~~Any added code is fully documented~~

**Issue**

#4058

### CODE REVIEW

**Comment by AndreasPizsa** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Review by gantunesr — COMMENTED** [review]
~LGTM. Waiting for QA approval~

This only requires spot check

**Review by gantunesr — APPROVED** [review]

**Comment by gantunesr** [comment]
Don't worry, I just approved it to run the workflows

**Review by gantunesr — CHANGES_REQUESTED** [review]
Pending an extra review

**Comment by sethkfman** [comment]
Will not implement at this time.

**Pull request closed without merging**
