### PR TITLE
Feat: InstaPay v2

### PR DESCRIPTION
**Pull request by brunobar79**
Opening PR to track what's left:

### UI
=> Design QA (mostly migration)
=> Deposits not showing up in tx history

### CODE REVIEW

**Comment by rhlsthrm** [comment]
@brunobar79 the PR you linked https://github.com/ConnextProject/indra/pull/466 is merged and live already.

**Comment by LayneHaber** [comment]
[ConnextProject/indra#469](https://github.com/ConnextProject/indra/pull/559) is ready to be merged, pending fixes to our CI!

Note: The `createdAt` field will always be when the payment was sent (ie. when it was added to the database). We can change this to include an `updatedAt` field, which will reflect when a payment was claimed, just let me know.

Sample transfer record from `getTransferHistory` endpoint:
```
[
  {
    "id": 3,
    "createdAt": "2019-11-22T21:50:44.215Z",
    "amount": "1000000000000000000",
    "assetId": "0xeec918d74c746167564401103096D45BbD494B74",
    "senderPublicIdentifier": "xpub6DjtXrpB4z7agWaG2MLCMj391xNe2UPuvHrHDBKMqzemJfpujcHy4nAHfrVVKTdKvxPGpCimAHrYEhMPA4pbijBRiHYN3nKqVsMExKMCDz2",
    "receiverPublicIdentifier": "xpub6EvWpWRd56x6LP2W9dVV9oEYCGvZhJn9dQEcHdr4oqoNVjr2eJFyssyS7Zp3Kcox3TTH9DHcFSFAfEigYzGyLWA2kGZwNh1gFes7tXhJcPa",
    "meta": {
      "source": "daicard"
    }
  }
]
```

**Comment by LayneHaber** [comment]
meta and datetime merged into latest client `1.2.9`

**Comment by brunobar79** [comment]
Closing in favor of #1238

**Pull request closed without merging**
