### PR TITLE
Bug fix/android cookie storage

### LINKED ISSUE #1273: metamask-mobile not accepting cookies from github login flow on gitcoin
Hi from Gitcoin.

weve got a few reports from users that metamask mobile is not accepting cookies set in the browser from github login flow, preventing users from logging in on gitcoin, and creating a 500 on the Gitcoin login flow.

For example i got this from a user..  

Screenshot_20200110-215041_MetaMask (1)

 The objective of this bounty is to get Gitcoin login working on metamask mobile

Suggested fix path is to clone metamask-mobile, get it running on your local, and then try to login to gitcoin.  The browser will receive a set of cookies/session variables back from Gitcoin.. which are not stored in the same manner that Chrome/Opera store them.. thus causing logins on gitcoin to fail on metamask mobile.

Please only apply to the bounty if you can get this done within 2 weeks; and if you have strong independent debugging skills.

### PR DESCRIPTION
**Pull request by mul1sh**
**Description**

This is the init commit to fix the cookie storage bug in android, will have it working in less than 4 days, just testing out a few things on my end.

**Checklist**

* [*] There is a related GitHub issue
* [ ] Tests are included if applicable
* [*] Any added code is fully documented

**Issue**

Resolves #1273

### CODE REVIEW

**Comment by mul1sh** [comment]
Testing my fix locally with the gitcoin site and then I update this PR :)

**Review by nicc938 — APPROVED** [review]
Arr

**Comment by andrepimenta** [comment]
Closing this due to inactivity, feel free to open a new one when the fix is finished.

**Comment by mul1sh** [comment]
Ok will do, thanks

**Pull request closed without merging**
