### PR TITLE
[trivial] - Update react-native-webview+11.13.0.patch

### PR DESCRIPTION
**Pull request by ac-cb**
**Description**
Rather than assume valid `head` tags must close, we count less characters + return true for the following changes
1. `<head `
2. `<head attr=value`

This is an issue we've seen [here](https://github.com/MetaMask/metamask-mobile/issues/1975), but it was closed before the fix was implemented.

Our recommendation is to instead implement the parsing outlined [here](https://github.com/MetaMask/metamask-mobile/issues/1975#issuecomment-942712432)

We think this is better because
1. It makes no assumptions about what other attrs apps might include in the `head` tag
2. It accounts for a minor edge case where html is parsed / typed as `<head >` instead of `<head>`

However, since we ultimately unsure around the exact scope / behavior of this patch, we would appreciate a second set of eyes to verify that nothing unexpected would occur from this. @andrepimenta committed the patch and might know best.

**Checklist**
* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Progresses #???

### CODE REVIEW

**Comment by ac-cb** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by andrepimenta — APPROVED** [review]
LGTM!

**Comment by ac-cb** [comment]
@andrepimenta we're trying to apply these changes locally + verify they work in dev builds, however, our preliminary tests are not promising. :(

Can you give some context why you're looking for `62` [here](https://github.com/MetaMask/metamask-mobile/pull/4154/files#diff-201059220320d45146a2d513851645305e0f908cd746a0ea29a22e2376a6c2d0R290)?

**Comment by ac-cb** [comment]
@andrepimenta we got to it. looking up the byte character, you're looking for the closing tag `>`.

instead, we propose looking for `d` (character 100), looking back 5 characters, and then running the equals on `<head`

**Comment by rphuber** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rphuber** [comment]
I'm not sure what the difference in the patch is.  I'm guessing that it's based on the tools used to generate the patch file.  If you could let me know what versions of gradle/android sdk/android ndk you use I can update mine and repatch the file and update the pr.  Thanks!

**Comment by rphuber** [comment]
relevant code from the react-native-webview:
```
    @Override
    public int read() throws IOException {
        if (scriptWasInjected || !hasJS) {
            return pageIS.read();
        }

        if (!scriptWasInjected && headWasFound) {
            int nextByte = scriptIS.read();
            if (nextByte == -1) {
                scriptIS.close();
                scriptWasInjected = true;
                return pageIS.read();
            } else {
                return nextByte;
            }
        }

        if (!headWasFound) {
            int nextByte = pageIS.read();
            contentBuffer.append((char) nextByte);
            int bufferLength = contentBuffer.length();
            if (nextByte == 62 && bufferLength >= 6) {
                if (contentBuffer.substring(bufferLength - 6).equals("<head>")) {
                    this.scriptIS = getScript(this.charset);
                    headWasFound = true;
                }
            }

            return nextByte;
        }

        return pageIS.read();
    }
```

**Comment by rphuber** [comment]
I really only updated the react-native-webview file with:
```
public int read() throws IOException {
+        if (scriptWasInjected || !hasJS) {
+            return pageIS.read();
+        }
+
+        if (!scriptWasInjected && headWasFound) {
+            int nextByte = scriptIS.read();
+          int nextByte;
+          if (!hasClosedHead) {
+            nextByte = pageIS.read();
+            if (nextByte != closingCarat) {
+                return nextByte;
+            }
+              hasClosedHead = true;
+              return nextByte;
+
+          }
+            nextByte = scriptIS.read();
+            if (nextByte == -1) {
+                scriptIS.close();
+                scriptWasInjected = true;
+                return pageIS.read();
+            } else {
+                return nextByte;
+            }
+        }
+
+        if (!headWasFound) {
+            int nextByte = pageIS.read();
+            contentBuffer.append((char) nextByte);
+            int bufferLength = contentBuffer.length();
+            if (nextByte == 62 && bufferLength >= 6) {
+                if (contentBuffer.substring(bufferLength - 6).equals("<head>")) {
+            if (nextByte == lowercaseD && bufferLength >= 5) {
+                if (contentBuffer.substring(bufferLength - 5).equals("<head")) {
+                    this.scriptIS = getScript(this.charset);
+                    headWasFound = true;
+                }
@@ -303,7 +4433,7 @@ index f743bbc..fb6b4c1 100644
+  }
```

**Comment by rphuber** [comment]
Let me know your settings and I can rerun the patch of react-native-webview and see if it makes a difference

**Comment by rphuber** [comment]
I figured out that it had to do with having run the app with debug mode and pulled out those commits and pushed up a cleaner commit.  This has been tested for it's specific use case locally in the android emulator and works.  Please let me know if you have any questions.

**Comment by rphuber** [comment]
@plasmacorral let me know if you have any questions.  We tested this locally on an emulator and got the expected results

**Pull request merged**
