### PR TITLE
fix: Upgrading Appium test failing

### LINKED ISSUE #10825: [Bug]: Upgrading Appium test failing
### Describe the bug

Currently, both upgrading Appium test are failing on main. For `MultipleAccounts.feature`, when the test relogin to the app after upgrading to the app. This is happening because there is a step that execute the Android Back button. We need to remove that step.

For `ConnectedTestNetwork.feature`, the test are failing because whats new modal is not longer appearing after connected to the test network. We need to remove that step.

### Expected behavior

All upgrading test should passed.

### Screenshots/Recordings

_No response_

### Steps to reproduce

Run `wdio/features/Upgrading/MultipleAccounts.feature`  and `wdio/features/Upgrading/ConnectedTestNetwork.feature` 

### Error messages or log output

_No response_

### Detection stage

In production (default)

### Version

7.29.0

### Build type

Beta

### Device

Pixel 6

### Operating system

Android

### Additional context

_No response_

### Severity

_No response_

### PR DESCRIPTION
**Pull request by SamuelSalas**
## **Description**

Currently, both upgrading Appium test are failing on main. For MultipleAccounts.feature, when the test relogin to the app after upgrading to the app. This is happening because there is a step that execute the Android Back button. We need to remove that step.

For ConnectedTestNetwork.feature, the test are failing because whats new modal is not longer appearing after connected to the test network. We need to remove that step.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by Cal-L** [comment]
Could we run an upgrade test again this branch to verify this fix?

**Review by Andepande — DISMISSED** [review]
LGTM

**Comment by SamuelSalas** [comment]
> Could we run an upgrade test again this branch to verify this fix?

@Cal-L the upgrading appium test passed, but the test run failed because of the core ios test suite failed. Apparently it was some setup issue `Error: Unable to update lock within the stale threshold`. I'll rerun it once again.

**Review by chrisleewilcox — APPROVED** [review]
LGTM

**Comment by SamuelSalas** [comment]
@Cal-L https://app.bitrise.io/build/6d4eb117-a80c-4d7f-99f6-46354741a811 upgrade appium test

**Pull request merged**
