### PR TITLE
Show token symbol in verify contract details

### PR DESCRIPTION
**Pull request by blackdevelopa**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
Should show the token symbol when verifying contract details.

**Screenshots/Recordings**
Before:
http://recordit.co/qNXHWrukFz

After
http://recordit.co/Xv4CQeEOeg

**Issue**

Progresses #5872 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by jpuri** [comment]
Hey code change is perfect, again can you plz check about test coverage.

**Review by jpuri — DISMISSED** [review]

**Review by segun — APPROVED** [review]

**Comment by seaona** [comment]
@blackdevelopa I see the issue fixed. The behaviour looks good, I can see the token symbol on Verify Contract details:

https://user-images.githubusercontent.com/54408225/232527835-506d2e9a-b0b4-4d48-9df1-77417dc06c08.mp4

We need x2 dev re-approvals and we can merge it

**Review by jpuri — APPROVED** [review]

**Review by segun — APPROVED** [review]

**Comment by bschorchit** [comment]
I've went ahead and merged it and added the next release label as it had the ✅ from Mariona, Jyoti and Olu 😊

**Comment by blackdevelopa** [comment]
Thank you @bschorchit

**Comment by seaona** [comment]
thank you @bschorchit !!

**Pull request merged**
