### PR TITLE
Improvement/chain ticker

### LINKED ISSUE #2388: Instead of ETH - show me native currency (+symbol)
As a user, when I am on a custom network where the native currency is not ETH, show me the native currency & logo/symbol in the balance thumbnails (e.g., in account switcher, default currency in send/receive flows)

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

I could only find these places:

- Accounts list
- Message of not enough ETH
- Payment requests on custom RPC networks. **it's also now generating the correct deeplinks for other chainId**
- Receive flows

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #2388

### CODE REVIEW

**Review by rickycodes — APPROVED** [review]

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
**Question**

I noticed in https://github.com/MetaMask/metamask-mobile/issues/2388#issue-832174345 it mentions the logo/symbol as well, is that no longer a requirement? 
cc: @omnat 

image

Screen Shot 2021-03-29 at 8 24 34 PM

**Issue 1:** 

When I do the receive flow and scan the deeplink while on xDAI and requesting xDAI I get this with a spinner/white screen 

Screen Shot 2021-03-29 at 8 26 18 PM

I used this QR:
Screen Shot 2021-03-29 at 8 24 55 PM

**Issue 2:** 

I found another place where we still show ETH in the send flow

image

**Comment by omnat** [comment]
cc @wachunei @jakehaugen

**Comment by estebanmino** [comment]
@ibrahimtaveras00 all issues resolved and now we're displaying a gray icon with the first letter of the ticker for custom networks if the symbol of such is network isn't ETH (as rinkeby, and other testnets)

**Review by ibrahimtaveras00 — APPROVED** [review]
All fixes look good, QA Passed 👍🏽

**Pull request merged**
