### PR TITLE
Android deeplink approve modal changes network and works

### PR DESCRIPTION
**Pull request by tommasini**
**Description**
When deeplink to send funds it's pressed and it's needed to change the network, it would only change the network and do not show the approve modal.

**Proposed Solution**
The approve modal appears
Remove unused code

**Code impact**
Low

**Screenshots/Recordings**
Recordings of solution:
With two devices (Huawei P30 pro and Samsung A22, both Android 12)
https://recordit.co/NpxyGiXbVD
With one device:
https://user-images.githubusercontent.com/46944231/179568171-cb51ae76-c784-43bb-bedf-8b584cbdd06f.mp4

**Test Cases**
Case1:
* Select ethereum mainnet as your network
* Open this [deeplink](https://metamask.app.link/send/0x3dD3DfaAdA4d6765Ae19b8964E2BAC0139eeCb40@4/approve?address=0x178e3e6c9f547A00E33150F7104427ea02cfc747&uint256=5e8)
* Notice that the network changed and the modal is openning 

**Issue**

Progresses #3880 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by andreahaku — APPROVED** [review]
LGTM

**Comment by tommasini** [comment]
Tested on two Androids, Samsung and Huawei, both Android 12
(Samsung needed to add the opening links on settings to be working)
https://recordit.co/NpxyGiXbVD

**Review by andreahaku — APPROVED** [review]
LGTM but check the missing analytics, if and what to add there ;)

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
On my Samsung A42 Android 12 when I tap on the deeplink in this PR description in Case 1 I do not get the approval modal.  It only switches networks and lands on Wallet view.....
https://recordit.co/jJJVlJMDCm

**Comment by tommasini** [comment]
Convert this to a draft, still needs development

**Comment by tommasini** [comment]
I'm not able to replicate the issue on this PR, it needs to be an Android 12 device

**Comment by tommasini** [comment]
Closing this PR since it doesn't solve the issue

**Pull request closed without merging**
