### PR TITLE
ci(builds): CocoaPods install without Flipper

### PR DESCRIPTION
**Pull request by leotm**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add the appropiate QA label when dev review is completed
    - `needs-qa`: PR requires manual QA.
    - `No QA/E2E only`: PR does not require any manual QA effort. Prior to merging, ensure that you have successful end-to-end test runs in Bitrise. 
    - `Spot check on release build`: PR does not require feature QA but needs non-automated verification. In the description section, provide test scenarios. Add screenshots, and or recordings of what was tested.
5. Add `QA Passed` label when QA has signed off (Only required if the PR was labeled with `needs-qa`)
6. Add your team's label, i.e. label starting with `team-` (or `external-contributor` label if your not a MetaMask employee)

**Description**

Follow-up
- https://github.com/MetaMask/metamask-mobile/pull/6944

Changes
- Remove `cocoapods-install@2` steps that don't support custom flags like `NO_FLIPPER=1`
- Replace with scripts that `pod install` without Flipper

Refs
- https://github.com/facebook/react-native/releases/tag/v0.71.1
  > Exclude react-native-flipper when NO_FLIPPER=1 to prevent iOS build fail ([f47b5b8b5d](https://github.com/facebook/react-native/commit/f47b5b8b5def41aeb6d5b672928cc57e20fba49d)) by retyui
- https://github.com/bitrise-steplib/steps-cocoapods-install
  - Inputs command flags unsupported

Docs
- https://bitrise.io/integrations/steps/cocoapods-install
- https://devcenter.bitrise.io/en/steps-and-workflows/workflow-recipes-for-ios-apps/-ios--install-cocoapods-dependencies.html
- https://devcenter.bitrise.io/en/dependencies-and-caching/managing-dependencies-for-ios-apps/managing-dependencies-with-cocoapods.html

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

fixes #https://github.com/facebook/flipper/issues/4278

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by leotm — COMMENTED** [review]
Improvement: make this script a BitRise step re-used 3x

**Comment by jpcloureiro** [comment]
Should be good to go once the script gets into a reusable bitrise step  ✅ 

Thanks for looking into this @leotm!

**Comment by leotm** [comment]
`ios_e2e_test` passing on main: https://app.bitrise.io/build/7f2793f5-6040-4be1-be20-9b3b2dd7c34e :suspect:

updating branch with `main` then re-running `ios_e2e_test`

**Comment by leotm** [comment]
e2e round 2, post-[ff06275](https://github.com/MetaMask/metamask-mobile/pull/6955/commits/ff062758ac054cd22e4f1355d63e6da4e5ddb279)

`ios_e2e_test` test run: https://app.bitrise.io/build/31657ded-b32a-47b7-afe5-ce64d70662d4

**Comment by leotm** [comment]
e2e round 3: post-https://github.com/MetaMask/metamask-mobile/pull/6955/commits/530c29e11b3a3f1703c8d332a671eb63136f0485

ios_e2e_test test run: https://app.bitrise.io/build/3986fb7d-ec7c-415a-a236-957f4725c4d3

`build_ios_qa` ...

`build_ios_release` ...

**Comment by leotm** [comment]
- https://github.com/facebook/flipper/issues/3995#issuecomment-1359135987

**Pull request closed without merging**
