### PR TITLE
Direct to proper screen on address QR code scan

### PR DESCRIPTION
**Pull request by EtDu**
https://trello.com/c/V51d5FO6/204-public-address-qr-code-scanning-opens-confirm-screen-should-be-just-the-prefilled-recipient-address-screen

### CODE REVIEW

**Review by rickycodes — APPROVED** [review]

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
**Issue 1:**

When I scan the QR Code from the Receive view, I am correctly sent to to the Send to view, however, upon continuing I see collectible pre-selected with Balance: undefined, with 2 warnings appearing and when I do switch to ETH the Next CTA is disabled and I cannot continue.

Seen here = https://recordit.co/HULaqjSnMe

Screen Shot 2020-10-05 at 7 49 49 PM

**Issue 2:** 

When I go through the request payment flow and I set how much ETH I want, I'm still taken to the Send to view and the same bug as above happens.  I'm under the assumption that when a user goes to the Add funds/receive > request payment > and selects the asset with the value wanted we should take them to the confirm view like usual right cc: @omnat @cjeria? 

seen here = https://recordit.co/TZac6VURZ8

**Comment by omnat** [comment]
**Case 1** >> This behavior is as intended in production - shouldn't change with this (or other) PRs.
When user scans a QR code which is a payment request from someone - we should direct user directly to the confirm screen, with all values correctly pre-filled (asset type, amount, recipient address, network). 
**Question:** This is happening as expected in the prod version. Looks like this PR is breaking this behavior. @EtDu Was this intentional? 

**Case 2** >> This behavior needed to change with this PR. The intended flow should be the following:
When user scans a QR code which is a public address - we should direct user directly to the 'Send to' screen, correctly pre-filled with recipient address. 
**Question:** Why is collectible the default selected asset on the 'Amount' screen. No reason to change that behavior from how it is today in production - @EtDu was this intentional?

**Comment by EtDu** [comment]
@omnat 
https://trello.com/c/V51d5FO6/204-public-address-qr-code-scanning-opens-confirm-screen-should-be-just-the-prefilled-recipient-address-screen
Case 2 is correct, although collectible shouldn't be the default in the amount screen.

**Comment by EtDu** [comment]
@ibrahimtaveras00 
For issue 2 that seems logical. If the payment request QR contains an amount the behavior should function as normal

**Comment by EtDu** [comment]
@ibrahimtaveras00 should behave properly now :)

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Issue 1 seems resolved 👍 

Issue 2 seems to only work when requesting ETH but fails when requesting ERC 20 tokens
Fails when I request KNC (goes to send to view rather than confirm view) seen here = https://recordit.co/18qexARqIT

This works on prod; seen here = https://recordit.co/PbuklCc8YM

**Comment by EtDu** [comment]
@ibrahimtaveras00 Fixed

**Review by ibrahimtaveras00 — APPROVED** [review]
QA Passed 👍

**Pull request merged**
