### PR TITLE
Handle eth_signTypedData_v4 in wallet connect.

### LINKED ISSUE #3008: Use V4 of eth_signTypedData when using WalletConnect.
We should consider using eth_signTypedData V4 instead of V3 for WalletConnect. 
But we would need to warn developers first and give adequate time to migrate.
For reference: https://github.com/MetaMask/metamask-mobile/pull/2990

### PR DESCRIPTION
**Pull request by pauldemarco**
**Description**

Allows the latest eth_signTypedData_v4 to be used via WalletConnect, while keeping full backwards compatibility with existing dApps.

**Issue**

MetaMask does not currently support the latest eth_signTypedData_v4 when used through WalletConnect.

Resolves #3008

### CODE REVIEW

**Comment by pauldemarco** [comment]
@andrepimenta Here's a completely additive; fully backwards compatible change to support v4 signTypedData.

**Review by sethkfman — APPROVED** [review]
Reviewed, dev tested & moving to QA.

**Comment by sethkfman** [comment]
@pauldemarco Is there a specific dapp you were able to reproduce this issue on?

**Comment by pauldemarco** [comment]
> @pauldemarco Is there a specific dapp you were able to reproduce this issue on?

 
@sethkfman just our app that we are developing. I've just pulled down the latest from this PR (with develop merged), and can verify the signTypedData is working. Let me know if there's anything else needed from me for this to pass QA.

**Pull request merged**
