### PR TITLE
fix: WC2 error management and SDK 'authorized' event

### PR DESCRIPTION
**Pull request by abretonc7s**
- Improve wc2 error handling
- Fix 'authorized' bug in sdk
- Prevent reconnection otp screen bypass
- SDK Sessions items automatically refresh

### CODE REVIEW

**Review by andreahaku — DISMISSED** [review]
LGTM

**Comment by christopherferreira9** [comment]
SDK version: 0.3.4-preview.cd77d74 (0.3.4 latest RC)

**Android**
React native:
- React native "Go Back" is flaky resulting in it not applying always.
- Resuming on connection is not working
https://github.com/MetaMask/metamask-mobile/assets/104831203/3eab15f5-606e-4e35-9b88-a1cd1989acde

Web deeplink:
- Doesn't go back
(first connection had issues with socket)
https://github.com/MetaMask/metamask-mobile/assets/104831203/003e9b7e-1e11-46ad-9c8c-f783ba7e44b1

**iOS**
React native:
- Going back is flaky but it works most of the time
https://github.com/MetaMask/metamask-mobile/assets/104831203/509b7c82-90e4-4502-8734-c193ec4dbb8a

Web deeplink:
- Doesn't go back
https://github.com/MetaMask/metamask-mobile/assets/104831203/5902d115-9c56-4c73-99fe-f9e4ff26b73d

**Review by andreahaku — APPROVED** [review]
LGTM

**Comment by christopherferreira9** [comment]
Tested with the current prod versions of all SDK's and the upcoming JS one and it's a pass ✅

**Pull request merged**
