### PR TITLE
fix(SendFlow): Render full amount being sent.

### PR DESCRIPTION
**Pull request by jpcloureiro**
### Description
SendFlow Confirm screen show the amount we are about to send.
Currently it formats to max 5 decimals.
The goal is to show the full amout.

Font will scale (see after video)

### Screen recordings

__Before__

[Before](https://user-images.githubusercontent.com/1649425/185205886-05ae220f-4a47-4f41-9ae6-490fb5eded60.webm)

__After__
<video src="https://user-images.githubusercontent.com/1649425/185205653-d2af0af0-c604-4106-840b-b9066effeba1.webm">

### Checklist

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### Issue

Progresses #3619

### CODE REVIEW

**Review by sethkfman — DISMISSED** [review]
LGTM

**Review by cortisiko — CHANGES_REQUESTED** [review]
hey @jpcloureiro your fix works properly with [native tokens](https://recordit.co/BJZtusAKPT) but not [ERC-20 tokens](https://recordit.co/rV3Kip1BjX)

**Comment by jpcloureiro** [comment]
@cortisiko fixed

[commit 0bdf5ab](https://github.com/MetaMask/metamask-mobile/pull/4123/commits/0bdf5ab21a10b64a4c45183eee83f02a54daf135)

**Comment by cortisiko** [comment]
Found another issue:

- If i have a lot of funds with a particular token:
- I attempt to use max
- numbers after the decimal point are truncated
- see recording here: http://recordit.co/5bgzqIFNG3

you can use my cdavid3.eth test account and import DAI [0xc7AD46e0b8a400Bb3C915120d284AafbA8fc4735] to reproduce

**Pull request closed without merging**
