### PR TITLE
Improvement/assets by chainid

### LINKED ISSUE #2391: View my assets displayed accurately (specific to the network)
As a user, I want to accurately view the assets I own on the currently active network, including accurate balance. 

Acceptance criteria:
- Assets must be assigned to chain ID 
- This should work for both test nets and other chains
- Assets include all token types we support: ERC20, ERC721, ERC 1155

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

Deprecation of `networkType` in favor of `chainId` to store assets.

A migration was added to migrate existing assets

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #2391

### CODE REVIEW

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Looks like the migration didn't get picked up

For example, OMI should not be here under BNB as it belongs to GoChain network

image

Steps:
- build v2.0.1 on both OS’s
- yarn clean && yarn watch:clean
- yarn start:ios and yarn start:android
- import your wallet, add networks + tokens
- stay on either network (before putting app in background stay on BNB or GoChain)
- put app in background
- switch to improvement/assets-by-chainid
- yarn clean && yarn watch:clean
- yarn start:ios and yarn start:android
- login, notice how it’s still the same

**Comment by ibrahimtaveras00** [comment]
This does work when you create a fresh wallet and add the networks and custom tokens

seen here = http://recordit.co/f7zWGgcDIh

**Review by ibrahimtaveras00 — APPROVED** [review]
QA Passed 👍🏽

**Review by andrepimenta — APPROVED** [review]
LGTM!

**Pull request merged**
