### PR TITLE
[REFACTOR] Clear Privacy section

### PR DESCRIPTION
**Pull request by gantunesr**
**Description**

Refactor 'Clear Privacy' setting to TS and extract it from the SecuritySettings file. The functionality should stay the same as it's today.

**Screenshots/Recordings**

As showed in the video, after connecting to a dapp, if the user chooses to clear the privacy data, all connections must be revoked.

https://user-images.githubusercontent.com/17601467/233511519-e6557987-954d-40ef-a87d-b85728d33024.mov

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by sethkfman** [comment]
@gantunesr Can you show a successful E2E test run? I think the label should go to your team.

**Comment by gantunesr** [comment]
@sethkfman can you the reasons for my team's label? Just because I'm the author does not imply that the work is relevant to my team, I as the author will be responsible for any bugs introduced

**Comment by gantunesr** [comment]
Regarding the E2E, I'm waiting on the dev review to solve any comment presented and then run the required workflow

**Comment by cortisiko** [comment]
Hmm chiming in here, this is the right approach. The E2E tests should be triggered after a successful dev review. You should also post the bitrise build with the test run on this PR. 

> Regarding the E2E, I'm waiting on the dev review to solve any comment presented and then run the required workflow

**Comment by chrisleewilcox** [comment]
@gantunesr I think this needs QA.  Please add `needs-qa` label once dev review is complete.

**Review by sethkfman — APPROVED** [review]
LGTM

**Review by cortisiko — APPROVED** [review]
This PR did not require any feature QA. However, I did a light manual smoke test on the security and privacy page. I also ran the e2e tests for both android and iOS. Nothing to report.

**Pull request merged**
