### PR TITLE
Bugfix: custom rpc network

### LINKED ISSUE #903: xdai.io not working
Looks like the TX popup is not showing up. We should look into it.

INFO: https://twitter.com/kyoronut/status/1153709620344438784?s=20

### LINKED ISSUE #1052: if add custom network and goto browser open my dapp, it's ok, but i send tx it can not open Send view.
if add custom network and goto browser open my dapp, it's ok, but i send tx it can not open Send view.

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

This PR

- Fixes txs from dapps using custom rpc networks
- Uses ticker on transaction review instead of ETH symbol, in order to display custom network ticker.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #903
Resolves #1052

### CODE REVIEW

**Review by brunobar79 — COMMENTED** [review]
💯 100

**Review by brunobar79 — APPROVED** [review]
💯

**Comment by yourihua** [comment]
if i change network to custom RPC networks, switch account view not use ticker, it's ETH.

**Comment by ibrahimtaveras00** [comment]
**Issue 1:**

When I'm on mainnet and go to https://dai-bridge.poa.network/ to transfer DAI to xDai I see this on confirm transaction view

image

**Issue 2:**

When I'm on xDAI custom network, then go to xdai.io and send xDAI to another account I don't see fiat amount

image

Also, if I don't have a symbol set on xDAI network I see this:

image

**Review by ibrahimtaveras00 — APPROVED** [review]
All fixes look good, QA Passed 👍

**Pull request merged**
