### PR TITLE
fix: Alias added  to the to address field when added to the contacts

### PR DESCRIPTION
**Pull request by tommasini**
**Description**
When added a contact, it needed to be added to the to address field as well.

**Screenshots/Recordings**
https://recordit.co/2JU6rllQYQ

Transaction review test: (derived to be impacted by the change)
https://recordit.co/4KcFx41spL

**Issue**

Progresses #6571 

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by cortisiko — APPROVED** [review]
@tommasini this is ✅ ✅

**Review by NicolasMassart — APPROVED** [review]
Looks good to me.

**Comment by Cal-L** [comment]
@tommasini When you have a chance, could you base and point this PR to main since it isn't unique to RN upgrade?

**Comment by tommasini** [comment]
I'm closing this PR and opening this [one](https://github.com/MetaMask/metamask-mobile/pull/6671)  branched of main and pointing to it, after we merge it we can update the react native branch and have all the bugs solved

**Pull request closed without merging**
