### PR TITLE
feat: 1957 crash screen redesign

### PR DESCRIPTION
**Pull request by frankvonhoven**
## **Description**

Refactors ErrorBoundary to match [updated designs in Figma](https://www.figma.com/design/DM5G1pyp74sMJwyKbw1KiR/Error-message-and-bug-report?node-id=1-5473&node-type=section&t=98CWfEC4JrKwpNCE-0)

## **Related issues**

Fixes: [#1957](https://github.com/MetaMask/mobile-planning/issues/1957)

## **Manual testing steps**

1. Go WalletView
2. Add:
    ```
    useEffect(() => {
      throw new Error('Test Error');
    }, []);
    ```
3. Restart the app
4. Dismiss the Red Screen
5. See the new Error Screen

## TESTING THE BUILD:
1. Create a QA build in Bitrise
2. force an error
3. report the error
4. check [Sentry](https://metamask.sentry.io/feedback/?feedbackSlug=test-metamask-mobile%3A6031686409&mailbox=ignored&project=2651591&referrer=feedback_list_page&statsPeriod=30d)
5. Should see user feedback in the Sentry report
6. Example:
image

### **Before**

image

### **After**

https://github.com/user-attachments/assets/7dbe5e04-0152-41bc-984a-37cba98c4eeb

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by yanrong-chen** [comment]
Design QA:
1. Can we have 16px padding in between these vertical buttons ("Describe what happened", "Contact support" & "Try again") please?
2. You might have included it but it wasn't obvious in the video: can we have a confirm toast ("Thanks! We will take a look soon") when users submit an error report?
Thank you Frank! Everything else look good!

**Comment by frankvonhoven** [comment]
> Design QA:
> 
> 1. Can we have 16px padding in between these vertical buttons ("Describe what happened", "Contact support" & "Try again") please?
> 2. You might have included it but it wasn't obvious in the video: can we have a confirm toast ("Thanks! We will take a look soon") when users submit an error report?
>    Thank you Frank! Everything else look good!

Updated buttons. Added new video

**Review by Daniel-Cross — DISMISSED** [review]
LGTM!

**Review by vinnyhoward — APPROVED** [review]
This is very cool, nice job @frankvonhoven @yanrong-chen 
LGTM✅

**Review by Daniel-Cross — APPROVED** [review]

**Pull request merged**
