### PR TITLE
Fix cloudflare redirects

### LINKED ISSUE #2170: Cloudflare does not redirect to Web3 dapp
**Describe the bug**
When launching a web3 dapp in the in-app browser, a cloudflare is displayed that does not redirect to the web3 dapp.

**Screenshots**
image
image

**To Reproduce**
1. Using the in-app browser, navigate to a web3 dapp such as yfdai.finance or axieinfinity
2. A cloudflare will display

**Expected behavior**
When a cloudflare is displayed, it should eventually redirect to the web3 dapp after a few seconds.

**Smartphone (please complete the following information):**
 - Device: Realme 7 pro
 - OS: Android 10
 - App Version: 1.0.10
 
 - Device: iPhone 11
 - OS: 14.3
 - App Version: 1.0.10

### PR DESCRIPTION
**Pull request by andrepimenta**
**Description**

This PR fixes cloudflare redirects on Android. Couldn't reproduce it on iOS.

**Issue**

Resolves #2170

### CODE REVIEW

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
When attempting to load axieinfinity.com on android browser, the app crashes; seen here = http://recordit.co/5hCtxzoqag

Screen Shot 2021-01-29 at 7 17 57 PM

Nonetheless, I am able to access yfdai

Screen Shot 2021-01-29 at 7 21 05 PM

**Comment by andrepimenta** [comment]
@ibrahimtaveras00, regarding the first issue, I think this is also happening on older versions so I don't think it's related to this change. Does this also happen on a real device?

**Comment by ibrahimtaveras00** [comment]
I can't reproduce axie infinity issue on current playstore nor on this branch on a real device (tried on pixel 2 running OS 11 and Samsung Note 9 running OS 10

**Review by ibrahimtaveras00 — APPROVED** [review]
👍🏽

**Review by rickycodes — APPROVED** [review]

**Pull request merged**
