### PR TITLE
[FIX] Updating gas price

### PR DESCRIPTION
**Pull request by blackdevelopa**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
There's a bug with updating gas prices for legacy transaction. While calculating the gas fees, `gasFeeEstimates?.gasPrice` is used and not the updated gas price.

Step to QA:
1. For legacy transactions (BSC, OP)
2. Attempt to send token to an address
3. Tap on the estimated gas fee to edit gas price or gas limit
4a. Adjust the gas limit (Works)
4b. Adjust the gas price (Fixed in this PR)

**Screenshots/Recordings**
Before:
https://recordit.co/sS1rEY18DR

Now:
http://recordit.co/FldqSShztZ

**Issue**

Progresses https://github.com/MetaMask/metamask-mobile/issues/5397

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by tommasini — APPROVED** [review]
LGTM!

**Review by andreahaku — APPROVED** [review]
LGTM

**Comment by seaona** [comment]
From QA looks good. I can edit the Gas Price without problem.


https://user-images.githubusercontent.com/54408225/219001507-1a110508-1508-4dcb-acf1-018bb9505cb5.mp4


Only one question, is it expected that the Gas Price for Xiden network is defaulted to 0? 

https://user-images.githubusercontent.com/54408225/219001846-f7c67694-fe88-4b11-8ad7-df7cc8be767a.mp4

**Comment by blackdevelopa** [comment]
Yeah, according to the code, it will seem the set `gasPrice` is 0 and should be adjustable.

**Comment by seaona** [comment]
thank you @blackdevelopa ! I proceed with the merge then :)

**Pull request merged**
