### PR TITLE
fix(11895): remove duplicate networks in incoming transactions settings

### PR DESCRIPTION
**Pull request by vinnyhoward**
## **Description**

We now list `mainnet` networks in the `rpcEndpoints` so the previous logic rendering `mainnet` in separate functions are no longer need. Here is the relevant [PR](https://github.com/MetaMask/metamask-mobile/pull/11705/files) that has those changes. The `rpcEndpoints` do not render in the right order so filtering by Linea Mainnet and Ethereum Mainnet is needed.

## **Related issues**

Related Issue: [#11895](https://github.com/MetaMask/metamask-mobile/issues/11895)

## **Manual testing steps**

1. Go to this settings page
2. Click on "Security & Privacy" 
3. Scroll down and toggle "Show incoming transactions" and confirm that it works
4. Confirm that the duplicate `mainnet` networks are gone

## **Screenshots/Recordings**
test

| Before | After
|:---:|:---:|
|Simulator Screenshot - iPhone 16 Pro Max - 2024-10-24 at 13 37 34|incoming_transactions|

### **Before**

NA

### **After**

NA

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
The app security indicates that 'Mainnet' is not the right name.  Expected that the default network name matches suggested name and is aligned with security checks. We can get PM input if needed.

screenshot-1729802892586

**Review by andreahaku — DISMISSED** [review]
LGTM

**Comment by sethkfman** [comment]
@vinnyhoward Can you provide and update on on the naming of the network?

**Comment by vinnyhoward** [comment]
@sethkfman I think this PR can be merged to unblock release. The issue found by @chrisleewilcox can be fixed in a later PR since things are still functional and the bug found isn't directly related to this fix here. But related to network names as a whole. I've created an [issue](https://github.com/MetaMask/metamask-mobile/issues/12054) to track his finding and create a follow up fix for this release or next.

**Comment by alfeng6** [comment]
Comment from Slack on overall approach:

Let's keep the name from our default RPC URL as the source of truth across our entire application — 'Ethereum Mainnet'. This should be reflected in the network edit modal as well as in the settings page.
Thus, the change should be that Salim will need to update his previous PR to update the "Mainnet" name back to "Ethereum Mainnet", alongside any other chains and their names to match what chainid.network is fetching for MM as a default.

In the future, we can look to allow multiple different names for the same chainid, but for simplicity in the short term, let's stick to a single name from chainid.network.

**Review by chrisleewilcox — APPROVED** [review]
LGTM

**Review by darkwing — APPROVED** [review]

**Pull request merged**
