### PR TITLE
Fix issue #2829 - Lack of full ENS namespace support

### PR DESCRIPTION
**Pull request by tommasini**
**Description**

The ENS name verification was hardcoded and in metamask-extension they have an ens verification already implemented that fix this with a regex expression

Now we can find an account with the name "brantly.art" 

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**https://github.com/MetaMask/metamask-mobile/issues/2829**

Resolves #

### CODE REVIEW

**Review by cortisiko — APPROVED** [review]
🌮 🌮 🌮

**Review by gantunesr — COMMENTED** [review]
@tommasini looks like the tests are failing. Can you update the test cases for the `isENS` method?

**Review by gantunesr — CHANGES_REQUESTED** [review]
LGTM. But can you restore the file `android/app/src/main/assets/fonts/Metamask.ttf`?

**Comment by tommasini** [comment]
@gantunesr Opened another PR here -> https://github.com/MetaMask/metamask-mobile/pull/3825

I tried to restore the file in this branch but when I went to the folder to add it again, the file is already there and git do not recognize any change.

**Pull request closed without merging**
