### PR TITLE
[UPGRADE] Keychain package upgraded to v8.0.0

### LINKED ISSUE #3533: Performance: Upgrade the RN Keychain Library
### **Description**

Upgrade the RN keychain library to the latest version.

### **Technical Details**
- Upgrade the library and apply the pervious versions patching if needed

### **Acceptance Criteria**
-   Biometric, fingerprint & pin code should work the same

### PR DESCRIPTION
**Pull request by sethkfman**
**Description**

Upgrade the keychain package and created a new patch file.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #3533

### CODE REVIEW

**Comment by sethkfman** [comment]
@cortisiko Minimum testing should be done to confirm the following:

**Review by gantunesr — APPROVED** [review]
LGTM. There's no modification in the codebase, only dependences upgrades.

**Comment by gantunesr** [comment]
Related https://github.com/MetaMask/metamask-mobile/issues/1463

**Review by plasmacorral — APPROVED** [review]
Ran into a few issues but nothing that was introduced in this PR. Will follow up with  feedback for (https://github.com/MetaMask/metamask-mobile/issues/3476).

**Pull request merged**
