### PR TITLE
Use default QR code colors

### PR DESCRIPTION
**Pull request by Cal-L**
**Description**

#4490
Remove setting colors of QR codes - Use default QR codes, which is black and white. QR code colors remain the same between light and dark mode. This was updated in 4 places - PaymentRequestSuccess, ReceiveRequest, AddressQRCode, and RevealPrivateCredential flows. 

Here's an example of a QR code in light mode before and after the fix.
BEFORE: 
image
AFTER: 
image

And dark mode
BEFORE:
image

AFTER:
image

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by gantunesr — APPROVED** [review]
LGTM.

**Comment by gantunesr** [comment]
@Cal-L can you improve the description of the PR? For example, including screenshots of the before and after for an easier understanding of the changes for external teams like CS.

**Comment by plasmacorral** [comment]
I am still experiencing the inability to scan a QR from my Android device when in dark mode, from the `QR journal` from the mac app store as reported in the initial issue.

I believe that we need a white border around the QR to resolve this.

**Comment by Cal-L** [comment]
@plasmacorral Just updated all QR codes with white padding around it.
Here's an example of one in dark mode
image

**Pull request merged**
