### PR TITLE
feat: Update assets controllers v^9.0.0

### PR DESCRIPTION
**Pull request by tommasini**
## **Description**
The issue still needs validation.
On this PR was rebased all the packages on assets controllers present on this core branch: `v53-mobile-assets-controllers-patch` with the exception of:
* AccountTrackerController: https://github.com/MetaMask/core/pull/1146/files#diff-917e371461a96a1d0cd3b06add0191b8a6b3d505e961a82d86ca4483c67a6a30
* AssetsUtils - https://github.com/MetaMask/core/pull/1173/files
* NftController - https://github.com/MetaMask/core/pull/1173/files , https://github.com/MetaMask/core/pull/1406/files, https://github.com/MetaMask/core/pull/1455/files
* NftDetectionController - https://github.com/MetaMask/core/pull/1417/files#diff-30fbe131e95d33ea72848ab3efd6f0a34de27eebf85cdf6f749b814fe2ad4f69

Still have a warning when it renders the app from a cold start `undefined is not an object (evaluating 'inputBn.toString')` This error is on the `refresh` function on the AccountTrackerController and still under investigation. Good to mention that the behavior of the app still seems the same, since it recovers from the warning.

Core branch with specific updates: v55-mobile-assets-controllers-patch

**Patches needed**
* **AccountTrackerController**
 * What happened
	- BNToHex function was receiving an value undefined and prompint an error
* Solution
	- Needed to patch AccountTrackerController,[ core commit change line 201](https://github.com/MetaMask/core/commit/7a7c8a3d537633e6250ef57a641e7101f6dd42d6#diff-917e371461a96a1d0cd3b06add0191b8a6b3d505e961a82d86ca4483c67a6a30R201), balance was returning undefined and not being handled
(Keep in mind this commit have more changes Because I'm updating all the changes of the assets-controller since version 8 in this branch, for being easier to update the patches on mobile)
I believe this is fixed on future versions where the networkId is implemented together with a mutex logic

Still need recordings of everything around assets: Tokens, NFTs, privacy settings working 

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

* Import tokens (auto detection, auto complete and manually) - https://recordit.co/njdVHu26q7
* Import NFts (Auto detect, manuall import) - https://recordit.co/hWlGtQnf66
* Import NFts (played around with privacy settings) - https://recordit.co/VBEjX2msko
* Multiple accounts balance - https://recordit.co/wb2CeoP01G
## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by tommasini** [comment]
E2E smoke pipeline: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/a622aa59-02ef-400d-9f10-1109866647c5

**Comment by tommasini** [comment]
new E2E pipeline: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/fec22ec4-758b-403e-93be-07c004e1daa1

**Review by MarioAslau — DISMISSED** [review]
LGTM Tomas!

**Review by georgewrmarshall — APPROVED** [review]

**Comment by georgewrmarshall** [comment]
Approving as code owner to unblock merge but have not tested this in any way. Please get another review from an engineer with context of these changes

**Review by MarioAslau — APPROVED** [review]

**Pull request merged**
