### PR TITLE
[EIP1559] QA

### PR DESCRIPTION
**Pull request by andrepimenta**
Figma: https://www.figma.com/file/NXvUKcZ0Ocu1GPcT7VxRMx/1559---Gas-Controls
Copy: https://docs.google.com/document/d/1qcANOD_E4uvRWcimSCAHmQHJyuPSrHBaiyjryU-7cJk/edit

**Description**

This is a PR for QAing all the EIP1559 functionalities including:
- transactions
- speed up
- cancel 
- swaps legacy
- transaction history view

# For transactions:

Networks to test:
- Mainnet -> should get gas options from legacy API
- EIP-1559 networks (e.g. Ropsten) -> should get gas options from new API
- non EIP-1559 networks (e.g.Kovan) -> should only get a gas price
- Custom networks

Things to test:
- All the different transactions screens: Send flow, dapp transaction, token allowance, any other?
- All the transaction origins: app, dapp, QR, deeplink.
- All the transaction types, send ETH, send ERC-20, send nft
- Smaller screens if everything is reachable by scrolling.

Things to check:
- Check all values (especially gas) on blockchain.
- Check gas values suggested by the dapp or deeplink or QR correspond to the ones on the UI.  You can use https://andrepimenta.github.io/eth_sendTransaction for some of the dapp transactions, good to check if the gas values correspond to the ones suggested by the dapp
- Warnings and validations -> gas too low, too high, insufficient balance, etc.
- When you have a gas selection (low, medium, high), the gas should update every 10 seconds if it has new values. If you have changed the gas on the advanced gas settings, then the gas values should not get updated.

### CODE REVIEW

**Comment by ibrahimtaveras00** [comment]
**Issue 1:** 

Tooltip title is different than mock up.  Also, the text for the last sentence of the first paragraph is no longer bold compared to mock up and current develop

image

**Comment by ibrahimtaveras00** [comment]
**Issue 2:**

The "How should I choose" modal for smaller screens padding is off:

iPhone SE = 
Screen Shot 2021-07-21 at 5 55 27 PM

**Comment by ibrahimtaveras00** [comment]
**Issue 3:** 

Just making sure we do not need to display the icon here:

image

**Comment by ibrahimtaveras00** [comment]
**Issue 4:**

Tapping on "Learn more about customizing gas." link does nothing

seen here = http://recordit.co/8LBDi7qaAD

**Comment by ibrahimtaveras00** [comment]
**Question**
This is not really an issue but more of a question for clarification:
I have my primary currency set to "Fiat", however, everything is still in native by default.  I am assuming this is because I am on Ropsten and we don't have conversions for default/custom networks?

image

**Review by ibrahimtaveras00 — APPROVED** [review]
QA Passed 👍🏽

**Comment by andrepimenta** [comment]
Going to close this one since all the code is in this PR:
https://github.com/MetaMask/metamask-mobile/pull/2798

**Pull request closed without merging**
