### PR TITLE
feat(551): add Linea Mainnet

### PR DESCRIPTION
**Pull request by VGau**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
- Added Linea mainnet network
- Linea mainnet network uses infura rpc url (https://linea-mainnet.infura.io/v3/)
- Added feature toggle to display the Linea Mainnet network only after July 11th
- Created a PR in metamask core to add linea networks support (https://github.com/MetaMask/core/pull/1423)

Note: ⚠️  For now, the linea mainnet url is not working so I cannot record a successful transaction for the new linea mainnet network.

**Screenshots/Recordings**

https://github.com/MetaMask/metamask-mobile/assets/85494462/075559fe-2ff0-4f17-984e-704c37bfa59f

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Comment by VGau** [comment]
> @VGau are these ready for dev-review?

@sethkfman  Yes it is ready for dev review :)

**Comment by sethkfman** [comment]
Do you know when the functional url is going to be in place so you can show a successful transaction?

**Comment by sethkfman** [comment]
@VGau Can you add a video showing this there is no functional impact to displaying the current networks?

**Review by sethkfman — DISMISSED** [review]
LGTM

**Comment by sethkfman** [comment]
@cortisiko This is a dormant feature that is enabled via infura flag. You will not see any functional difference. It should only need regression/e2e QA but I wanted you to confirm.

**Comment by cortisiko** [comment]
hey @VGau a couple of things:

- What should be the behavior when linea mainnet is turned on? Should the network appear in the default network list like mainnet or any other test net? 

-  is there a way to verify that the feature flag is working? We don’tt necessarily have to use the linea mainnet rpc url to test. what if we use another rpc url just to make sure when we toggle the feature on the app doesnt break.

- Can you do some smoke tests to verify that mainnet, an infura-supported custom net like polygon is still working?

**Comment by VGau** [comment]
> hey @VGau a couple of things:
> 
> * What should be the behavior when linea mainnet is turned on? Should the network appear in the default network list like mainnet or any other test net?
> * is there a way to verify that the feature flag is working? We don’tt necessarily have to use the linea mainnet rpc url to test. what if we use another rpc url just to make sure when we toggle the feature on the app doesnt break.
> * Can you do some smoke tests to verify that mainnet, an infura-supported custom net like polygon is still working?

Hey @cortisiko : 
- The linea mainnet network will appear in the default network list like mainnet
- If you want to display the Linea mainnet network for your tests you can reverse the boolean result of this function `shouldShowLineaMainnetNetwork` in `app/util/networks/index.js` 
- Yes sure I can do a smoke test :)

**Comment by VGau** [comment]
> @VGau Can you add a video showing this there is no functional impact to displaying the current networks?
> 
> Also, can you add a description how you plan to test the network and if it fails how it will be disabled? This will help QA understand the feature is triggered from a specific response on infura endpoint.

By default the linea mainnet network won't be displayed on MM. It will be displayed only if the current date time is higher than July 11th and if the linea mainnet rpc url is working.

**Comment by sethkfman** [comment]
@VGau Can you resolve the conflicts? It looks like the testnet PR is causing issues. We will get the PR merge on Tuesday.

**Review by sethkfman — APPROVED** [review]
LGTM

**Pull request merged**
