### PR TITLE
docs: add JSDoc to deprecate Alert in favor of BannerAlert

### PR DESCRIPTION
**Pull request by Libens-bufo**
**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

Added deprecation JSDoc to deprecated code in Alert.tsx

**Screenshots/Recordings**
image

image

**Issue**

#6890 Deprecate Alert in favor of BannerAlert

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

### CODE REVIEW

**Comment by Libens-bufo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by georgewrmarshall — APPROVED** [review]
LGTM! Thanks for your contribution @Libens-bufo 
- pulled branch and checked deprecation identifiers and notice ✅

**Comment by georgewrmarshall** [comment]
Hey @Libens-bufo, we recently updated SonarCloud settings so external contributor PRs would pass but I think you may have to close this PR and create a new one. Would you mind doing that and we should be able to get this in

**Comment by Libens-bufo** [comment]
Closing and creating a new one.

**Pull request closed without merging**
