### PR TITLE
feat: Support token detection on linea

### PR DESCRIPTION
**Pull request by bergeron**
## **Description**

Enables token autodetection on Linea

## **Manual testing steps**

1. Restore a wallet containing tokens (like WETH, USDC) on Linea 
2. Tokens should be automatically detected and suggested for import (`N new tokens found in this account`) 
3. Click `Import tokens` to manually import
4. There should be a search box that suggests tokens as you type their symbols

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/3500406/c3fb7c64-bf5b-4415-be31-a6bdb57c800a

### **After**

https://github.com/MetaMask/metamask-mobile/assets/3500406/4b1f5c12-4f41-4a8a-891d-04b0fb6dd03d

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Review by Cal-L — DISMISSED** [review]
LGTM. what is that yellow box error though?

**Review by chrisleewilcox — CHANGES_REQUESTED** [review]
Hi @bergeron.  I'm am not able to load asset balances on Linea Mainnet on my android emulator.  Can you take a look?
https://recordit.co/VKuFxuwyMy

**Comment by bergeron** [comment]
Fixed missing prices in https://github.com/MetaMask/metamask-mobile/pull/8171/commits/e02095a72379304c2cbca91643e3fe7ab74ccb63,  here's the before/after:

image

**Review by chrisleewilcox — APPROVED** [review]

**Review by chrisleewilcox — APPROVED** [review]
Smoke: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/7b4fd2a3-a235-4489-806b-0bb4f0eff0ff
Regression: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/56c576bd-3624-460e-9218-27b791f983bb

**Pull request merged**
