### PR TITLE
feat(ramp): popular region and search states

### PR DESCRIPTION
**Pull request by wachunei**
## **Description**

This PR improves the Region selector for Ramp flows by removing duplicate code and adding these features:
1. Default list is now shown in sections (Popular Regions and Regions)
2. Searching will also match and display states

## **Related issues**

Fixes: #

## **Manual testing steps**

1. Go to Ramp flow
2. Open a Region modal (Region or Amount screens)
3. Confirm the changes from descriptions

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

### CODE REVIEW

**Comment by bkirb** [comment]
@wachunei LGTM I verified this change for regions ✅

**Comment by wachunei** [comment]
@bkirb can you quickly verify again? by self reviewing I found an issue and I added a fix to avoid recomputing the fuzzy search engine on every stroke

**Review by sethkfman — APPROVED** [review]
LGTM

**Comment by bkirb** [comment]
@wachunei LGTM I verified with the latest changes ✅

**Pull request merged**
