### PR TITLE
Improvement/gas estimations

### LINKED ISSUE #1998: Update gas estimation API (across the app)
Extension's PR:
https://github.com/MetaMask/metamask-extension/pull/9867

Remove ETH Gas station, and use MetaSwap API instead (GasNow primarily, Etherscan as fall back)

### PR DESCRIPTION
**Pull request by estebanmino**
**Description**

Use codefi API to get the gas estimates

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #1998

### CODE REVIEW

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
On smaller screens, I can't scroll to read all of the messaging on the bottom

Left (iPhone 5s) and Right (Nexus S)

Screen Shot 2021-01-06 at 4 33 26 PM

**Review by ibrahimtaveras00 — APPROVED** [review]
👍🏽

**Review by andrepimenta — APPROVED** [review]
LGTM! 👍

**Comment by tomw1808** [comment]
Not sure if this is the right location to raise that issue, but doing gas-estimations on non-public networks is cause issues for us. Essentially what happens is that on mobile the hard-coded gasPrice is being overwritten.

Can this be done only if no gasPrice is set in the transcation object and only if it's not a custom chain?

**Pull request merged**
