### PR TITLE
[FIX] Update selected network when delete network manually inserted

### PR DESCRIPTION
**Pull request by tommasini**
**Description**
When comparing two rpc url, and one was inserted manually, we were comparing the selected network url (example: "https://rpc.gnosischain.com") with the rpc url of the network we want to delete (example: "https://rpc.gnosischain.com") and this is false, only when it's true we change the network to mainnet

**Proposed Solution**
Comparing two rpc url with an existing function, that converts the rpc url to an object for we to be sure they are the same.

**Test Cases**
Case 1:
* inserted manually xdai chain
* deleted on Settings/Networks
Case 2:
* Inserted binance smart chain via network picker
*  deleted on Settings/Networks
Case 3:
* Inserted Avalanche network via network picker
* Change selected network to goerili
* Deleted avalanche network on Settings/Networks
* Expected to remain on goerli network

**Screenshots/Recordings**
https://recordit.co/DtgAlb5F23

**Issue**

Progresses #5117 

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

### CODE REVIEW

**Review by ullashb — APPROVED** [review]

**Review by ullashb — APPROVED** [review]

**Review by blackdevelopa — APPROVED** [review]
LGTM

**Review by olenapankina — CHANGES_REQUESTED** [review]
**Tested on**
Samsung Galaxy M21 Android 12, One UI Core version 4.1
iPhone Xr iOS 16.1.1

**Issue_01:** User is switched to the Mainnet after deleting custom network while on a different custom network
**Steps to reproduce:**
1. Select Avalanche network via network picker
2. Change selected network to goerili
3. Go to Settings/Network
4. **Open** Avalanche network
5. Note that the network is not changed to Avalanche
6. Click delete
7. Go back to the wallet

**Actual result:** user is on Mainnet [5219_Issue_01.mov](https://user-images.githubusercontent.com/116747263/209388300-42a698d9-3961-4484-a4b4-f6eccc8c9af9.mov)
**Expected result:** user is on goerli network

**Note:** the bug will not be reproducible if you delete the network by hard pressing Avalanche network and deleting it from the pop-up. [5219_expected.mov](https://user-images.githubusercontent.com/116747263/209388373-cb7e77f3-e289-4aa2-8070-cdd09dfc03b7.mov)

**Review by Fatxx — APPROVED** [review]
LGTM

**Review by olenapankina — APPROVED** [review]
Tested on
Samsung Galaxy M21 Android 12, One UI Core version 4.1
iPhone Xr iOS 16.1.1
fix/5117-network-picker-not-update-correctly: commit 87c241a6d02e90b3aec865c51323c4a69afb9abe

User is able to switch the network, the network picker is updated accordingly. Issue_01 confirmed fixed.
e2e tests passed

**Pull request merged**
